### ISSUE TITLE
Pages vs subpages

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#101]
When I started translating the panel in French, I had trouble getting what exactly are subpages. Are they different from regular pages? After I digged a bit deeper, turns out they're the same, a subpage is just a page "inside" or another page.
Actually even the top-most pages like "About" and "Projects" in the Starterkit are subpages, even though there's no page above them. So every page is also a subpage in the end.
Another issue is that the context in not very obvious in the sidebar. There is a link to add "Subpages", but subpages of what? Of the current page, which name is visible in the topbar (the right-most item in the breadcrumb, not highlighted) or in the form on the right side of the screen. I think it could be more obvious.

I'm a recent Kirby user, some obvious things may escape me, but here are a couple suggestions.

1. Wording:

  - Name "pages" just that. No more "subpages". Perhaps use "parent page" and "child page" instead in the docs?
  - Use link titles like "Add a new page in Projects" to give an explicit context.

2. Interface:

  - Add the current page title at the top of the sidebar.
  - As you can see in the beta 1 screenshot below I also moved the new subpage link below the subpages list, but you already did something similar in beta 2.

![subpages](https://cloud.githubusercontent.com/assets/193492/3869326/174afd0a-208b-11e4-8ef1-889a35686df0.png)

**Comment by bastianallgeier** [comment]
I'm working on this for one of the next releases: #39 This should finally fix this thing. I will keep the older ticket updated.
