### ISSUE TITLE
Fetch ALL page children with select field

### ISSUE THREAD

**Issue by olach** [getkirby/panel#1029]
A feature request for the select field:

Right now we can only fetch pages from a parent page with these two options:

- children – selects all *direct* children of the parent page (first level)
- grandchildren – select all grandchildren of the parent page (second level)

I would propose an option to select *all* children of a parent page, several levels deep.

**Comment by texnixe** [comment]
This is already possible with the seemingly undocumented `index` option, just found it in the source code.

**Comment by olach** [comment]
Oh thanks!

Just to clarify for other readers, here is a sample blueprint field for a select field that lists all descendant pages from a parent page:

```
type: select
query:
  page: specify_your_parent_page_here
  fetch: index
```
