### ISSUE TITLE
Wierd checkboxes behaviour

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1032]
If I click the label for a checkboxes field I get this:

![checkboxes](https://cloud.githubusercontent.com/assets/927011/24705660/36ef3fd0-1a0d-11e7-9107-cf3e525d4395.gif)

It checks and unchecks the first checkbox. Clicking a label is often to activate the form field, not change it.

An common behaviour is to click outside an element to deselect it. If that is done in this case and I'm over the label, a checkbox value is changed instead of the deselection of the field.

I suggest to just unattach the connection between the label and the first checkbox.

**Comment by lukasbestle** [comment]
This is fixed on the develop branch.
