### ISSUE TITLE
add class in dom tree if page has been edited

### ISSUE THREAD

**Issue by bnomei** [getkirby/panel#1037]
if the panel would add a class like `pageHasBeenEdited` to the dom tree plugins javascripts could check that value and update their behaviour accordingly.

I miss that dearly since I am extending the panel more and more for my customers.

**Comment by lukasbestle** [comment]
In which situation would you need the class exactly? When the "you have unsaved changes" message is displayed?

**Comment by bnomei** [comment]
some of my panel extension trigger an api call processing data on the current page object of the panel. if the page has not been saves yet i would like to disable that api-call-button. right now i have to go with a 'please save before pressing this button' help text which is not very save nor pretty.

**Comment by jenstornell** [comment]
@bnomei Maybe you can check if the content textfile exists before processing the data, as a workaround at least?

**Comment by bnomei** [comment]
@jenstornell i am less worried about if the page data exists at all but more if its the most current one.

**Comment by lukasbestle** [comment]
If I understand you correctly, you could check in the DOM if the "you have unsaved changes" message is displayed.

**Comment by bnomei** [comment]
good idea. thanks.

**Comment by lukasbestle** [comment]
You can reopen this issue if that solution doesn't work. :)
