### ISSUE TITLE
Upload of files containing `@` char / IIS server

### ISSUE THREAD

**Issue by Stolzenhain** [getkirby/panel#1040]
Hello! We just noticed that uploading files containing `@` chars leaves them uneditable / undeletable on an Azure/IIS server via panel. The only option is to delete/rename the files via FTP. 

Guessing Apache has no problems here; didn't test though.

So the question is: Is there a way to prevent this – maybe by extending the filename escaper on this project?

**Comment by lukasbestle** [comment]
Hm, that's strange. The `@` sign is a normal allowed character in URLs. What error do you get if you click on the image in the Panel?

**Comment by Stolzenhain** [comment]
It's showing `file not found`, in the editor as well while accessing the image itself. It shows up in the file list though, as well as on FTP, obviously. Direct read access doesn't seem to work though.

That's almost certainly a specific behaviour of this hosting (changing the `.htaccess` accordingly was not uncomplicated to begin with; I recall IIS servers not being officially supported).

So the question is: Is there any way we can use the file upload hook or extend the filename escaping to rename the file on upload?

**Comment by lukasbestle** [comment]
IIS does not use `.htaccess` files, those servers have their own configuration files.

You are right that IIS is not officially supported by Kirby. We won't be adding a built-in workaround for this as each workaround has its own disadvantages for other users.

You can use a hook like this to rename all uploaded files though:

```php
<?php

kirby()->hook(['panel.file.upload', 'panel.file.rename'], function($file) {
  $currentName = $file->name();
  $newName     = str_replace('@', '_', $currentName);
  
  if($currentName != $newName) {
    $file->rename($newName . '.' . $file->extension());
  }
});
```

**Comment by Stolzenhain** [comment]
Cool, thanks for the hint! – this is the most solid solution in this case.

And you are right, we actually converted `.htaccess` settings to a `Web.config`file – a fact I luckily had already forgotten.
