### ISSUE TITLE
File upload issues in IE 11

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#1042]
Some files get uploaded while others aren't, with no apparent rule to it. Sometimes a file that is not uploaded as a single file, does get uploaded when multiple files are selected for upload.

When a file does not get uploaded, there is nothing in the network tab, as if the request was not sent at all.

See [this issue](https://forum.getkirby.com/t/unable-to-upload-images-files-in-internet-explorer-in-panel/5987/20) in the forum.

**Comment by lukasbestle** [comment]
Solution seems to be in [this post](https://forum.getkirby.com/t/unable-to-upload-images-files-in-internet-explorer-in-panel/5987/22?u=lukasbestle). Still needs to be validated and tested in different browsers.

**Comment by MathiasGmeiner** [comment]
I can confirm that, I changed it in `panel/assets/js/dist/panel.min.js` to
```
t("[data-upload]").on("click",function(){n.find("input[type=file]").on("change",function(){i(this.files)});return n.find("input[type=file]").trigger("click"),!1})
```
