### ISSUE TITLE
datetime with time format throwing error

### ISSUE THREAD

**Issue by calebgrove** [getkirby/panel#1046]
When the time format for the `datetime` field is set to `12`, the panel will refuse to save any changes if the time part of the field is filled, saying "Please fill in all fields correctly". The error printed below the field says `strpos() expects parameter 1 to be string, array given`.

Blueprint:

~~~~ yaml
title: Event
pages: false
files: true
fields:
  title:
    label: Event Title
    type: text
  date:
    label: Date & time
    type: datetime
    required: true
    time:
      format: 12
~~~~

**Comment by lukasbestle** [comment]
This is now fixed on the develop branch. The whole `datetime` field wasn't prepared for 12 hour time.
