### ISSUE TITLE
Drag structure empty?

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1054]
I installed a fresh installation of Kirby 2.4.1 without plugins (starterkit) with a structure field. Am I supposed to be able to drag the gray empty block around? I see no good reason for that.

![structure-drag](https://user-images.githubusercontent.com/927011/26867940-7835bd8a-4b67-11e7-948b-bae619b326b5.gif)

**Comment by lukasbestle** [comment]
That doesn't make any sense at all. We will take a look at it.

**Comment by lukasbestle** [comment]
Fixed on the develop branch.
