### ISSUE TITLE
Headline without label gets weird

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1061]
**With label**

![image](https://user-images.githubusercontent.com/927011/27327379-bb1e903a-55ae-11e7-9036-b637dd5e2fd4.png)

```text
headline:
    label: My headline
    type: headline
```

**Without label**

![image](https://user-images.githubusercontent.com/927011/27327433-dd5a7236-55ae-11e7-85f1-210f6d5e754d.png)

```text
headline:
    type: headline
```

**Without label - Suggested result**

![image](https://user-images.githubusercontent.com/927011/27327513-1c202ed4-55af-11e7-8e2b-26dc98637d80.png)

**Comment by lukasbestle** [comment]
Fixed on the develop branch.
