### ISSUE TITLE
Panel form id

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/panel#1062]
I ran into a problem when referencing a form in the panel form method.
I don't know if I'm missing something but in my understanding this should work.

```php
// does not work
// file does not exists https://github.com/getkirby/panel/blob/master/app/src/panel.php#L320
$form = $parent->form(__DIR__ . DS . 'form.php', function($form) use($parent, $self) {
  …
});

// does work 
$form = $parent->form(str_repeat('..' . DS, 4) . 'site' . DS . 'plugins' . DS . 'talks' . DS . 'form', function($form) use($parent, $self) {
  …
});
```

I'm not quite sure why the [`file_exists()`](https://github.com/getkirby/panel/blob/master/app/src/panel.php#L314) function somehow returns false in this context.

Reference to the demo plugin
https://github.com/lukaskleinschmidt/kirby-custom-add-form

**Comment by lukasbestle** [comment]
With `$parent->form()`, you are not actually calling `$panel->form()` directly but [`$page->form()`](https://github.com/getkirby/panel/blob/master/app/src/panel/models/page.php#L144-L146).

As you can see, this method is a shorthand and inserts a path name for the internal forms.
You can use this for your custom forms instead:

```php
$form = panel()->form(__DIR__ . DS . 'form.php', $parent, function($form) use($parent, $self) {
```

**Comment by lukaskleinschmidt** [comment]
Uh makes sense. Thanks for info.
