### ISSUE TITLE
Error when trying to add a new user Kirby 2.5.0

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#1064]
https://forum.getkirby.com/t/possible-issue-with-user-kirby-2-5/7783

**Comment by bnomei** [comment]
confirmed. client almost killed me. :-(

**Comment by texnixe** [comment]
I think this can be fixed in line #28 of panel/app/forms/users/user.php:

```
if($user && !$user->password()) {
```

**Comment by nilswindisch** [comment]
I can confirm, that editing this line makes it possible to add users again.

**Comment by lukasbestle** [comment]
Sorry for that bug, I actually verified that user creation works before pushing this change, but apparently I tested with an older version of the "user without password" feature.
This is now fixed on the develop branch.
