### ISSUE TITLE
Inconsistency sidebars, page and site

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1069]
When working with one of my plugins I noticed an inconsistancy in the sidebar/sidebars.

https://github.com/jenstornell/kirby-headline-jump/blob/master/fields/headlinejump/assets/js/script.js#L21

The sidebar for a page has this structure:

```html
<div class="sidebar-content section">
</div>
```

The sidebar for site has this structure:

```html
<div class="sidebar-content">
  <div class="section">
  </div>
</div>
```

It means that the selectors for plugins needs to act a bit different.

```text
.sidebar-content.section // Page
.sidebar-content .section // Site
```

Maybe there are good reasons for the differences but I could not find any.

**Comment by lukasbestle** [comment]
There probably aren't, but we are not going to change this in v2, there are more important issues. I hope that's OK.

**Comment by jenstornell** [comment]
I understand that there are more important things to fix.

But closing the issue? For me that means "solved" or "wontfix", to never be seen again. Maybe you have another way of looking at it.

I would probably use a label for it called "future" or "maybe later".

**Comment by texnixe** [comment]
As @lukasbestle said, we won't fix this in v2, so it doesn't make sense to leave this open (won't be relevant in a future version of Kirby).

**Comment by jenstornell** [comment]
>won't be relevant in a future version of Kirby

It won't be relevant, because of major UI changes to the panel v3? That's how I interpreter it anyway. Interesting if that's the case. 😃

Closing of this issue accepted. Thanks @lukasbestle and @texnixe.

**Comment by texnixe** [comment]
> That's how I interpreter it anyway. 

Yeah, stay tuned 😮 !
