### ISSUE TITLE
Add new user in kirby 2.5.1

### ISSUE THREAD

**Issue by jonabaptistella** [getkirby/panel#1071]
I think I found a small bug in the panel. When I click the "Add a new user" button in the panel under "Users" I get this error. 

![screen shot 2017-07-05 at 16 46 37](https://user-images.githubusercontent.com/2127627/27882272-6b9af652-61a2-11e7-8b5f-f034d8fb74e1.png)

A hotfix had been nice.

**Comment by lukasbestle** [comment]
This has been fixed in 2.5.2 yesterday. ;)
