### ISSUE TITLE
radio with options query empty not savable

### ISSUE THREAD

**Issue by MrApe** [getkirby/panel#1073]
If a radio field in blueprint (`type: radio`) has an options query set (e.g. `options: images`) but the query returns no results, the page cannot be saved. It throws a warning, that required fields are not filled.

Example:

```
  image:
    label: Image
    type: radio
    options: images
```

Leads to no radio buttons (as intended, since no images are uploaded) and an error while saving:

![bildschirmfoto 2017-07-12 um 09 53 59](https://user-images.githubusercontent.com/98466/28107499-51ab7cd0-66e8-11e7-847a-0f691c19c47e.png)

![bildschirmfoto 2017-07-12 um 09 53 36](https://user-images.githubusercontent.com/98466/28107505-542792aa-66e8-11e7-8e27-758e5db38788.png)

**Comment by texnixe** [comment]
Does this happen no matter if the field is required or not?

**Comment by MrApe** [comment]
Yes happens in any case

**Comment by texnixe** [comment]
I think the radio field should probably have its own validate method, the validate method inherited from the InputListField will return false if the value and the options array are empty.

**Comment by lukasbestle** [comment]
The error message is fixed. Regarding the placeholder I have opened a new issue as this is rather something for v3.
