### ISSUE TITLE
Can't access panel, ini_set() error

### ISSUE THREAD

**Issue by leamcg** [getkirby/panel#1075]
Hi!

I just put my website online, but whenever I try to connect to the panel, I get this error:

`ini_set() has been disabled for security reasons`

Any idea where this comes from?
On local, it works fine.

**Comment by texnixe** [comment]
Do you have access to the php.ini file on your server? See this [Stackoverflow](https://stackoverflow.com/questions/34082632/warning-ini-set-has-been-disabled-for-security-reasons) answer.

BTW: the place to ask such questions is the [Kirby forum](https://forum.getkirby.com).
