### ISSUE TITLE
Changing template only removes old text file of currently active language

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#1077]
The non-active text file remains in the folder causing issues.

**Comment by lukasbestle** [comment]
Fixed on the develop branch.

**Comment by alexandre-combemorel** [comment]
This ticket might be open again I guess, 

the correction is deleting the file of the current language used but not replacing other files languages whereas a template for all languages is created. 
Basically the current language used is updated, all the others languages get new files template when ever the template change.

**Comment by alexandre-combemorel** [comment]
@lukasbestle should we re open the ticket?

**Comment by texnixe** [comment]
I don't quite understand what you mean? In my test, all content files for all languages are renamed according to the newly selected template name as it is supposed to be.

**Comment by alexandre-combemorel** [comment]
Yes, sorry I struggled to explain that. So yes that's what I mean, is the website have more than one langue this case happen when a page is create:
`template.en.txt, template.de.txt, ...`
and if we change the template, the current language of the page modified will be changed, but all the other language file template will stay as they are.

**Comment by texnixe** [comment]
> and if we change the template, the template with the current language will be changed, but all the other language file template will stay as they are.

Which Kirby version are you using? This problem does not exist in version 2.5.5 anymore.

**Comment by alexandre-combemorel** [comment]
I'm on 2.5.5 the latest one. I just tested again to make sure. I show you the screenshot result.
I created a test page with a default.*.txt template, my user edit the page in german so (de). And I changed template 2 times with imprint.yml and then to jobs.yml. Here are the files that I get at the end:
<img width="143" alt="screen shot 2017-09-07 at 15 58 00" src="https://user-images.githubusercontent.com/24472130/30167173-d80c9582-93e5-11e7-93d2-7bf64bcbd116.png">

**Comment by texnixe** [comment]
I'm afraid I can't reproduce this. I tested in a fresh langkit. No matter if I change the template in the default language or in the non-default language, I do not end up with old text files.

**Comment by alexandre-combemorel** [comment]
Alright, that's weird. Ok I will check deeper what it could be, I did check the page.php file, it's well updated with the 2.5.5 version.  Quite mysterious

**Comment by texnixe** [comment]
Could you please test with a fresh langkit as well?

**Comment by alexandre-combemorel** [comment]
Ok I think I found the issue, I took a fresh langkit pack the problem was still there. With debugger I realised that in page.php:
```
foreach($this->site()->languages() as $lang) {
        $old = $this->textfile($oldTemplate, $lang->code());
        $new = $this->textfile($newTemplate, $lang->code());
        f::move($old, $new); 
/* the move function at the first loop the old.de.txt file is renamed in new.de.txt, second loop I have the old.en.txt file but the new.en.txt already exist then the move function on f.php line 341 return false and the old.en.txt is not renamed as the new.en.txt is created at the loop before I imagine, not sure which function is responsible of that */
        $this->reset();
        $this->updateForNewTemplate($oldTemplate, $newTemplate, $lang->code());
      }
```

**Comment by texnixe** [comment]
As I said, I can't reproduce this issue, the new.en.txt can't possibly be created prior to the second loop, because it only gets the file in the second loop and php is executed sequentially.

**Comment by texnixe** [comment]
I did some more tests and I think it has to do with the order of the languages and the `update()` method. That is, if the non-default language is updated first, it does not work.

**Comment by alexandre-combemorel** [comment]
Alright, thanks for information !
Ok bug still open then.

**Comment by texnixe** [comment]
We have to make sure that we sort `site()->languages()` so that the default language is the first item in the collection.

**Comment by alexandre-combemorel** [comment]
@texnixe sorry about that, but I did my test again, my default language is german and that is the first language in the collection which create (during the first iteration) 2 templates: `template.de.txt, template.en.txt` and then block the second iteration because the `template.en.txt` was already created.

Are you sure the default language should be first or rather last?

**Comment by texnixe** [comment]
I did my tests with a fresh langkit, where originally the default language is English. With this version in place, everything works fine (i.e. the default language is the first language if I `dump($site->languages())`).

Then, I set the default language to German in the config, without changing the order of the languages. And now I end up with an additional text file, in this case a text file with the name of the original template and an English language extension, which is the non-default language now, which is the first in the language collection. If I change the order of the languages again in the config, i.e. default language first, the problem goes away.

**Comment by alexandre-combemorel** [comment]
Alright ! 
So as a temporary solution I will definitely do that. 
Thanks a lot for the investigation !

**Comment by lukasbestle** [comment]
Fixed on the develop branch.

The fix was actually exactly what @texnixe proposed. The [`updateForNewTemplate` method](https://github.com/getkirby/panel/blob/master/app/src/panel/models/page.php#L630) uses `$page->update()` and that, you guessed it, depends on the intended template of the default lang. If the default lang isn't updated first, it won't work.
