### ISSUE TITLE
K2.5.3 missing sortFiles() method in site options

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#1078]

**Comment by JimmyRittenborg** [comment]
Thought it was just me going nuts 🙈

**Comment by texnixe** [comment]
I resolved it by adding 

```
public function sortFiles() {
    return $this->site->blueprint()->files()->sortable();
  }
```
to `/panel/app/src/panel/models/site/options.php`

**Comment by lukasbestle** [comment]
Ah, shoot! That's exactly why it's so important to have unit tests for everything in Kirby 3.
We will make a hotfix.

**Comment by lukasbestle** [comment]
Fixed on the develop branch.
