### ISSUE TITLE
Removing blueprint field leaves empty field in /content

### ISSUE THREAD

**Issue by dnspnjrs** [getkirby/panel#1086]
As the title says, when I remove an old field in the blueprint .yml and update the page via the panel, the removed field is left untouched in the /content folder. 

Is there a way to maybe "clean" the content folder of every blueprint when the linked page is updated? Instead of manually removing the fields in /content? I've tried passing "null" to the field but it stays firmly into place when saved.

**Comment by texnixe** [comment]
You could do that with a `panel.page.update` hook; or set the field to null programmatically with `$page->update()`.

```
foreach($page->children() as $p) {
  $p->update(array(
    'fieldname'  => null
 ));
}
```
