### ISSUE TITLE
Trailing Slash removal via .htaccess can break the panel dashboard

### ISSUE THREAD

**Issue by fitzage** [getkirby/panel#1093]
I was running into a redirect loop issue when logging into the panel. It seemed to be because `/panel` was redirecting between `/panel` and `/panel/`.

It turns out that the method we had implemented long ago to remove trailing slashes (because google treats `/blog` and `/blog/` as different URLs) was breaking the panel, because the panel forces a trailing slash on the main dashboard page.

It seems to me that most people don't want a trailing slash (and indeed, when kirby generates URLs, it generates them without the trailing slash), so having the panel dashboard force the trailing slash is backwards from everything else, and should be reversed to not have a trailing slash so it doesn't conflict with anything else.

For now I found a method for removing the trailing slash on public pages that does not break the panel redirects (seems like it might be as simple as just putting the slash removal code above the panel redirect options), but I think this panel behavior should be changed anyway.

**Comment by lukasbestle** [comment]
The Panel itself doesn't want the trailing slash, it's Apache that sees the `panel/index.php` file and redirects because index files of directories always have a trailing slash. So there's nothing we can do about this. :)
