### ISSUE TITLE
Problem when trying to replace SVG

### ISSUE THREAD

**Issue by alexandre-combemorel** [getkirby/panel#1095]
Hi all,

I saw that a correction for svg mime was added on:
`/kirby/vendor/getkirby/toolkit/lib/f.php` line 648

But I have a problem when I try to replace an svg through the panel. The type of the file uploaded is detected different than the type of the file that I try to replace (For information they are exactly the same, I did try to auto replace the same file). 

I get an 500 error with this message `{"status":"error","code":0,"message":"The uploaded file must have the same file type"}` from this php file `kirby/panel/app/src/panel/models/page/uploader.php on line: 78`

Does the difference come from the different file systems of my computer and my server or is it just kirby checking the type at the wrong place or something else?

Thanks in advance !
Cheers

**Comment by lukasbestle** [comment]
Hm, it works for me in every browser I tested, so I can't reproduce this issue.

Could you please tell me more about your setup and maybe send me an example SVG that doesn't work?

**Comment by alexandre-combemorel** [comment]
Hi @lukasbestle , I did try the same manipulation to reproduce the bug. I couldn't.
May be the file encoding that we did try to upload at this time was not well encoded.
Let's consider the ticket close because I won't have more information.

**Comment by lukasbestle** [comment]
Alright. Feel free to reopen this issue in case you have this issue again. Thanks!
