### ISSUE TITLE
Only Admin can edit users

### ISSUE THREAD

**Issue by kraftner** [getkirby/panel#1097]
Currently it seems as if due to [this](https://github.com/getkirby/panel/blob/370e9767766c2d9404bcbaf0fd1f7922d9458bd1/app/src/panel/models/user.php#L46) (as already previously reported [here](https://forum.getkirby.com/t/possible-bug-with-user-permissions-in-user-update/6343)) only admins can actually edit users other than themselves, no matter what `panel.user.update` is set to. This makes this permission pretty much pointless.

**Comment by texnixe** [comment]
True, it does not make sense. If a non-admin user can create users, this user should be able to update users. Also, when creating a new user, a non-admin user cannot choose a role for this new user.

**Comment by kraftner** [comment]
Yeah, but I think changing the role is another, separate issue.

**Comment by texnixe** [comment]
Yes, just wanted to mention it.

**Comment by kraftner** [comment]
@texnixe I've just re-read your comment and this should not only work when a non-admin can create users but also when he can only edit/update them. So this case in particular:

```
'panel.user.create' => false,
'panel.user.update' => true
```

I've seen you set this to the "future" milestone but I believe this is somewhat urgent as the whole idea of setting permissions for the user edit screen is kind of broken right now.

**Comment by kraftner** [comment]
So I just added a PR that fixes this:

When `panel.user.update` was introduced in https://github.com/getkirby/panel/commit/0f2d25fd4445e72a681aeefa130dda22cb03eaed these lines should have been removed, [just like here](https://github.com/getkirby/panel/commit/0f2d25fd4445e72a681aeefa130dda22cb03eaed#diff-152477d2a9fbbfe59c8676942093cbe7L66). Removing this line is safe as someone without proper rights for `panel.user.update` would already be blocked here:

https://github.com/getkirby/panel/blob/370e9767766c2d9404bcbaf0fd1f7922d9458bd1/app/src/panel/models/user.php#L41

**Comment by lukasbestle** [comment]
Updating users without being admin now works on the develop branch.
Updating roles of other users is not possible however because we can't differentiate the permission between "update own role" and "update role of other users". And because of that, users would be able to change their own role as well. We can't allow that for non-admins as that would be a privilege escalation.
