### ISSUE TITLE
Duplicate language field in panel causes error

### ISSUE THREAD

**Issue by kraftner** [getkirby/panel#1106]
I've just noticed that https://github.com/getkirby/panel/commit/f2d8ddbc3fe48f3b69808d4ed594d47db1b97cd2#diff-83ad63e557edb68709164679e9ff94a4R330 causes the following error:

`array_key_exists(): The first argument should be either a string or an integer in file: /srv/www/site/panel/app/fields/select/select.php on line: 71`

**Comment by lukasbestle** [comment]
When exactly does this error occur? Could you please post steps to reproduce this based on the Starterkit? Thanks!

**Comment by kraftner** [comment]
Sorry, I was in a bit of a hurry on friday and at least wanted to leave it with you before running off for the weekend so I don't forget about it.

This happens when saving a user.

The problem is that you're creating a hidden input with the same name as the already existing language select. The browser now automatically turns those two post fields with the same name into an array. And that then causes the error mentioned above.

Adding this additional hidden field might also cause another issue: If somebody has a field called "language" on any blueprint that field can't be saved any more now.

I'm not sure what issue https://github.com/getkirby/panel/commit/f2d8ddbc3fe48f3b69808d4ed594d47db1b97cd2 was intended to fix, but I think it needs another approach. :)

Finally I think the code that causes the error in [validate()](https://github.com/getkirby/panel/blob/c8e376cf9517ce58a84b10fd0e560f44f33b0216/app/fields/select/select.php#L71) is probably problematic because it blindly assumes that `$this->value()` is a string while it can (as we've just noticed) just as well be an array.

**Comment by lukasbestle** [comment]
We will move this fix to 2.5.7 as we will need to find a better and more reliable fix for this.
Idea: Prefix or underscore for the special `language` field.

**Comment by lukasbestle** [comment]
See #943.

**Comment by lukasbestle** [comment]
Fixed by #1125.
