### ISSUE TITLE
Panel error if `pages:false` in the site blueprint. (v2.5.6)

### ISSUE THREAD

**Issue by julien-gargot** [getkirby/panel#1112]
```
Whoops\Exception\ErrorException thrown with message "Method Kirby\Panel\View::__toString() must not throw an exception, caught Error: Call to a member function nextPageUrl() on null"

Stacktrace:
#0 Whoops\Exception\ErrorException in /mnt/datas/Sites/rockwithrules.com/www/panel/app/layouts/app.php:0
```

**Comment by texnixe** [comment]
This another of these cases where `pages: false` in site.yml causes an error. In my opinion, the setting should be disallowed and the problem with disallowing to add additional pages solved differently. The site object must have at least one subpage, the home folder.

**Comment by Rainbowlemon** [comment]
+1, I just encountered this bug and it took me a few hours to figure out what was going on (converting a single page website into a multi-page website).

**Comment by lukasbestle** [comment]
I agree with @texnixe here. The question is what to do with the use-cases where devs want to prevent the creation of new pages. I think we should still allow `pages: false` for that but interpret it differently.

**Comment by krisak** [comment]
+ 1
Just want to say that it is extremely useful option. We use it in almost every project. I don't care how it is implemented but most of the time we can't have clients changing structure of the site in such a way.

**Comment by texnixe** [comment]
I'd prefer a different option for this feature, `pages: false` should be limited to no pages at all, maybe something like
```
pages:
  add: false
```

**Comment by julien-gargot** [comment]
@texnixe Good idea to keep the actual logic!

**Comment by ktennie** [comment]
I've got the same error. Are there any possibilities now to set the pages to false?

**Comment by texnixe** [comment]
Instead of setting `pages:false` you can set a max value to prevent adding more pages and make the existing pages undeletable.

**Comment by lukasbestle** [comment]
Discussion in the forum: https://forum.getkirby.com/t/panel-crashes-after-update-to-2-5-6/8834?u=lukasbestle
