### ISSUE TITLE
Insert-Link in texteditor for links and emails broken

### ISSUE THREAD

**Issue by pju-** [getkirby/panel#1121]
It seems that in 2.5.7 the link in the modal to confirm the insertion of links/email-links in the kirbytext editor is broken?

Also a suggestion:
It would be cool if you could undo the output of the bold and italic buttons with Cmd+Z.

**Comment by lukasbestle** [comment]
Introduced in https://github.com/getkirby/panel/commit/b5408d36c23b7c19f9534081b9dacde8862ceede. @bastianallgeier?

**Comment by lukasbestle** [comment]
Fixed by #1126.
