### ISSUE TITLE
Widgets, Hooks

### ISSUE THREAD

**Issue by meszarosrob** [getkirby/panel#113]
I love the idea for adding custom widgets to the dashboard, and it is very to easy to create a basic one.

I have a concern regarding more complex widgets, that would require custom CSS or JS. As I looked at the files I figured out that I can insert my own CSS and JS by including it in the panel/lib/assets.php. Doable. But what happens when I am going to update the panel? Of course I can make sure that I don't overwrite that file, but it would be easier to hook somehow into that functions.

I think the possibilty of hooks would open the doors for the customization of the panel.

**Comment by bastianallgeier** [comment]
Hey guys, the API is still not 100% ready, but here's a very simple demo setup for a widget: https://gist.github.com/bastianallgeier/c34a99c54fa849f3adb0 I hope it helps.

**Comment by distantnative** [comment]
Widgets and hooks have been introduced in the recent releases, namely the 2.1: http://getkirby.com/changelog/kirby-2-1-0#panel
