### ISSUE TITLE
Setting 'pages:false' in Site Blueprint causes Fatal Error

### ISSUE THREAD

**Issue by azharc** [getkirby/panel#1131]
Hello Kirby Team!

If one were to set 'pages:false' in the site.php blueprint (a silly idea, but I did it accidentally), it causes a fatal error:

`Whoops\Exception\ErrorException 
/Site/panel/app/layouts/app.php 0`

`Method Kirby\Panel\View::__toString() must not throw an exception, caught Error: Call to a member function nextPageUrl() on null`

Kirby Toolkit | v2.5.8
Kirby CMS | v2.5.8
Kirby Panel | v2.5.8

This website had only two pages, both hidden (home and error). 

Thanks for maintaining and constantly improving the best CMS out there!

**Comment by texnixe** [comment]
There was already an [issue](https://github.com/getkirby/panel/issues/1112), this will be fixed in the next release.
