### ISSUE TITLE
Link and Email Link Broken in 2.5.8

### ISSUE THREAD

**Issue by calebgrove** [getkirby/panel#1132]
I noticed today after updating to Kirby 2.5.8 that both the Link and Email features of the textarea field are broken. Everything looks fine, until you click "Insert" on the modals. Then, absolutely nothing happens. The modal isn't dismissed, and the link isn't inserted.

**Comment by texnixe** [comment]
Works for me and should have been fixed in 2.5.8: https://github.com/getkirby/panel/issues/1121

**Comment by calebgrove** [comment]
Oh, goodness, I just remembered that I had installed https://github.com/medienbaecker/kirby-enhanced-textarea which had replaced the default field, so it's a problem with that plugin, not with the core field. Terribly sorry about that!

**Comment by medienbaecker** [comment]
Updating the Enhanced Textarea to version 1.7.1 fixes this issue. But I would advise you to switch to [SimpleMDE for Kirby](https://github.com/medienbaecker/kirby-simplemde). I won't always be able to quickly fix issues of the core textarea, which the Enhanced Textarea is based on.

**Comment by calebgrove** [comment]
Thanks @medienbaecker, I've just switched to SimpleMDE. It's sweet!
