### ISSUE TITLE
Custom Page Model Methods not available in the panel

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/panel#1133]
Custom page models aren’t used in the panel and thus it’s not possible to access any custom methods defined via page models e. g. when setting up permissions.

**Comment by texnixe** [comment]
See this issue: https://github.com/getkirby/panel/issues/740

**Comment by tillprochaska** [comment]
Sorry, didn’t see this issue. Hope there will be a proper in v3!

**Comment by texnixe** [comment]
Don't know what you are trying to do, but maybe this helps: https://forum.getkirby.com/t/call-page-model-in-panel-field/7179/2

**Comment by tillprochaska** [comment]
Thanks, @texnixe, that’s might help! :)
