### ISSUE TITLE
Panel auto log-out on Heroku Deployment

### ISSUE THREAD

**Issue by maxwolfs** [getkirby/panel#1137]
Hello!

I have troubles with deploying Kirby on Heroku. Everything works well with pages and subpages except for the panel. After logging in, it automatically redirects to /panel/login. I already tried some options within the .htcaccess and also with solutions posted [here](https://github.com/getkirby-solutions/heroku). Unfortunately there are no useful server logs at all. Projects runs without any issues on plain apache/nginx default config.

Thanks in advance!

**Comment by lukasbestle** [comment]
Thanks for getting in touch. However stuff like this is difficult to debug, so it's easier to do this in [our support forum](https://forum.getkirby.com). Please post your issue over there and we will help you. Thanks in advance!
