### ISSUE TITLE
File upload fails with "a non well formed numeric value encountered" error

### ISSUE THREAD

**Issue by Sija** [getkirby/panel#1153]
Every time I try to upload certain JPG files the upload fails with `A non well formed numeric value encountered` error.

Oddly enough it works on my dev server (php 7.1), while it doesn't on the production one (php 7.2).

**Comment by lukasbestle** [comment]
That's the issue then. Kirby can't do anything about this.

**Comment by Sija** [comment]
Error message is clearly wrong, that's the issue.

**Comment by Sija** [comment]
I have to say that this issue tracker is an absolute joke.
