### ISSUE TITLE
[Feature request] Please make "popup: yes" default

### ISSUE THREAD

**Issue by NECKRHINOS** [getkirby/panel#118]
Please add a checkbox or likewise to textarea's link button property to check for "popup: yes" true or false as a default.

That would be much easier for clients / editors.

**Comment by distantnative** [comment]
Outdated with the upcoming 2.2 (currently on the develop branch).

**Comment by distantnative** [comment]
As discussed in the forum, this should rather be solved with some JS - if at all: https://forum.getkirby.com/t/open-link-in-new-tab-button-for-non-coders/3151/12
