### ISSUE TITLE
User profile picture upload doesn't work

### ISSUE THREAD

**Issue by sashtown** [getkirby/panel#13]
Neither via drag & drop nor via click to upload. 
Tested in latest stable versions of Chrome, Safari, FF and Opera.

**Comment by AldoFerrari** [comment]
I still have the same issue on Kirby 2.1.1
I run chrome 45 or explorer 11
I'm using the latest  version of WAMP with mod_revrite active

I have the avatars folder

**Comment by byybora** [comment]
I have same issue but on live server it's working.
