### ISSUE TITLE
Plugin triggers/hooks

### ISSUE THREAD

**Issue by mearno** [getkirby/panel#134]
I'm not sure there is something in place yet in the current codebase so I'm asking :-)

In many CMS systems there's a plugin hooks or triggers API which creates a great deal of power for developers.

A good example is a trigger onAfterSave:
- When you save a page in panel it will trigger plugins that are assigned to this position
- One of the plugins is a Twitter plugin that automatically tweets the posts Tweet text field to Twitter when the Send tweet field is set to true.

A good trigger system will allow for many places in the CMS to fire plugins with specific tasks adding power and flexibility.

As an example, Joomla has many trigger points throughout the CMS http://docs.joomla.org/Plugin/Events or Drupal hooks concept http://drupal.stackexchange.com/questions/26290/what-is-the-basic-concept-behind-hooks

**Comment by byybora** [comment]
+1 looking forward v2.1

**Comment by distantnative** [comment]
Hooks have been introduced in the recent 2.1 release: http://getkirby.com/changelog/kirby-2-1-0#panel

**Comment by byybora** [comment]
:+1: Great job!
