### ISSUE TITLE
Template Field Locked

### ISSUE THREAD

**Issue by petephm** [getkirby/panel#143]
I can't seem to be able to select the templates I want to use when creating a new page in the panel?

![screen shot 2014-08-21 at 3 10 27 pm](https://cloud.githubusercontent.com/assets/7984905/3992080/e67a5d28-28f1-11e4-93a0-f6fb0510ef59.png)

**Comment by rik84** [comment]
Had the same issue and I second @hyperperforator's suggestion. The lock icon isn't really self-explanatory in this context, so adding a message would definitely help.

**Comment by OscarGodson** [comment]
Took me awhile to figure this out. Looked through all my blueprints, restarted my server, and a bunch of other things before googling and finding this.

**Comment by lukasbestle** [comment]
I have created an issue at getkirby/starterkit#59.
