### ISSUE TITLE
Heroku: "save" wipes my content

### ISSUE THREAD

**Issue by zakgreene** [getkirby/panel#156]
I've just deployed my site to Heroku. Works fine locally, but every time I save any page, from any account, all of the content on the page clears. The main reason I ported the site to Kirby 2 was actually because this site had quite a few issues on Heroku using Kirby 1.

I searched and found this Gist: https://gist.github.com/bastianallgeier/3919312
but am unclear about the php/mbstring part. Where do I find that and how do I add it to Heroku's PHP install?

I'd really like to keep using Kirby but these Heroku issues are a dealbreaker. Surprised no one else has encountered this.

The site is http://riffle-kirby2.herokuapp.com
To log into the panel, I've created an account with the username 'test' and password 'test.' Feel free to try this — this isn't a production site.

**Comment by ldamon** [comment]
It looks like this buildpack is no longer being maintained.
https://github.com/winglian/heroku-buildpack-php/issues/7

Do you have any other recommendations for buildpacks? @zakgreene

**Comment by OscarGodson** [comment]
Looking for something like this too. I'd love to use Heroku but I'm not sure how to leave the content in place

**Comment by zakgreene** [comment]
It turned out that buildpack didn't actually solve the problem at all, it was just slower to reset the .txt files to the original Git committed version. Heroku doesn't allow files in the codebase to be altered dynamically that way, so the Kirby Panel really isn't really compatible with Heroku, unfortunately.
