### ISSUE TITLE
manage templates/blueprints inside the panel

### ISSUE THREAD

**Issue by dionysiusmarquis** [getkirby/panel#157]
Manage templates: 
- Creation based on other template
- An option to automatically create a corresponding blueprint.
- delete template.

Manage blueprints (maybe part of the template manage interface anyhow):
- edit variables
- add fields including type definition
- delete fields

Maybe it will just save a little time done once, but if you are creating many different templates with blueprints during a project you'll start to save a lot of time spend in your file system very quick.

**Comment by benseitz** [comment]
Would love, if such things would be released as a plugin, instead of a built-in feature.
I love the idea of a small, flexible CMS with just the things most people need and the possibility to add the special stuff, that you need, via plugins and panel widgets.

**Comment by bastianallgeier** [comment]
I really had this on my list, but the more I think about the general direction of Kirby the more I agree with @benseitz. I think an external plugin or standalone tool would be much better and help to keep Kirby simple and clean.
