### ISSUE TITLE
Structure Pop-up Box Too Small

### ISSUE THREAD

**Issue by peterph-am** [getkirby/panel#167]
I've created a page template with a structure field,

There's quite a bit of content for each structure entry which is causing the pop-up box to scale vertically outside of the browser window:

![screen shot 2014-09-04 at 3 01 30 pm](https://cloud.githubusercontent.com/assets/7984905/4145152/82362570-33f2-11e4-83a9-dd0974e5dd89.png)

I feel that the width and overall size of the structure popup should be increased to allow for such situations, and be scrollable in overflow cases.

![screen shot 2014-09-04 at 3 13 15 pm](https://cloud.githubusercontent.com/assets/7984905/4145155/8d7589e4-33f2-11e4-8a84-ec634475f520.png)

I could make the entries subpages but I'd rather not because this page is already two levels down from the site.

**Comment by tasinttttttt** [comment]
Maybe it's not the place to ask, but how did @peterph-am added the formatting options in the modal textarea? :)

**Comment by peterph-am** [comment]
@tasinttttttt I didn't add the formatting buttons, you just have to memorise and use markdown in the kirbytext fields

**Comment by wtip** [comment]
:+1: for wider popup with overflow scrolling

**Comment by bastianallgeier** [comment]
This is finally solved in 2.1
