### ISSUE TITLE
Uploading changes file names

### ISSUE THREAD

**Issue by dionysiusmarquis** [getkirby/panel#181]
When uploading files the original filenames getting converted to lower case. Sometimes its necessary to keep the names exactly like the original.

```
files:
  changenames: false
```

**Comment by benseitz** [comment]
An option to disable that filter would be nice :)

**Comment by bastianallgeier** [comment]
This has finally landed in the develop branch and will be in the next stable release. You can switch it off like this: 

```
files:
  sanitize: false
```

**Comment by benseitz** [comment]
:+1:
