### ISSUE TITLE
Delete Subpages

### ISSUE THREAD

**Issue by ghost** [getkirby/panel#185]
" The page cannot be deleted.
This page has subpages and cannot be deleted. Please delete all subpages first. "

Please activate the option to delete all subpages in "one go". It´s kind of a pain to delete
ALL subpages first. You could do a second call " Are you really really sure you want to delete all subpages too "   YES SIR ! ; )

**Comment by Andi-Lo** [comment]
Are there any news on that? @bastianallgeier 
I think this issue is really important and would solve a lot of troubles.

With the addition of the modules plugin and the revisions plugin by @jenstornell it is important that the page can delete its children?

**Comment by olach** [comment]
Has anyone managed to create a temporary core hack to enable this functionality, until it lands in Kirby 2.5?

I will soon launch a large site with a lot of editors, and without the possibility to delete pages with subpages/modules, the client will not be happy.

**Comment by bastianallgeier** [comment]
This is finally on the develop branch. Pages with subpages can be deleted, but users have to check a checkbox to confirm it, when there are any subpages, to avoid unwanted disasters.

**Comment by SirNovi** [comment]
Does this need to be enabled in the blueprint or something? I got the develop branch but pages with subpages still can't be deleted.

**Comment by texnixe** [comment]
No, you don't need to enable anything. Just make sure that your blueprint allows deleting of the page/subpages.

**Comment by SirNovi** [comment]
d'oh - I somehow thought the panel was part of the kirby core now and I only switched the core and didn't switch the panel to the develop branch. Works now. Thanks
