### ISSUE TITLE
Structure field

### ISSUE THREAD

**Issue by A-Monkey** [getkirby/panel#212]
Hi,

Any plans for fixing the structure field in panel for K2 ?
The popup window are not the best solution. I suggest doing
a drag and drop Accordion, with expand/collapse buttons  instead. In that way you can keep
all the functionality of the fields inside the structure field. For an example
buttons for textarea, drag and drop images/files from sidebar, and so on...

Best regards /

MONKEY!

**Comment by servicethinker** [comment]
Maybe something like a dynamic new-item row? I know that's hard but that would be really awesome!

More informations about this pattern: 
http://quince.infragistics.com/Patterns/New-Item%20Row.aspx 
http://www.davepaquette.com/wp-content/uploads/2014/02/image_thumb5.png
