### ISSUE TITLE
colon (:) in url causing 400 on iis servers.

### ISSUE THREAD

**Issue by tickHub** [getkirby/panel#213]
In the new panel, some urls containing a colon (e.g. /panel/views/editor/link/pages/show/hq/p:1) causing a 400 bad request on iis servers.

http://stackoverflow.com/questions/667429/using-a-colon-in-a-url-with-asp-net-iis

Maybe safer to replace the colon with something else?

**Comment by bastianallgeier** [comment]
The new version of the panel will finally no longer use those kind of URLs.
