### ISSUE TITLE
Untranslated error message

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby/panel#234]
When trying to create a page duplicate, this untranslated error message appears

![Error message](http://f.cl.ly/items/1q0o3x3j2h0h3A2r420R/Image%202014-10-09%20at%203.39.11%20PM.png)

**Comment by distantnative** [comment]
Does this one still appear in the Kirby 2.1 beta?

**Comment by JimmyRittenborg** [comment]
@distantnative yes it does :grin:

**Comment by distantnative** [comment]
Fixed in the upcoming  2.2. (currently on the develop branch).
