### ISSUE TITLE
Search by Page Title instead of uid ?

### ISSUE THREAD

**Issue by iandoe** [getkirby/panel#242]
Hey,

Wouldn't it be better for the page search function panel to search pages by Title instead of their uid ?

This could prove less geeky and more useful to actual clients, as i for example often let the home page uid be `home` while in French a client looking for the homepage would type `Acc` to look for `Accueil`.

What do you think ? i can work on the feature

**Comment by distantnative** [comment]
Will be possible in the upcoming 2.2 (currently as beta on the `develop` branch).
