### ISSUE TITLE
Panel: Problem with Site-Owner under Linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by ghost** [getkirby/panel#244]
Adding sites about panel, I always get a "Daemon" as Owner. And when I want to change there anything about my ftp, I regularly must change the ownership about root getting the real owner (and that's me in my view). Otherwise I can't do or change nothing with these folders respectively in these folders. 

Bug, "normal", or my personal Ubuntu-problem? Must say, I only trying Kirby on my local installation till now, not yet on my real server.

**Comment by bastianallgeier** [comment]
I completely missed this issue to be honest and it's a bit embarrassing to find this after months. Do you still need help with this?
