### ISSUE TITLE
touch(): Utime failed: Permission denied

### ISSUE THREAD

**Issue by nockedout** [getkirby/panel#249]
I keep getting this error in the panel, although saving content (e.g. site variables) within the panel actually works.

Here is my workflow on my Mac (running OSX 10.9.4, where my sites are in "~/Sites", Apache is running as User/Group "_www" and DocumentRoot is "/Users/nockedout/Sites"):

1) cd ~/Sites; mkdir kirbytest
2) sudo chmod -R +a '_www allow read,write,delete,add_file,add_subdirectory,file_inherit,directory_inherit' kirbytest
3) cd kirbytest; git clone --recursive https://github.com/getkirby/starterkit.git .
4) Open up the site in the browser - everything works as expected
5) Open up /panel - create user - login - works as expected
6) Edit a site variable - getting touch(): Utime failed: Permission denied, even though the changes are saved

What's wrong with this workflow? I did not get these permission errors with previous versions of Kirby.

**Comment by dweidner** [comment]
I had the same issue, which was caused by me accidentally changing the file permissions of the file `site/accounts/.logins`. The panel requires write access not only to the directory, but for the file as well.

**Comment by frankrausch** [comment]
I saw the same problem with the latest version 2.5.7 of Kirby. Changing permissions on `site/accounts/.logins` solved the problem for me, too. 

The error message in the debugger had nothing to do with the actual problem unfortunately.
Maybe the login page could check for permissions of the `.logins` file, show a descriptive error message and suggest this solution?
