### ISSUE TITLE
'Site Variables' widget display

### ISSUE THREAD

**Issue by skifreak** [getkirby/panel#267]
Not that the site variables need to be edited often, but it would be nice if the widget displayed the Label for the variable instead of the variable itself:

![image](http://cl.ly/image/222O3g1X2s1C/Image%202014-10-26%20at%204.51.43%20PM.png)
![image](http://cl.ly/image/392x3d0n3u08/Image%202014-10-26%20at%204.51.49%20PM.png)
-->
![image](http://cl.ly/image/073L1U3H2201/Image%202014-10-26%20at%204.54.47%20PM.png)

**Comment by bastianallgeier** [comment]
I finally fixed this by restructuring the site options and moving them to the menu, while removing the widget. I agree that it didn't make enough sense to have a right to stay in the dashboard.
