### ISSUE TITLE
Files for Site

### ISSUE THREAD

**Issue by xypaul** [getkirby/panel#269]
Adding the option to configure ```blueprints/site.php``` was a big deal for me. Every website has lots of global settings that people should be able to change. However I am quickly running into problems. Files are essential part of the configuration settings (*...think logo for website, body background picture, many more examples...*). I would mean a lot to me if files could be uploaded here.
![screenshot 2014-10-28 20 20 00](https://cloud.githubusercontent.com/assets/2549828/4820653/7a0904a0-5f1a-11e4-9c55-1969dd83c5a3.png)

Thanks Bastian :)
Kirby is awesome

**Comment by bastianallgeier** [comment]
This is finally available on the develop branch and will be in the next stable release.

**Comment by xypaul** [comment]
Thanks @bastianallgeier :)
