### ISSUE TITLE
Structure field doesn't show stored values in Panel after page has been saved

### ISSUE THREAD

**Issue by felixbridell** [getkirby/panel#275]
I'm using the Structure field in a blueprint (which by the way is a killer feature!). Everything works good the first time I add entries, but when I save the page the added entries disappear form the template. The values is getting saved to the .txt-file and show up on the front-page but in the Panel the message "No entries yet" show up and it looks like I never added any data.

I'm using Kirby 2.0.2 on Mac os X 10.10 MAMP 3.0.7.2.
I hade the same problem before i upgraded to Kirby 2.0.2 (was running Kirby 2.0) and was hoping that the upgrade should fix the problem...

**Comment by t128** [comment]
> So underscore and camelCase should be prefered.

That's what i'm doing. I defined a *structure* field in my blueprint:
```yml
[...]
label: My struct
type: structure
fields:
  myStructField:
    label: My struct field
[...]
```

But it gets converted to lower case in php:
```php
<?php
$myStruct = yaml($page->myStruct());
echo $myStruct['mystructfield'];
```

> I solved it this way to avoid issues between different cases in blueprints and text files, which would lead to errors in forms.
(https://github.com/getkirby/panel/issues/330#issuecomment-70100132)

That's pretty much the opposite here. As you can use camelCase in blueprints, but then have to switch to lowercase in your code.

I also could workaround this by using underscore notation for all structure fields, but this is 1. ugly and 2. it wouldn't be consistent at all (use underscore for all structure fields, but keep camelCase for all other fields).
