### ISSUE TITLE
Changing titles changes the pages' uid

### ISSUE THREAD

**Issue by meretv** [getkirby/panel#291]
The problem does not seem to happen only with alphabetically sorted pages as described in #173. Regularly (drag and drop) sorted pages also get renamed whenever a title changes.

This creates huge problems because if you rename the homepage in any of the site languages it gets moved to `1-<new-title>`. This in turn causes the internal `homePage` function to return null instead of the home page, which results in a fatal error and a black error page instead of any content.

It makes the panel kind of unusable as it keeps changing URLs/uids and even breaking the entire site while translating or editing content.

**Comment by bastianallgeier** [comment]
This is fixed in the latest version on the develop branch.
