### ISSUE TITLE
User role to access single profile page

### ISSUE THREAD

**Issue by jkelleher** [getkirby/panel#307]
Looking to employ Kirby to host a collection of project pages for my students, each with a collection of fields (e.g. project name, github url etc.). I'd like them to:
* team user 'account' to enable them to enter project details
* access only to their project details form in panel - no other permissions
* otherwise site has full public access to all

Or is it just a better option for me to have them make a simple txt file with separate fields and have a Kirby template pull from the files to produce the pages?
Thanks,
John

**Comment by bastianallgeier** [comment]
We are currently working on user roles: #60 So I'm going to close this for now and keep the first ticket updated on changes.
