### ISSUE TITLE
On trying to create new tags in Safari on Mac and iPad Fails with Error

### ISSUE THREAD

**Issue by shoesforindustry** [getkirby/panel#308]
Seems to work OK in Firefox or if you are using previously defined tags?

On mac
![screen shot 2014-12-13 at 17 38 19](https://cloud.githubusercontent.com/assets/2102743/5424613/7c8750c6-82ef-11e4-8f95-feb732732797.png)

On iPad
![img_0526](https://cloud.githubusercontent.com/assets/2102743/5424621/dd38fed8-82ef-11e4-8af3-1b98256c518e.PNG)

Any ideas?

**Comment by servicethinker** [comment]
Have you also tried with Kirby v. 2.0.6?

**Comment by distantnative** [comment]
Or even the 2.1 beta? Tags work perfectly for me on Mac OS 10.10.3 with Safari 8.0.5 (10600.5.17). Don't have an iPad to test tho - but you can send me one, if you want ;)

**Comment by bastianallgeier** [comment]
This should be fixed in 2.2. on the Decruft branch.
