### ISSUE TITLE
Setting site title empty in panel breaks site

### ISSUE THREAD

**Issue by Muximize** [getkirby/panel#309]
If you ignore the little green star in the dashboard and set an empty title anyway, the site breaks and after logging out you can't log back in. /panel/login says:
```
Catchable fatal error:  Method Field::__toString() must return a string value in (snip)/panel/app/layouts/login.php on line 7
```
Only way to fix is manualy setting a title in site.txt

**Comment by puckey** [comment]
(Just came across this one too while doing a test migration...)

**Comment by bastianallgeier** [comment]
This is finally fixed on the develop branch!! Sorry that it took so long.
