### ISSUE TITLE
My panel doesn't show blogarticle #115 in the "Visible pages"-list

### ISSUE THREAD

**Issue by DerZyklop** [getkirby/panel#310]
My panel doesn't show a particular site (#115) in my list. I just published article nr. 116 (per command line), now my "Visible pages"-list looks like this: 
![screen shot 2014-12-16 at 20 58 50](https://cloud.githubusercontent.com/assets/912344/5461084/730f627e-8568-11e4-9ba1-ac921ab3e67f.png)

When i move 116 to "Invisible pages", then the list just starts at 114.

When i rename the folder `115-bannerwerbung/` to `bannerwerbung/` via command line it doesn't show up in the "Invisible pages" list either.

The permissions on `115-bannerwerbung/` and my new article `116-mein-neues-arbeits-spielzeug-blink-1` are the same.

Despite everything, [my blog](http://der-zyklop.de/) and [the article](http://der-zyklop.de/blog/bannerwerbung) is fine and in the correct order. 

If you want to have a look at it: The [whole website](https://github.com/DerZyklop/der-zyklop.de) and its [content](https://github.com/DerZyklop/der-zyklop.de/blob/master/content/01-blog/115-bannerwerbung/blogarticle.txt) is on github.

**Comment by bastianallgeier** [comment]
I totally missed this. Is it still an issue?

**Comment by DerZyklop** [comment]
No. Since that issue i updated kirby one or two times. Maybe that fixed it somehow. Anyways... you can close it.

**Comment by bastianallgeier** [comment]
:)
