### ISSUE TITLE
Always lowercase chars while typing a tag

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#313]
Well I've recognized this issue while using the panel. I think this is an issue because I always don't know what I'm getting if lowercasing all inputs is off.

**Comment by jonabaptistella** [comment]
The lower case attr for the blueprint do now work. I can still type capital letters.

**Comment by bastianallgeier** [comment]
It took forever. But I finally fixed this. It will be in the next stable release and is now available in the develop branch.
