### ISSUE TITLE
info-Fields don’t work with smartypants

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#317]
The `info` field type seems to have a problem with smartypants activated. You can see the error by doing the following:

1. get the starter kit
2. activate smartypants in `config.php` 
3. change the `default` blueprint to

        <?php if(!defined('KIRBY')) exit ?>
        
        title: Page
        pages: true
        files: true
        fields:
          title:
            label: Title
            type:  text
          info:
            label: Info
            type: info
            text: Das ist ein Test
          text:
            label: Text
            type:  textarea

4. go to the panel and try to chang the page “About”

If you deactivate smartypants the blueprint will work.

**Comment by bastianallgeier** [comment]
Done! :)

**Comment by tweh** [comment]
Thank you!
