### ISSUE TITLE
Add some “public“ css classes to style the view of structured fields

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#319]
It would be nice to have some kind of `public` CSS classes that allow a better styling of the view of structured fields in the panel. For example I generate this output for events in a calendar

![output](https://cloud.githubusercontent.com/assets/3011538/5598051/21f73ec6-92af-11e4-85dd-44078b1ee523.png)

with

      calendar:
        label: Einträge
        type: structure
        entry: >
          <strong>{{title}}</strong><br>
          <span style="color:#8dae28;display:inline-block;margin-right:1em;width:95px">Beschreibung</span> {{description}}<br>
          <span style="color:#8dae28;display:inline-block;margin-right:1em;width:95px">Datum/Zeit</span> {{date}}, {{starttime}}–{{endtime}}<br>
          <span style="color:#8dae28;display:inline-block;margin-right:1em;width:95px">Ort</span> {{place}}
        fields:
          title:
            label: Titel
            type: text

but it would be great to have a class like `label` in the panel’s CSS to achieve this output,

**Comment by bastianallgeier** [comment]
Just added an option to the develop branch to include your own panel stylesheet: 

```php
c::set('panel.stylesheet', 'assets/css/custompanel.css');
```
