### ISSUE TITLE
Other (second) position for “Save” button

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#321]
For pages with long content it’s not really comfortable that the button to save the changes is a the bottom. Maybe you can add a second button at the top of the page …

**Comment by texnixe** [comment]
Hope this idea finds its way into the next release ...:)

**Comment by tillpro** [comment]
+1

**Comment by eytanbiala** [comment]
+1

**Comment by shoesforindustry** [comment]
+1 
a. Solution maybe to put it in the top toolbar - make that toolbar fixed, so it is always visible ;-)
b. Also make the side bar fixed if on a wide enough screen - so it is always there?

**Comment by AugustMiller** [comment]
You can always `Control+S` on a page to save it!

The top of the left-hand panel would be an ideal spot for this, given it contains other page-management features—with more being added in 2.1.

**Comment by eytanbiala** [comment]
See also #462 .

**Comment by bastianallgeier** [comment]
This is now fixed on the decruft branch and will be in the next release.
