### ISSUE TITLE
Custom directory structure breaks Panel

### ISSUE THREAD

**Issue by dictions** [getkirby/panel#325]
I noticed this issue today when I was installing panel on my project. I separated out kirby from the content by putting it in a server folder. You outline a few gotchas on the site, but the avatars directory specifically is not set within `$kirby->roots`.  I still get the "/assets/avatars is not writable" error on panel install.

```
|--public
   |--index.php
|--server
   |--site
   |--kirby
```

My proposed solution, and the one that worked, is this:

```
// fix avatar directory 
if(!isset($kirby->roots->avatars)) {
  $kirby->roots->avatars = $index . DS . 'assets' . DS . 'avatars';
}
```

**Comment by bastianallgeier** [comment]
I just fixed this in the develop branch and it will be included in the next release.
