### ISSUE TITLE
required:true does’t work like expected

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#328]
When I add a required field to my blueprint with

      test:
        label: Testfield
        type: Text
        required: true

I’d expect, that I get an error/warning when trying to save a page with en empty `test` field. But the only thing that happens is that the label gets an asterisk.

__to reproduce__

1. download the starter kit
2. add field above to the `default` blueprint.
3. edit the page `About` in the panel and leave Testfield empty
4. Try to save the page

(same with a new created page)

**Comment by bastianallgeier** [comment]
This is fixed in the develop branch and will be in the next release.
