### ISSUE TITLE
Sort select box items in dropdown menu

### ISSUE THREAD

**Issue by ian-cox** [getkirby/panel#329]
I'm using a selectbox field to allow the user to choose featured projects to be highlighted on the homepage. The selectbox shows a list of all project pages but they aren't sorted alphabetically.

Is it possible to sort the dropdown list alphabetically?

Thanks!

![sort_alpha](https://cloud.githubusercontent.com/assets/4325127/5631482/0cf3b28c-9595-11e4-9522-f3d04fc50ae8.gif)

**Comment by bastianallgeier** [comment]
I just added this to the develop branch for the next version.

**Comment by ian-cox** [comment]
Awesome, thanks!

**Comment by bastianallgeier** [comment]
A little documentation would be good here I guess :) 

just add the new sort: option to the field

```
myselect:
  label: select
  type: select
  options: children
  sort: desc
```

**Comment by ian-cox** [comment]
very cool, 

Is the development branch something I should play now or should I wait for the stable version release?

If not, what is the best way to check when certain features become available? Are you announcing versions?
