### ISSUE TITLE
Capital letters in field names

### ISSUE THREAD

**Issue by mzur** [getkirby/panel#330]
Since I can't reopen #281, I have to open a new issue.

It is currently not possible to use upper case letters in field names because all names are [converted to lower case](https://github.com/getkirby/panel/blob/4a58f71aee83da3c67e8bc43d4d0f2cdf8926b63/app/lib/form.php#L47). I know that all the default field names are lowercase but with the structure field, custom field names are possible, too. In my opinion field names should be allowed to contain upper case letters unless there is a specific reason to force lower case names.

**Comment by bastianallgeier** [comment]
Could you explain a bit more in which situation it would be useful/necessary to have upper case field names? I'm not 100% sure yet if I understand the reason for it.

**Comment by mzur** [comment]
There may be no situation requiring upper case field names. I'm just wondering why they are disallowed in the first place. Is there a specific reason for that?

**Comment by bastianallgeier** [comment]
I solved it this way to avoid issues between different cases in blueprints and text files, which would lead to errors in forms.

**Comment by mzur** [comment]
Thanks for making that clear, I can accept that. It is consistent with the case insensitive handling of content file field names, too.

But the case insensitive handling of structure field names only works one way. Take the example on the [structure field doc page](http://getkirby.com/docs/cheatsheet/panel-fields/structure) for instance. The form fields are called `street`, `zip` and `city` and the content file fields are called `Street`, `ZIP` and `City`, but the content file field names are *not* converted to lower case before matching the keys, so the example doesn't work.

I hope you could follow my explanation :-)

**Comment by bastianallgeier** [comment]
The docs are not correct here. I will fix this asap.

**Comment by distantnative** [comment]
Seems to be fixed in the current docs.
