### ISSUE TITLE
Umlauts in Panel Field Url

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/panel#333]
I want to use following valid url: ›http://de.wikisource.org/wiki/Über_das_Marionettentheater‹ in an url panel field.

![Error Message](https://cloud.githubusercontent.com/assets/1524319/5745374/8a2fb3ce-9c28-11e4-9b23-4dd2408172e3.png)

**Comment by bastianallgeier** [comment]
I just committed a fix for this to the develop branch and it will be included in the next version.
