### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by zzzzBov** [getkirby/panel#335]
I've built a custom [CodeMirror][1] field, and I'm just curious whether you'd like custom fields submitted to the panel repo as pull requests, or if I should just make a separate repo for the custom field.

[1]: http://codemirror.net/

**Comment by bastianallgeier** [comment]
I think this would be a perfect addition for http://getkirby-plugins.com/
I don't want to add it to the core, because the source code for CodeMirror is rather big and not everyone will need it, but it's defintiely a nice addition which will be liked be many.

**Comment by zzzzBov** [comment]
Good to know. Thanks!
