### ISSUE TITLE
Sort subpages by field

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#337]
Would be great to automatically sort subpages (maybe even assign the number to them) by a field of that subpage. I'm thinking of blogs with just so many articles as subpages. Moving them over to visible and so on just doesn't feel right. Would be great to get them sorted by a date field automatically.

**Comment by distantnative** [comment]
Even an option to display the date in front of the page title in the subpages list would help enormously

**Comment by ausminternet** [comment]
You might have a look here: http://getkirby.com/docs/panel/blueprints/page-settings#numbering-of-subpages -> "Date-based numbering"

**Comment by distantnative** [comment]
How did I miss that? Thanks - that's pretty much exactly what I want :D
