### ISSUE TITLE
Select field doesn't seems to use Panel Model for dynamic options

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#338]
I want to use the `option: images` to let the user choose a cover image from a set of images in the subpage called `galerie`. To get this to work I thought it would be easy enough to override the images() function of this specific template via the new Page Model feature.

So I've wrote this function into my Page Model:

    public function images() {
        return $this->children()->find('galerie')->images();
    }

.. and I've configured my blueprint with a new field:

    coverimage:
      label: Coverbild-Auswahl
      type: select
      options: images

Now I have 4 images in my gallery and `dump($page->images()->count())` returns exactly 4 images - as I've expected. Excellent!

But the field is still empty: 
![bildschirmfoto 2015-01-17 um 23 53 53](https://cloud.githubusercontent.com/assets/980778/5790666/2423a666-9ea4-11e4-8cbd-b895d33a4f73.png)

I think the field doesn't uses the Panel Model to get the right values...

**Comment by lukasbestle** [comment]
I guess the reason for this is that the Panel doesn't load Page Models in the current version.

**Comment by bastianallgeier** [comment]
I'm afraid I have to close this. Including Page models in the panel would lead to such massive possible side effects that it would be close to impossible to keep the panel stable.
