### ISSUE TITLE
Filename's tabindex set to 1 or 'auto'?

### ISSUE THREAD

**Issue by adamcbrewer** [getkirby/panel#341]
Bulk renaming file names could be a lot faster without having to navigate to using the mouse. I was wondering if it might help making sure the inputs on the right are immediately focusable?

**Comment by bastianallgeier** [comment]
I had the autofocus on the filename field and removed it because keyboard navigation with arrow keys is of course not possible when the field is focused. So it felt worse than not focusing on the field.
