### ISSUE TITLE
'save' button in structure is misleading

### ISSUE THREAD

**Issue by puckey** [getkirby/panel#345]
Clicking the 'save' button when editing/adding a structure makes me think I have saved the page, but actually nothing is really saved. You have to press save again to save the page..

Perhaps rename it to 'ok'?

**Comment by ralfgoeke** [comment]
+1 this is a pretty critical UX issue I think.

**Comment by bastianallgeier** [comment]
You are right! I just changed this in the German and English translations on the develop branch.

**Comment by puckey** [comment]
Thanks!

**Comment by ralfgoeke** [comment]
Awesome, thx! :)
