### ISSUE TITLE
Shortcodes interfere with panel extensions

### ISSUE THREAD

**Issue by JonasDoebertin** [getkirby/panel#347]
I'm working on a custom panel field right now. Everything's going smooth, except one small but important detail:

The panel field is basically a very limited WYSIWYG editor field (similar to the medium editor) that doesn't use an <input> or <textarea> element as the input element but rather an editable div(`<div contenteditable="true></div>`). Even tough this works quite good, there is a problem with the shortcuts (like `g` to open search and `f` to upload a file) being fired while editing it and typing the related keys.

It seems like these events are omitted when the user has the focus on a form element (input, textarea, select, etc) but not when an editable element is focused.

The problem here seems to be the *jQuery Hotkeys Plugin* that's included in the panel.js resource. It checks for focused input elements but not for focused editable elements.

Is there any known way to overcome this?

**Comment by lukasbestle** [comment]
It seems like this behavior is now fixed in the [latest version](https://github.com/tzuryby/jquery.hotkeys/blob/master/jquery.hotkeys.js#L61). Updating the plugin might solve this issue.

**Comment by JonasDoebertin** [comment]
I found this to be the only solution, too.

@bastianallgeier Could you consider including this updated version or at least a quick fix to check for `contenteditable` elements too?

**Comment by JonasDoebertin** [comment]
I just added a pull request for a fix: #353
