### ISSUE TITLE
Can't update default language after switching on multilanguage support

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#348]
I started setting up a site in German only. After a while now we decided to add English support, so I added the follwoing to the `config.php`:

```php
c::set('languages', array(
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'default' => true,
    'locale'  => 'de_DE',
    'url'     => '/',
  ),
  array(
    'code'    => 'en',
    'name'    => 'English',
    'locale'  => 'en_US',
    'url'     => '/en',
  )
));
```

On most pages it works, but on some the panel seems get confused with the naming of the default file, e.g. in one directory I have now three files:
- `news-item.txt`
- `news-item.de.txt`
- `news-item.en.txt`

With the English version everything works fine, I switch to English in the panel and everything gets saved/updated to `news-item.de.txt`. But with German, there seems to be a mix up: While both panel and the actual site seem to read from `news-item.txt` the panel creates and saves to `news-item.de.txt` - which results into me not being able to change the German content of these pages at all.

**Comment by lukasbestle** [comment]
Hm, that's a difficult problem as the Panel doesn't know about configuration changes.

A possible solution for most of the cases could be to delete the old "default" file when saving a page in the Panel.
Unfortunately, this could lead to problems when the new default language is not equal to the language that was used before.

**Comment by distantnative** [comment]
I wouldn't bother so much to have a "useless" old default file in the folder - but shouldn't the Panel and site also read from the `news-item.de.txt` for the default language (German) if it's present? At the moment it's written to the right (new) file, but read still from the old one even though a respective specific language file for German is present

**Comment by distantnative** [comment]
Also couldn't figure out why some pages just work (Kirby uses old default file for German in reading and writing, creates new one for English), but for other it creates this new German language file.

**Comment by shoesforindustry** [comment]
Hi, distantnative, we had similar problems, ours turned out to be differing rights for the files. 
Hope it helps you.

**Comment by distantnative** [comment]
Thanks for that - I already updated the file rights, so it doesn't solve the problem once it's there. Though it might have triggered it in the first place

**Comment by bastianallgeier** [comment]
This is actually a bigger issue with the architecture of content files in Kirby. It's just not made in the way that you can easily switch from single language sites to multi language sites. The more I think about it the more I guess there should be some kind of clean-up procedure for this. Not entirely sure how to implement it yet and where to put it. Suggestions are welcome!

**Comment by distantnative** [comment]
Besides the clean-up procedure, Kirby would just to stick to something like this: If multiple languages are activated, always only go for the name.LANG.txt files. And only if none exists for your language, you either create a new one from scratch, or - if it is the default language - you look for the "normal" name.txt and immediately rename it.

Cause I think the problem atm is, that Kirby at some point creates a new file, but on other actions still falls back to the old file. I'm wondering if this could be used without any clean-up procedure by being just stricter or more consistent

**Comment by distantnative** [comment]
Since this has been addressed in the documentation now (https://github.com/getkirby/getkirby.com/commit/fcc0986aa7118fd8fa3a9262a895ad12cac84832), I will close this issue. We will have to see if Kirby could support the necessary actions to switch between single and multilang at some point in the future.
