### ISSUE TITLE
Ability to manage site-wide files

### ISSUE THREAD

**Issue by sashtown** [getkirby/panel#35]
Would be great to have the possibility to view/edit/manage sitewide accessible files (stored in the root of the content folder) from the dashboard page in order to the new, sexy site blueprint.

Resulting file urls like:

```
http://some-project.com/content/faq.pdf
```

could be automatically redirected to something neat like:

```
http://some-project.com/faq.pdf
```

**Comment by bastianallgeier** [comment]
It took forever, but it's finally in the develop branch and will be in the next stable release.

**Comment by jaydenseric** [comment]
Woohoo! Thanks for making this happen :)
