### ISSUE TITLE
Files: Add default values of file meta fields at upload

### ISSUE THREAD

**Issue by A-Monkey** [getkirby/panel#350]
I upload a Image and expect that the img will get the class of "asp", but no nothing happens..
I have to push the "save" button to get it to get it or do I NOT get it ?

Another thing is the white empty row in the select box, although I have set it in "required" mode.

```
dimension:
	label: Dimension
	type: select
	width: 1/2
	required: true
	default: asp
	options:
		aut: Auto
		asp: Aspect
		ful: Full

$dimension = $image->dimension();
<img class="<?php echo $dimension ?>" 
```

![dim](https://cloud.githubusercontent.com/assets/6350636/6048836/980ae720-acb3-11e4-9f9a-925d097a66a8.png)

**Comment by bastianallgeier** [comment]
This is finally being fixed in 2.2. Already available on the Decruft Branch
