### ISSUE TITLE
Image previews in panel are nonexistence...

### ISSUE THREAD

**Issue by A-Monkey** [getkirby/panel#351]
Great... doing a photographers site and this eyeballing me right in the face..
Is there a LIMIT ? and WHY ? and HOW ?

![thumb](https://cloud.githubusercontent.com/assets/6350636/6051279/08fdcf66-acc7-11e4-8de2-42cd17d99f06.png)

**Comment by iksi** [comment]
Probably PHP doesn’t have enough memory available to process the image due to its settings, file size (3.5 mb) and image dimensions.

**Comment by A-Monkey** [comment]
"   There is a image size restriction at 2000px for either dimension in the Kirby source code.
n /panel/app/views/files/show.php – line 23 –, 
in /panel/app/views/files/index.php – line 32:
$f->width() < 2500 and $f->height() < 2500

"

**Comment by A-Monkey** [comment]
Just change the dimension to support retina screens or higher..

**Comment by A-Monkey** [comment]
Why is there a image size restriction ?

**Comment by JimmyRittenborg** [comment]
it is better, than burning out the server i guess..

**Comment by JimmyRittenborg** [comment]
No frontend needs an image of that size anyway.

**Comment by A-Monkey** [comment]
well if you want to go fullscreen (2880 x 1800) on a retina screen and the limit is set to 2000x2000.....

**Comment by A-Monkey** [comment]
i guess it should be a limit on the **file** size, not the **image** size..

**Comment by JimmyRittenborg** [comment]
What about fullscreen on the new 4K iMac then 😋 it might still be a bad default. 

You're right - but that might go in relation to the image size, and i'm afraid that the limit is in place to prevent memmory issues when scaling the image.

I don't know if It's relates to imagemagick or GD limitations, otherwise it could make sense to be able to opt-out from it through the config :)

**Comment by iksi** [comment]
Related: https://github.com/getkirby/panel/issues/254 an as mentioned there the `2000` limit is a temporary fix.

**Comment by Bristoled** [comment]
Noticed two issues:
1) Sometimes Panel do not allows upload large image.
2) If Panel allows upload large image, preview was not showing inside Panel.

And yes, there is situations where some people need extra large images to use. For, example, offline content for big screens.

**Comment by bastianallgeier** [comment]
Ok, guys! There is finally a useful fix for this on the develop branch. The limit for GD lib is now 2048 x 2048 pixel. GD Lib simply can't handle more unless you have lots of free RAM on your server. But if you switch the thumbs driver to Imagemagick `c::set('thumbs.driver', 'im')` the limit is automatically removed.
