### ISSUE TITLE
Add ability to caption video figures via Kirbytext

### ISSUE THREAD

**Issue by jaydenseric** [getkirby/panel#356]
You should be able to caption video figures via Kirbytext just as you can images:

```
(image: image-name.jpg caption: Caption here)
(youtube: http://www.youtube.com/watch?v=lLuc6rtWkrM caption: Caption here)
```

As it is, they are both output in the HTML as `figure` elements.

Adding this functionality would also mean updating the docs: http://getkirby.com/docs/content/text#youtube-amp-vimeo-videos.

**Comment by bastianallgeier** [comment]
That's a great idea!!

**Comment by bastianallgeier** [comment]
Done! It's available now on the develop branch and will be in the next stable release.
