### ISSUE TITLE
404 after changing url in the panel and clicking "Open page"

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/panel#358]
via @dinko

When changing the url via the panel and subsequently clicking the "Open page" button, a 404 is issued.
The href of the button needs to be updated after the url change, I believe.

Moved here from: https://github.com/getkirby/kirby/issues/201

**Comment by bastianallgeier** [comment]
@dinko

**Comment by dinko** [comment]
I just ran pulled the submodules, I'm still having it :/ let me double-check to make sure I have the right version.

**Comment by dinko** [comment]
OK…no worries, it's working fine, it was a caching problem. Sorry for the false alarm!

I suppose it's a JS thing…some cache busting would be good if you don't have it planned already, especially for clients.

**Comment by bastianallgeier** [comment]
Cache busting would indeed be a good idea for the panel. I will implement that in the next version. Thanks for the suggestion.
