### ISSUE TITLE
Add «PUBLISH» in page option

### ISSUE THREAD

**Issue by Ventricule** [getkirby/panel#367]
Hello !
That's a suggestion :
Why don't add a button « Publish » or « Make Visible » juste under the « Preview » button in each page option ?
It should be great ! Because actualy, that's not so easy to explain to clients to go-back on the parent page and click on modify and use de drag'n'drop fonctionnality, just to publish a small thing like a news.
And however Kirby is beautiful !

**Comment by bastianallgeier** [comment]
Check this out: https://twitter.com/getkirby/status/570879106931396608 :) It's no in the develop branch and will be in the next stable release.

**Comment by Ventricule** [comment]
Wooo great !!
