### ISSUE TITLE
Preserving content file variables

### ISSUE THREAD

**Issue by MichaelBoselowitz** [getkirby/panel#368]
The default action upon saving a page should be to keep all existing variables in the content file. As it stands, if that variable is not explicitly called out in the blueprint it will be clobbered on save. The ideal would be if all variables in the content file are implicitly treated as a ```type: hidden``` field unless otherwise specified in the blueprint.

During development it is quite easy for the markdown files and the blueprints to be out of sync. As features are added, variables are often added/removed/renamed in the markdown files. This is not always translated back to the blueprints. This leads to a quite broken experience when we hand over the keys to the panel to our clients. I've been burnt by this on several occasions, especially on pages that aren't edited often.

A great phase one would be if there was a warning from the panel when saving, or before saving, a page with an out of sync blueprint. Perhaps even pointing out the variables that are out of sync.

I would love to assist in anyway I can to the development effort of this feature. I would just like to have some guidance. Where would an ideal implementation be added and thoughts on how it should be implemented?

**Comment by MichaelBoselowitz** [comment]
I wrote a quick and dirty python script to fix up my blueprints according to the suggestion above (if a blueprint doesn't contain a content variable, add it as a hidden field). If anybody's interested; here's the [gist](https://gist.github.com/MichaelBoselowitz/0698242b9ad1f6b1cb16).

**Comment by MichaelBoselowitz** [comment]
I just upgraded to Kirby 2.2.3 (it's looking fantastic by the way!! Loving the save notification!) and this appears to be fixed, @bastianallgeier is that true?

**Comment by distantnative** [comment]
Yes, this seems to be solved in the current release.
