### ISSUE TITLE
Panel doesn't read custom fields from site.txt

### ISSUE THREAD

**Issue by shoesforindustry** [getkirby/panel#37]
Panel doesn't read custom fields from site.txt, e.g. if I add a 'Subtitle' field. It does however save the default Title, Description and Text values ignoring 'Subtitle' - oddly it doesn't remove 'Subtile' which I think it used to do.

**Comment by malvese** [comment]
I was just about to ask this in the forum: "Is there a way to keep fields that are not defined in the blueprint?"
Could also be useful for the odd legacy product page that requires an additional field, but you don't want to add it to the blueprint just for that one item.

Possible issue: when you build or update a site and fiddle with fields, you may not want to leave crumbs behind.
It could be a blueprint option, off by default:
```
fields:
  extra: true
```

Or a special naming, like a leading underscore: _myHiddenField. So old fields could be deleted if a blueprint changes, but these extra fields would be kept.
