### ISSUE TITLE
title attribute or some form of tooltip for Page titles

### ISSUE THREAD

**Issue by dinko** [getkirby/panel#370]
Sometimes, page titles (especially for blog articles) become very long and it may be a bit difficult to distinguish pages. A title tag or some sort of tooltip might help here.

![title](https://cloud.githubusercontent.com/assets/61015/6390853/34de6c4a-bdb0-11e4-8a8e-604aad4707d8.png)

**Comment by bastianallgeier** [comment]
I just added this to the develop branch as well :)

**Comment by dinko** [comment]
:)
