### ISSUE TITLE
Feature request about modal view

### ISSUE THREAD

**Issue by byybora** [getkirby/panel#372]
![modal](https://cloud.githubusercontent.com/assets/3393422/6391012/23af8346-bdba-11e4-8c33-36a3ceee754c.png)

Structure field modal view is too narrow. It would be better if there are modal size options like `modal-lg`, `modal-md`.

**Comment by dinko** [comment]
There's a fix in https://github.com/getkirby/kirby/issues/183. I posted in the wrong repo there. ;)

**Comment by byybora** [comment]
@dinko your solution is perfect! :+1:  But i think, there is a option about modal sizes.

**Comment by dinko** [comment]
Thx! :)

What kind of option? In the config?

**Comment by byybora** [comment]
Not in global config. So just a example in blueprint or something like that:

     reviews:
		label: Reviews
		type: structure
		view: modal-lg
		fields: ....

**Comment by dinko** [comment]
Ok, I get it. That would also be quite nice. With the custom panel css you can already solve a lot for now.

**Comment by byybora** [comment]
Yes, i solved the issue with your custom panel css solution. Thx!
