### ISSUE TITLE
sort: flip not reflected in dashboard for site.php

### ISSUE THREAD

**Issue by iksi** [getkirby/panel#374]
Using the following in the `site.php` blueprint is not refelected in the dashboard box for pages.

```
pages:
  sort: flip
```

**Comment by iksi** [comment]
Could be solved by sorting the subpages in the controller and passing the blueprint: https://github.com/getkirby/panel/pull/376

Then in the dashoard view the `$subpages` variable should be used.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
