### ISSUE TITLE
Can't Edit Site Variables

### ISSUE THREAD

**Issue by syropian** [getkirby/panel#379]
Whenever I click a site variable, or click "Edit Site Variables" it takes me to a panel page with a blank text area. I'm running latest (2.0.6 at the time).

My site vars box: http://d.pr/i/18DSQ+

What clicking them or edit takes me too: http://d.pr/i/147rq+

**Comment by lukasbestle** [comment]
It looks like you haven't created a Panel blueprint for the site variables (`site.php`). It works just like any other blueprint.

@bastianallgeier: There seems to be documentation missing about this. Also, the tag-style display of the site variables on the dashboard (displaying vars even if they don't exist in the blueprint) might contribute to this problem.

**Comment by syropian** [comment]
@lukasbestle Thanks a lot! I was indeed missing that. More documentation on it would be nice :)
