### ISSUE TITLE
Title case sensitive template txt filename issue - not showing some content in Panel

### ISSUE THREAD

**Issue by Bristoled** [getkirby/panel#380]
If project.txt is renamed to Project.txt in Content folder (in my case there was different name), textarea content in Panel is not showing, therefore user can not edit content in Panel.

It happened, because I wanted to change previously choosed template to different. So I changed *.txt filename to other templates name, but first letter wrote capitalized. On my Win / Chrome everything was ok even if first letter was capitalized, but on friends Mac / Safari textarea content was not showing.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch and it will be in the next stable release.
