### ISSUE TITLE
Multiple image upload on iphone/ipad not working

### ISSUE THREAD

**Issue by seehat** [getkirby/panel#386]
The image name is always image.jpg/image.png on iphones/ipads and that's why only one file gets uploaded. 

Maybe we can do some kind of this to rename the files in case of iphone/ipad upload: http://stackoverflow.com/questions/21135037/html-upload-on-iphone-ios-filename-is-always-same-image-jpg-image-png

**Comment by JimmyRittenborg** [comment]
This relates to this one https://github.com/getkirby/kirby/issues/109

It's actually a very serious issue, if you dare think about it! :(

**Comment by bastianallgeier** [comment]
It's now fixed on the develop branch.
