### ISSUE TITLE
Ability to (re)name different types of subpages via blueprints

### ISSUE THREAD

**Issue by sashtown** [getkirby/panel#39]
Due to the natural file system of Kirby's content folder not every collection of subpages results in "real" subpages later.

Let's say we have an exemplary content structure like this:

```
content/
  blog/
    post-01
    post-02
    post-03
  home/
  testimonials/
    voice-01
    voice-02
    voice-03
  about/
````

The blogposts are ("real") subpages which have to be available via urls and should be able to be previewed while the testimonials (voices) here will be only displayed through a simple list on my-site.com/testimonials, which means that those voices don't need to be available via corresponding urls. They just contain "subcontent" for the parent page (or other pages). Furthermore you wouldn't want to preview them separately.

Therefore it would be great if we could:

1. (re)name different types of subpages
2. exclude selected types of subpages from previewing

```
title: Testimonials
  pages: 
    name: Voices
    preview: false
    sort: flip
```

The (re)naming should automatically affect several other connected Panel elements like the "add a new _____" button, search placeholders etc. as well.

**Comment by benseitz** [comment]
Any news on that cool feature?

**Comment by malvese** [comment]
Does it exclude those "subcontents" from a menu like the one in the Starterkit, which uses foreach($pages->visible() ?

**Comment by byybora** [comment]
+1 waiting for..

**Comment by distantnative** [comment]
Newer duplicate issue: #248 (so let's focus on that one since it's the more active one)
