### ISSUE TITLE
Select field multiple option feature

### ISSUE THREAD

**Issue by byybora** [getkirby/panel#396]
I'm using checkboxes and preview like that long as long:
![checkboxes](https://cloud.githubusercontent.com/assets/3393422/6657621/0a4fe58c-cb5a-11e4-81a5-c26bb6decc1c.png)

When i use select field, i'm able to choose single option like that:
![select](https://cloud.githubusercontent.com/assets/3393422/6657626/3b181388-cb5a-11e4-86f3-288ca2ba9ccc.png)

I think, select field should have `multiple` option like that:
![select_multiple](https://cloud.githubusercontent.com/assets/3393422/6657631/5178274e-cb5a-11e4-86e9-6b33781316d1.png)

**Comment by DanielRivers** [comment]
Would tags not work for you here?

**Comment by byybora** [comment]
@DanielRivers  Your idea is good and logical but i'm getting list with query from specific page children and tags field doesnt have query option feature.

**Comment by distantnative** [comment]
As long as there is not multiple option select added officially, you might wanna have a look at this field plugin: https://github.com/distantnative/multiselect

**Comment by byybora** [comment]
@distantnative You're pro! :+1:
