### ISSUE TITLE
Replacing images: Panel preview isn't updated

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#405]
After replacing an image through the panel, the preview does not get updated.

'the-sea' has been replaced by awesome meow:
![screen shot 2015-03-21 at 14 19 41](https://cloud.githubusercontent.com/assets/3788865/6765188/e696fb1e-cfd5-11e4-81e2-9401e54fefe7.png)

But preview is still stuck with 'the-sea':
![screen shot 2015-03-21 at 14 19 47](https://cloud.githubusercontent.com/assets/3788865/6765189/e8cf3a86-cfd5-11e4-81bb-884a2e51f860.png)

**Comment by distantnative** [comment]
Interestingly this isn't a problem with news images added, only with the starterkit. I assume, a file rights issue, but it persists even after setting all rights for `content` and `thumbs`

**Comment by bastianallgeier** [comment]
Weird! I never had this issue.

**Comment by bastianallgeier** [comment]
Can you reproduce this with the latest develop version?

**Comment by distantnative** [comment]
No, I can't. So it could be solved or something else just changed which I can't think of, but let's close this issue for now. And I'll reopen a new one if I come across it again (then hopefully with better context to understand the problem, if there still is any).
