### ISSUE TITLE
site.php content and panel/panel/* redirects & routing

### ISSUE THREAD

**Issue by hagatorn** [getkirby/panel#409]
Kirby CMS supports a non default file structure. http://getkirby.com/docs/advanced/customized-folder-setup

When I introduce the following content to the site.php file:

    // changing the directory
    $kirby->roots->content = $kirby->roots()->index() . DS . 'vendor/client-content';

    // changing the url
    $kirby->urls->content = $kirby->urls()->index() . '/client/mindfulness-content';

The panel redirects to panel\panel\install or panel\panel\login which does not exist because it is has an unnecessary redirect.  However This is pretty much exactly copy and pasted from the docs. 

If I try panel\install or panel\login it doesn't try and redirect but styles are not loaded.
   
    <script src="/panel/panel/assets/js/panel.js"></script>

If attempt to logon it produces a 'Invalid route' exception:

    /panel/app/panel.php:203 Stack trace: #0 /panel/index.php(47): Panel->launch() #1 {main} thrown in /panel/app/panel.php on line 203

If I leave site.php with only the following it is perfectly happy:

    <?php 
    $kirby = kirby();

I'm running the following php on apache:

    PHP 5.4.16 (cli) (built: Oct 31 2014 12:59:36) 
    Copyright (c) 1997-2013 The PHP Group
    Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

This problem has been reported for Ngnx too https://github.com/getkirby/panel/issues/287

Reasons for this folder structure:
In this case I wanted to load content from another git repo using composer. This give made my deployment process easier to manage from cli and lets the content maintainer proceed independently.

**Comment by felixdorner** [comment]
+1 for this... would make my life more easier if I could setup a custom folder structure AND could use the panel.

**Comment by bastianallgeier** [comment]
Just a repost from the other thread: 

The panel makes some issues when the base URL is not set correctly. So please try setting the index url:

```php
$kirby->urls->index = 'http://example.com';
```

**Comment by hagatorn** [comment]
thanks for the reply - this will mean I have to do something smart for each of the subdomains I use test.example.com, local.example.com.

Therefore I'm thinking of sticking with a symbolic link for now as it hasn't caused any issues for me yet.

Is is a plan to improve this in a later release or is this something to live with?

**Comment by bastianallgeier** [comment]
When you work with a simple switch or an array of allowed hosts it should be super easy to set the index URL. I will of course try to improve this even more in the next versions, but it's not as trivial as it might seem. I think I will close this for now as it's possible to set it up correctly even if a bit complicated. I hope that's ok.

**Comment by hagatorn** [comment]
Happy with that - didn't mean to infer that I though it was trivial.  Just
that I'm happy to stick with a symbolic link until such a point as the cms
supports a simpler option.

I'm not sure how I would implement your suggestion. I was thinking I might
have to have a variable declared in a config for each subdomain.

**Comment by bastianallgeier** [comment]
Something like this:

```php
<?php

$kirby = kirby();

switch(url::host()) {
  case 'example-a.com':

    $kirby->urls->index = 'http://example-a.com';

    …

    break;
  case 'example-b.com':

    $kirby->urls->index = 'http://example-b.com';

    …

    break;
}
```

**Comment by hagatorn** [comment]
Thank you this snippet is exactly what I needed - symbolic link did not work in production - rather than make it I used your fix - Thanks C
