### ISSUE TITLE
Structure and checkbox fields still editable when using translate: false

### ISSUE THREAD

**Issue by ablanglois** [getkirby/panel#410]
Not sure if this is new, but I haven’t found it mentioned anywhere: `checkbox` or `structure` type fields with the `translate: false` option can still be edited and saved for languages other than the main one, despite correctly showing up as grayed out. I haven’t seen that happen with any other field type so far, it seems to be specific to those two.

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
