### ISSUE TITLE
Lost focus on Tags field doesn't save the input

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#412]
![bildschirmfoto 2015-04-01 um 09 25 10](https://cloud.githubusercontent.com/assets/980778/6936344/316fcf52-d851-11e4-8283-e954aef8162c.png)
When I now hitting `Hinzufügen` in this structure element I always getting the most frustrating point in the Kirby Panel: it doesn't save my entry - even when I "remove" the focus on the field. 

**Improvement:** When the focus is lost on a tag field that means the tag is okay but the user simply forgot to hit `Tab` or `Enter`. Save the entry on lost focus as a tag to avoid frustrating moments.

**Comment by distantnative** [comment]
This has just been added to the develop branch and will be included in the next release.

**Comment by servicethinker** [comment]
I have to say that this solution brings up now another issue: now I can't select any suggestion via click or arrow down + enter key.

Tested in Safari 8

**Comment by distantnative** [comment]
True - we'll need to find another fix for this one.

**Comment by distantnative** [comment]
A better fix has been added to the develop branch and will be included in the 2.1 release.

**Comment by servicethinker** [comment]
Works partly perfect. What doesn't work is to choose the suggestion via click. 

The rest: 
- Choosing with arrow keys works
- Hitting "Save" works.

**Comment by distantnative** [comment]
Are you sure? I just tested it with the current develop branch version and it works for me:

![tagsclick](https://cloud.githubusercontent.com/assets/3788865/7687019/70cb91b8-fd9a-11e4-9e2e-425021d4d141.gif)


What has never really worked (at least not in the 2.0.6 either) is a nice visual way for `:hover` states – I noticed that and will look to try this soon.

**Comment by servicethinker** [comment]
Hi,

sorry for the delay. I've tried it in Safari 8.0.7 and it doesn't work. To increase the confusion: it works in Chrome browser :-)

I don't know if it's something *special* in Safari browser. Is there any other event that gets fired?

**Comment by distantnative** [comment]
Hmm, I use Safari - and as showed in the gif, it works there. Any Safari extensions installed that could interfere? I'll look what Safari version I'm using, when I'm back from Istanbul next week.
