### ISSUE TITLE
Modal dialog on setting site visibility

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#420]
I've tried out the new site visibility feature and got this:
![bildschirmfoto 2015-04-01 um 13 39 22](https://cloud.githubusercontent.com/assets/980778/6940193/9b0a63fa-d874-11e4-9073-4b6ad2bdbabb.png)

I know that you want to avoid maybe critical actions just because of the try-and-error behavior of the user but I think this modal dialog could be frustrating and annoying for many users - especially for experienced ones. It disturbs the flow of the user and brings him to a question that he will mostly answer with `yes` after he leaned what happens. 

Possible solution: Just let the Status fade from Green to black if it's got changed - like the `Save` button on every site. That leads the focus of the user to what has been changed and trigger a possible undoing action when he simply forgot what this change made.

**Comment by bastianallgeier** [comment]
There's simply the translation missing. I don't know exactly why, but I will check this out. The modal is needed, because the user should actively confirm this step. 

As a side note: you probably know that you want something to be changed here and that includes me investing time to improve stuff so it wouldn't be a bad idea to get your tone right. I find it highly unprofessional to write such an issue text.

**Comment by distantnative** [comment]
I'd agree that I liked the version before the addition of the modal yesterday better and thought it'd be sufficient. So I'd like that changed...

What I really think MUST change is your tone tho...

**Comment by bastianallgeier** [comment]
It happened too often that I accidentally clicked on the toggle and changed the visibility and if it happens to me it will most probably happen to other users as well. The sorting can be affected quite massively so I think the confirmation is really needed. I also plan to include a field in the next version which lets you publish a page as "first" "last" or any number in between to get the sorting right straight away and therefor the modal is needed as well.

**Comment by distantnative** [comment]
Might be a valid point – and with the addition of that field, I'll immediately feel much more legitimacy for that modal for myself :+1:

**Comment by servicethinker** [comment]
Sorry for the tone. You're right. It wasn't professional. (I'll change the text to force the correct way of discussion here.)

My side note: if a change is being made so quick it needs to be undone also very quickly. But with this very great and simple toggle you don't have to confirm your change or action because you also can undone it very quickly. What it really needs is a better visible feedback to show what gets changed. 

A confirmation really should be made on critical things like deleting the page. Because there's no undo for that actions. Also: a confirmation disturbs hardly the flow of the user and ties him to a question with two answers - no other action is allowed for him. 

From "About Face 4":
> Confirmations pass the buck to users. Users trust the application to do its job, and the application should both do its job and ensure that it does its job right. The proper solution is to make the action easily reversible and provide enough modeless feedback so that users are not caught off-guard.

> For confirmation dialogs to work, they must appear only when the user will almost definitely click the No or Cancel button. They should never appear when the user is likely to click the Yes or OK button. Seen from this perspective, they look rather pointless, don’t they?

My reaction was the first thought as I saw this modal panel. I thought: "Well, yes. I really want to change the status of the page and I know that this toggle does because I tried it out in the first round and learned. So why do I need to confirm that I really change the status of the page? And why does this asking me for confirmation every time?" 

That leads me to another paragraph of "About Face 4":
> Of course, if an application confidently does something that the user doesn’t like, it must be able to reverse the operation. Every aspect of the application’s action must be undoable. Instead of asking in advance with a confirmation dialog, on those rare occasions when the application’s actions were out of turn, let the user issue the Stop-and-Undo command.

> Most situations that we currently consider unprotectable by Undo actually can be pro- tected fairly well. Deleting or overwriting a file is a good example. The file can be moved to a directory where it is kept for a month or so before it is physically deleted. The Windows Recycle Bin uses this strategy, except for the part about automatically erasing files after a month: Users still have to take out the garbage.

In every book I've read about designing an interface they're always saying: try to avoid modal dialogs. So my advice is: make a good UI feedback that leads the focus of the user to what has been changed instead of presenting an annoying and flow disturbing modal dialog. Users just have to learn what the `Status`-Toggle does.

**Comment by texnixe** [comment]
@servicethinker: you might have missed the main point here for the modal: While the toggle is easily switched back, it doesn't mean that the changes are undone if the result is a different order of the pages which might throw up the complete layout.

**Comment by distantnative** [comment]
> Having said that it would be great if the toggle could be disabled via blueprint (not sure if that's already possible)

There will be a way in one of the coming releases (not ETA yet tho)

**Comment by servicethinker** [comment]
@texnixe Good point. Even if switching the toggle isn't a real undo for that I think the user wouldn't switch it so often because of simply trying out what it does. 
Also: a real undo is something that has to be solved by the system (which is nearly impossible without any history) or has to be very clear for the user by the modal dialog (if @bastianallgeier decides to keep it). 

In this case you've described it should be disabled via blueprint to avoid any throw up in the future. And that would be very cool :+1:

**Comment by bastianallgeier** [comment]
For now the text is fixed and more stuff will come in future releases.
