### ISSUE TITLE
SVGs reported with dimensions of zero

### ISSUE THREAD

**Issue by jonwhipple** [getkirby/panel#421]
SVGs now displaying in Panel in Kirby 2.1 beta, but the reported dimensions of the image always show as being a single zero in the Panel > File > Edit view, under Type / Size / Dimensions
![panel-file-no-dimensions](https://cloud.githubusercontent.com/assets/792196/6946139/20a047ea-d853-11e4-8a3f-711aed92684e.png)
the example shows a graphic that is known 28px × 24px

**Comment by malvese** [comment]
As far as I can tell, the getimagesize() function is used and it doesn't work with SVG files, at least with GD. It's just a text document, it doesn't have a "size" like raster graphics have.
The only "size" you could fetch is the "viewbox" attribute inside the SVG.

**Comment by texnixe** [comment]
You will experience the same when looking at the file size in Finder, it doesn't indicate an image size for SVGs either.

**Comment by jonwhipple** [comment]
@malvese '…fetch [is] the "viewbox" attribute…' maybe that could work. I note depending on tool exporting the SVG (if not hand-coded) the setting is expressed as an integer or a floating point and assumed to be pixels by some apps but maybe not others, so I suspect it would need extra processing.

@texnixe Finder dimensions: I had never noticed that. I tried setting width and height on the root SVG element to see if that was processed (no) and matched that with viewport and background as well (still no).

On reflection, maybe not too useful for dimensions to be displayed on SVGs? There are some cases where an SVG drawn large but inserted into a web view at a very small size can look bad so you'd want to be selective. But largely wouldn't be a problem. And you can indicate which file is for large display or small display using the filename.

Maybe instead of showing '/ x 0' (slash space ex space zero) it should show '/ – × –' (slash space en-dash space multiply space en-dash' or like Finder '/ --' (slash space hyphen hyphen or slash space en-dash en-dash) or '/ na' not available or '/ scalable'?

**Comment by malvese** [comment]
> On reflection, maybe not too useful for dimensions to be displayed on SVGs?

@jonwhipple I was about to write this. SVGs can be used at any size, so displaying one may be misleading.

Besides, ```viewbox```may start at any coordinate, not always (0,0), and the values are often floating point. I don't think it is worth the hassle.

'Scalable' is good, it is what the "S" means after all, but depending on the implementation the image may or mat not be resizable by the editor so it could be misleading too.
I think a simple dash ```image / 504b / -```is good enough, and as an added bonus doesn't require an additional translatable string.

**Comment by jonwhipple** [comment]
@malvese I think you are right. I agree 100%

**Comment by bastianallgeier** [comment]
I fixed it now by not showing any info on dimensions.
