### ISSUE TITLE
SVGs in Files view overlap information text in preview tile

### ISSUE THREAD

**Issue by jonwhipple** [getkirby/panel#422]
Apparently, if an SVG image is not square, the SVG overlaps the title and size information in a preview tile
![panel-files-layering](https://cloud.githubusercontent.com/assets/792196/6946223/aa4179ec-d853-11e4-9269-8fd50a9a60c4.png)

**Comment by malvese** [comment]
Even when the SVG is output as an image, its real size it taken from its ```viewbox```element. If the viewbox is higher than the container div, the SVG will stick out of the img's bounding-box.
A simple way to fix this is to set an explicit height to the image. A fixed height would not be flexible, but a max-height works. So, for this panel view:

```
  .file-preview img { max-height: 100% }
```

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch. Thanks for your help guys!
