### ISSUE TITLE
Custom CSS resource for panel

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#423]
Occasionally I tweak the CSS on an instance of the panel for a specific scenario. For now, I've just been adding a bit to the main CSS file - but this gets wiped whenever I update.

Is there a way to include an additional CSS from somewhere? Perhaps a setting in the config?

**Comment by distantnative** [comment]
You can simply add a custom css, by adding the following to your `site/config/config.php`

```php
c::set('panel.stylesheet', 'assets/css/custom-panel.css')
```

**Comment by SQbiz** [comment]
Awesome, thanks for the rapid reply!
I had missed the **Advanced > Options** part of the docs - I was just looking for the word 'config'.
