### ISSUE TITLE
Using ImageMagick just for panel?

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#428]
Is it possible to always use ImageMagick for the panel? I'm using full sized pictures in my project and also would like to see them in the panel. I would use ImageMagick as a thumbs driver but I need GD for my template because I use it to blur images automatically.

**Comment by lukasbestle** [comment]
Are you blurring image thumbs using the `thumb` helper or the actual images with your own code?
If using the `thumb` helper, you can pass another option called `driver` in the second argument (the options array) and set it to `gd`. This should override the global setting.

**Comment by servicethinker** [comment]
Wow. That works perfectly for me. :+1: 

Closed :-)
