### ISSUE TITLE
Prevent content loss when uploading a file

### ISSUE THREAD

**Issue by samnabi** [getkirby/panel#430]
When uploading a file in the panel, any unsaved content in the textbox is lost. 

This is a problem when authoring long stretched of text with images, as the workflow is usually something like:

1. Write a bunch of text
2. Click file upload
3. Drag in the photo
4. Drag photo into the text box
5. Oops the text is gone because it was deleted when I uploaded the photo

**Comment by distantnative** [comment]
I think the 2.1 beta introduces a stored data feature that solves this problem: https://gist.github.com/bastianallgeier/061ddd007d5985ae28ca

**Comment by samnabi** [comment]
Confirmed. The 2.1 update fixes this. Thanks!
