### ISSUE TITLE
pages:false in site blueprint and Edit button in panel

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#431]
If `pages:false` is set in the `site.php` blueprint, there is still an **Edit** button on the dashboard of the panel. Clicking it comes up with 'page not found'
Simple to remove it or more complicated to allow sorting but not creation..

**Comment by distantnative** [comment]
Should be resolved together with panel permissions after the v2.1.

**Comment by mingyeungs** [comment]
the **Edit** button is still there in the v2.1 release. Is it the intended behavior?
Meanwhile, I'm using the following lines to hide the buttons:
`div.dashboard-section:first-child span.hgroup-options{ visibility: hidden; }`

**Comment by distantnative** [comment]
Permissions haven't made it into the 2.1 release but are still coming in a next release.

**Comment by bastianallgeier** [comment]
This is fixed on the decruft branch and will finally be in the next release.
