### ISSUE TITLE
Panel field labels don't decode HTML entities

### ISSUE THREAD

**Issue by adamcbrewer** [getkirby/panel#440]
A minor issue, but useful nonetheless.

![screen shot 2015-04-26 at 14 49 59](https://cloud.githubusercontent.com/assets/423310/7337502/c92bba00-ec23-11e4-8687-6a6cafc00d28.png)

**Comment by distantnative** [comment]
I think this may be intentionally. Just use `&` by itself, it works ;)

**Comment by adamcbrewer** [comment]
Oh yeah, it definitely works by itself, but I'm just being pedantic. :)
