### ISSUE TITLE
Customising folder paths breaks Panel behaviour

### ISSUE THREAD

**Issue by huntie** [getkirby/panel#447]
Hey all,

I've had an issue with Panel not loading and presenting a blank page after configuring paths in `$kirby->roots` and `$kirby->urls` to tweak my project folder structure according to [the documentation](http://getkirby.com/docs/advanced/customized-folder-setup#changing-the-thumbs-folder).

**site.php**

```php
<?php

$kirby = kirby();

// Custom roots
$kirby->roots->avatars = $kirby->roots()->index() . DS . 'assets' . DS. 'img' . DS . 'avatars';
$kirby->roots->thumbs = $kirby->roots()->index() . DS . 'assets' . DS. 'img' . DS . 'thumbnails';

// Custom URLs
$kirby->urls->avatars = $kirby->urls()->index() . '/assets/img/avatars';
$kirby->urls->thumbs = $kirby->urls()->index() . '/assets/img/thumbnails';
```

I've tried other folder locations and isolating one set of changes at a time, but ***any*** path modification seems to break the Panel, and each time the referenced directories were present and correct.

When inspecting the blank Panel page with `site.php` active it is trying to load assets from a different URL:

`http://localhost/projects/kirby-starter/panel/panel/assets/css/panel.css` (with path changes)
`http://localhost/projects/kirby-starter/panel/assets/css/panel.css` (normal)

For some reason there is an additional `panel/` in the path. Interestingly, if I then visit `http://localhost/projects/kirby-starter/panel/panel/`, part of the Panel markup does load.

As a first-party plugin, these global configuration changes ought not to break things :\ and I would prefer not hacking to fix this, as I have Panel included as a Git submodule. Also I'd hope that subsequent uploads through the Panel will respect the updated paths.

Many thanks.

[Original Kirby forum question ↗](http://forum.getkirby.com/t/issue-customising-folder-paths-breaks-the-panel/921/4)

**Comment by distantnative** [comment]
I'm not too sure how to fix this, but I got the following:

The error can be traced back to the `kirby()->urls()->index()` function in `kirby/kirby/urls.php`:

```php
  public function index() {

    if(isset($this->index)) return $this->index;

    if(r::cli()) {
      return $this->index = '/';
    } else {
      return $this->index = url::base() . preg_replace('!\/index\.php$!i', '', server::get('SCRIPT_NAME'));
    }

  }
```

In case of your custom folder setup, `$this->index` is not set and, thus, the first if fails. Also the second one fails, so we end in the else-part.

Now I am wondering if it would be a solution to also preg_replace a potential `panel/` part or if it should rather be required to define `$kirby->urls->index` in a custom `site.php`, no matter if multi-domain or not, @bastianallgeier?

**Comment by bastianallgeier** [comment]
Right now this is only fixable if you set the $kirby->urls->index manually before defining the other urls. It's more complicated to auto-detect this than it seems, so I'm postponing this for now.

**Comment by huntie** [comment]
Thanks guys for addressing this. I've set `$kirby->urls->index` explicitly now and all is good for the time being — would be great if the base URL is automatically handled later though :)

**Comment by malvese** [comment]
Glad I found this issue, I lost a couple hours trying to figure out what was going wrong. If this can't be fixed in the next release, may I suggest adding to the docs that we have to set `$kirby->urls->index`?
In the meantime, thank you for providing this solution!

**Comment by Ventricule** [comment]
I also lost a couple hours searching what was wrong ! Definitly it will be nice to add the fix to the doc, in [custom folder documentation page](http://getkirby.com/docs/advanced/customized-folder-setup).

**Comment by dionysiusmarquis** [comment]
+1

**Comment by bnomei** [comment]
would be nice to use config and not setting it hardcoded. am i missing something?

config.localhost.php
```
c::set('url', 'http://localhost:8888');
```

i added this to my custom site.php
```
$kirby = kirby();
// $kirby->urls->index = c::get('url'); // does not work
$kirby->urls->index = 'http://localhost:8888';
$kirby->roots->content = $kirby->roots()->index() . DS . 'data'; // changing the directory
$kirby->urls->content = $kirby->urls()->index() . DS . 'data'; // changing the url
```

**Comment by JimmyRittenborg** [comment]
@bnomei how about something along the lines of
```php
$kirby = kirby();
// $kirby->urls->index = server::get('HTTP_HOST');
$kirby->urls->index = server::get('REMOTE_HOST'); // if this doesn't output protocol and port, you could try HTTP_HOST and stitched together with protocol and port 
$kirby->roots->content = $kirby->roots()->index() . DS . 'data'; // changing the directory
$kirby->urls->content = $kirby->urls()->index() . DS . 'data'; // changing the url
```

**Comment by bnomei** [comment]
when entering url:
`http://localhost:8888/panel`

REMOTE_HOST does nothing to fix it
`http://localhost:8888/panel/panel/login`

HTTP_HOST duplicates the output
`http://localhost:8888/localhost:8888/panel/login`

in both cases root does work correctly
`http://localhost:8888/`

do i need the custom site.php in both / and /panel/ ?
https://github.com/getkirby/panel/blob/master/index.php#L8

**Comment by lukasbestle** [comment]
There is now finally a fix for this, see #887. Please test if my code changes for both the Panel and Kirby (see https://github.com/getkirby/kirby/pull/477) work for you. This will then be included in the next Kirby release.

**Comment by lukasbestle** [comment]
The fix for this will be included in Kirby 2.3.1. You don't need to manually set the index URL anymore with the fix.

**Comment by erikfriberg** [comment]
Still seems like you need to define `$kirby->urls->index` manually in order to get image previews and image links to work in panel.

**Comment by lukasbestle** [comment]
Could

**Comment by erikfriberg** [comment]
This is my `site.php`
```
<?php

$kirby = kirby();

// changing the directory
$kirby->roots->content = $kirby->roots()->index() . '/content';

// changing the url
$kirby->urls->content = $kirby->urls()->index() . '/content';

//change thumbnail folder
$kirby->roots->thumbs = $kirby->roots()->index() . '/../render/assets/thumbs';
$kirby->urls->thumbs  = $kirby->urls()->index() . '/../render/assets/thumbs';

```

**Comment by lukasbestle** [comment]
You are right. I apparently only fixed parts of this issue in Kirby 2.3.1.
The new fix should work. Could you please test the version from the develop branches of the Kirby and Panel repos?

**Comment by erikfriberg** [comment]
Hi again, sorry for the late answer (vacation)!
Yes, the image previews in Panel shows the images now even without setting `$kirby->urls->index` so that’s great!
However, if I move the content folder back out (so it’s in the parent directory relative to the `site.php`) images won’t show in Panel again.

Here’s how that setup would look like:
`<?php

$kirby = kirby();

switch(url::host()) {
  case 'localhost':
    $kirby->urls->index = 'http://localhost/dltd-scenes/api';
  break;
  case 'dltd-scenes.com':
    $kirby->urls->index = 'http://dltd-scenes.com/api';
  break;
}

// changing the directory
$kirby->roots->content = $kirby->roots()->index() . '/../content';

//change thumbnail folder
$kirby->roots->thumbs = $kirby->roots()->index() . '/assets/thumbs';
$kirby->urls->thumbs  = $kirby->urls()->index() . '/assets/thumbs';

//change avatar folder
$kirby->roots->avatars  = $kirby->roots()->index() . '/assets/avatars';
$kirby->urls->avatars  = $kirby->urls()->index() . '/assets/avatars';
`
This does not work…

**Comment by erikfriberg** [comment]
Hi again!
Sorry for the delay (vacation).
Everything seems to be working as it should now! 
Awesome!

**Comment by erikfriberg** [comment]
Hi again!
Sorry for the delay (vacation). (and my two deleted posts since I clearly forgot about what was the problem in the first place :-p)
Everything seems to be working as it should now in the latest developer branches!
**Awesome!**

**Comment by lukasbestle** [comment]
Thanks for your reply. The fix is already in the latest Kirby release, Kirby 2.3.2. :)

**Comment by erikfriberg** [comment]
Tested there too now, works perfect! 👍
