### ISSUE TITLE
Unexpected behavior while sorting files

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#448]
When I click and drag a file in a large set of files, there is some strange scrolling behaviour:

![scroll](http://cl.ly/image/1i2B3d2D3D08/Screen%20Recording%202015-04-30%20at%2012.57%20PM.gif)

This seems to only happen when it is in the third row or below, and isn't happening on previous versions

**Comment by distantnative** [comment]
Can confirm this: from the third row on, dragging a file results in an immediate scrolling down until you drop the file again.

**Comment by distantnative** [comment]
Found the bug, should be added to the develop branch soon and included in the next release.

**Comment by SQbiz** [comment]
It looks like something else is happening now - 
Also, not sure why cloudapp is glitchy, but you get the picture

![drag](http://cl.ly/image/1q162U0b323b/Screen%20Recording%202015-06-27%20at%2011.44%20AM.gif)
