### ISSUE TITLE
Time Field Fails When Using `default: now`

### ISSUE THREAD

**Issue by luxlogica** [getkirby/panel#449]
Although there is no official documentation for this feature in the online manual, it has been mentioned in the Kirby Forum that a 'time' field has a `default: now` option. Supposedly, this option should function similarly to the `default: today` option for date fields. I should be able to use, therefore, the following description for a time field in my blueprint:

``` 
time:
    label: Time
    type: time
    width: 1/2
    interval: 30
    default: now
```

Two issues seem to crop up with the `default: now` option:

  1. When you **first** access the page in the panel, the field is empty - i.e., the current time is actually not displayed in the panel at all. Only after you do your first **save** then the current time is displayed.

  2. The selected time is actually not saved. It seems that in order for the field to function normally, we must remove the 'default' option from the blueprint.

**Comment by distantnative** [comment]
A fix has just been added to the develop branch and will be included in the next release.
