### ISSUE TITLE
Allow publishing and hiding pages directly from the page settings

### ISSUE THREAD

**Issue by diondiondion** [getkirby/panel#45]
Kirby's new subpages manager is great, but at the moment it's the *only* way to make a newly created page visible (i.e. "publish it"), and that's not really easy to figure out:
It requires going back to the parent page, then clicking the "manage" link and finally dragging the new page into its new place. While it's the same amount of clicks as in the old panel, it feels like more steps are involved since the subpage manager is on its own page now.

I think publishing pages would be much easier to understand if there was a link in the page settings to make the current page visible (or hide it), without leaving the page. Since making a page visible requires setting its index, by default the page should just be given the lowest still-available index number.

**Comment by skifreak** [comment]
I'd like to add to this, as a related or sub-issue,
it would be nice to have the option to have newly created subpages be visible by default. In some cases, no real proofing or editing is needed and the extra step to make the page visible seems unnecessary.w

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by bastianallgeier** [comment]
This has finally landed in the develop branch and will be in the next stable release.

**Comment by diondiondion** [comment]
Awesome, thanks! :)
