### ISSUE TITLE
Wrong encoding in ui-draggable elements

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#450]
Accents are garbled when pages with accents in their title are dragged. It looks like a wrong encoding is used in the ```data-helper``` and ```data-text``` attributes.

![dragaccents](https://cloud.githubusercontent.com/assets/193492/7442461/cb50a0b8-f112-11e4-9391-1e753310777d.gif)

The Kirbtext tag still works, the URL is correct, but the link text contains wrong characters that are visible by the visitors, so they have to be corrected manually after the Kirbytext is placed in the content field.

**Comment by distantnative** [comment]
Hmm, could you provide some info on OS, Browser or so? Just tried to reproduce this, but it works for me:

![screen shot 2015-05-04 at 16 46 02](https://cloud.githubusercontent.com/assets/3788865/7455503/2fc5bb30-f27d-11e4-83cb-1ca434f23780.png)

**Comment by malvese** [comment]
I tested with Chrome and Safari, and run Kirby using OS X Yosemite's PHP internal server.

**Comment by bastianallgeier** [comment]
That's super weird. I just tried with a couple special chars without problems. Not sure how to reproduce this.

**Comment by malvese** [comment]
I'm sorry, the site I tested this on still runs 2.0.6. I didn't pay attention to the version when I noticed this.
I updated it to the develop branch and accents are fine now. Sorry again.

**Comment by bastianallgeier** [comment]
Don't worry Philippe! I'm just glad it works now :)
