### ISSUE TITLE
Structure field fails for file metadata 

### ISSUE THREAD

**Issue by t081** [getkirby/panel#461]
Kirby Version 2.06
panel/app/controllers/views/editor.php line 59
change from
    foreach($blueprint->fields() as $f) {
to
    foreach($blueprint->files()->fields() as $f) {
fixes issue, but brakes structure fields on pages :-(

**Comment by distantnative** [comment]
There is currently a pull request open for the 2.1 beta that fixes this problem - as you figured out yourself, it needs a little more to decide what blueprint fields collection to choose based on the context (page or file): https://github.com/getkirby/panel/pull/455/files
