### ISSUE TITLE
Hot keys

### ISSUE THREAD

**Issue by mrpuzzler** [getkirby/panel#462]
Will be great to have hot key to save changes on panel. Sometimes I forget to scrolldown and hit "save". Simpler and faster just ctrl+s.

**Comment by eytanbiala** [comment]
:+1:

**Comment by mrpuzzler** [comment]
https://github.com/jeresig/jquery.hotkeys

**Comment by mrpuzzler** [comment]
lol, it has panel\assets\js\vendors\jquery.hotkeys.js already. Why it was not used?

**Comment by eytanbiala** [comment]
I think this lib is more up to date and better maintained - https://github.com/PolicyStat/combokeys

**Comment by eytanbiala** [comment]
@distantnative @bastianallgeier  Is there anything I can do to help make this happen?

**Comment by Thomas-Lebeau** [comment]
:+1:  I always it cmd+s by reflex and been presented the browser save page.
It would be very useful it it was caught by kirby to trigger the save. And it would make perfect sense.

**Comment by bastianallgeier** [comment]
The new release is going to have CMD+S for saving as well as CMD+Enter in fields. You can already check it out on the decruft branch.
