### ISSUE TITLE
panel UI themes?

### ISSUE THREAD

**Issue by rosivanov** [getkirby/panel#467]
Hi guys, i was trying to google the ui themes for kirby panel and nothing i found. Does panel themes exist at all? 
pls advice or drop a link, thanks

**Comment by distantnative** [comment]
There are no themes for the panel. However, since version 2.0.6 you can adapt the style by adding a custom stylesheet with the following in your `config.php`:

```
c::set('panel.stylesheet', 'assets/css/custom-panel.css');
```

Read more: http://getkirby.com/blog/kirby-2-0-6

**Comment by rosivanov** [comment]
hi Nico, thank you for prompt reply
i found only plain css files in panel assets. but i think this css likely have been written with help of sass or less or stylus.
If its true can i find source csspreprocessor files?

**Comment by texnixe** [comment]
You can find the source files in `/panel/assets/scss`

**Comment by rosivanov** [comment]
sorry but i cant find scss folder, i remmaged through all repos. can you pls give a link for repo with scss?

**Comment by texnixe** [comment]
ah, sorry, it's only in the 2.1 beta, i.e. the development branch: https://github.com/getkirby/panel/tree/develop

**Comment by rosivanov** [comment]
thank you!
