### ISSUE TITLE
Set max-height for structure field modal

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#469]
Hi,

when I have a structure field with many fields it becomes to high for the browser window. I added

    modal-content {
       max-hight: 96%;
       overflow: scroll;
    }

to the custom panel CSS, but maybe this should be added to the core. I’m not good at Git so I wasn’t sure if (and how) I should make a pull-request.

**Comment by AugustMiller** [comment]
There are improvements slated for the `2.1` release that address this. Check out the change log, [here](https://gist.github.com/bastianallgeier/061ddd007d5985ae28ca)!

**Comment by tweh** [comment]
Thanks! I didn’t know this list …
