### ISSUE TITLE
Blueprint files to use .yaml instead of .php 

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#477]
**adamcbrewer (https://github.com/adamcbrewer) - opened this issue 22 days ago**
> It's super frustrating having to change the syntax and indentation settings every time I open a blueprint file.
>
> Any chance of making these actual .yaml files instead of .php ones?

**Comment by JonasDoebertin** [comment]
+1!

The panel should check for a `*.yaml`, `*.yml` and (if no YAML blueprint was found) for `*.php` file when loading a blueprint so using the YAML file extension is optional.

**Comment by malvese** [comment]
Would also love such a change.

**Comment by distantnative** [comment]
I guess, we would need to sacrifice the following line from blueprint files then?

```php
<?php if(!defined('KIRBY')) exit ?>
```

**Comment by malvese** [comment]
Is it for security, so people can't read the file directly?

**Comment by distantnative** [comment]
I'd assume, but only @bastianallgeier knows ;)

**Comment by JonasDoebertin** [comment]
That most definitely is a security precaution to prevent people from accessing the blueprints directly (most server deliver YAML files as plaintext, by default).

I don't think it's necessary though. Public (http) access to everything within the `site/` directory is blocked from the `.htaccess` file by default, including the blueprints.

```
# block all files in the site folder from being accessed directly
RewriteRule ^site/(.*) error [R=301,L]
```

**Comment by jenstornell** [comment]
Yes. Keep security in htaccess and make the file to pure yaml. +1

**Comment by louiswalch** [comment]
+1

**Comment by bastianallgeier** [comment]
This is finally fixed in my decruft branch and will be in the next release.

**Comment by JimmyRittenborg** [comment]
Nice to get auto syntax highlighting for these :grin: 

While we're at it - why is the markdown files in the content folder .txt files instead of proper .md ?

**Comment by texnixe** [comment]
@JimmyRittenborg You can set .md extensions as an option in your config file:

```php
c::set('content.file.extension','md');
```

**Comment by JimmyRittenborg** [comment]
@texnixe that's cool -thanks! :+1: 

Was just wondering about the thought about as a default, masking markdown as text instead of .md - is anything lost, if it's changed, compared to .txt ?

Because if not, i think the default should be changed.

**Comment by jenstornell** [comment]
Agree with @JimmyRittenborg

**Comment by jenstornell** [comment]
Thanks @texnixe for "workaround".

**Comment by JimmyRittenborg** [comment]
Can this safely be removed from .yml files, or will it still prevent other scripts where kirby isn't present from accessing it
```php
<?php if(!defined('KIRBY')) exit ?>
```

I really haven't tested it, just if someone know from atop of his head 😁

**Comment by jenstornell** [comment]
@JimmyRittenborg I'm not answering your last question but I just figured out that `md` might not be the correct extension for the files. The format is `yaml` or `yml` but contains `md` for some parts.

**Comment by JimmyRittenborg** [comment]
@jenstornell dang it -  minutes ago I literally just bash renamed everything `.txt` in /content folders to `.md`what makes you say it is `yml` ? because of its extended formattings or?

**Comment by jenstornell** [comment]
@JimmyRittenborg Yes, it's the other way around. `md` uses `yaml` sometimes. Sorry about my stupidity.

**Comment by JimmyRittenborg** [comment]
No it's alright my friend :+1: 

So I'm not on the wrong track ? You just meant that the .txt files in the content folder shouldn't be YAML but markdown rather?

I've just converted all blueprints which previously was .php into .yml
and all content which previously was .txt into .md

**Comment by jenstornell** [comment]
Yes, that should be totally correct. I will probably do the same thing.

**Comment by JimmyRittenborg** [comment]
Nice - yeah I really like it.

rename.sh
```bash
#!/bin/bash
find -L */*/content -type f -name '*.'$1 -print0 | while IFS= read -r -d '' file; do
    echo "renaming $file to $(basename ${file%.$1}.$2)";
    # mv -- "$file" "${file%.$1}.$2";
done
```

```shell
sh rename.sh txt md
```

1. Fit the `*/*/content` part to your own needs.
2. If everything looks cool, just uncomment the `mv` line and run it again.

**Comment by lukasbestle** [comment]
> Can this safely be removed from .yml files, or will it still prevent other scripts where kirby isn't present from accessing it
> <?php if(!defined('KIRBY')) exit ?>

Yes, that can be removed. It doesn't do anything when using YAML blueprints.

**Comment by JimmyRittenborg** [comment]
Great, thanks @lukasbestle :+1:
