### ISSUE TITLE
Thumbs for PNG files don't work with PHP's built-in web server

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#482]
Thumbnail generation fails for PNGs on my Mac running PHP's built-in server. It works when deployed on a pretty standard shared LAMP hosting.

Not an important issue, as live sites won't run on PHP's built-in server, and switching to ImageMagick solves it for me. But it can be annoying when you start developing a site with this handy little server.
I also tried GIFs and JPEGs, they work fine.

![png-error](https://cloud.githubusercontent.com/assets/193492/7776660/cd521f72-00bc-11e5-8609-b655c5c3954e.png)

The error is:
```Fatal error:  Call to undefined function abeautifulsite\imagecreatefrompng() in /Users/___/Documents/Sites/___/kirby/toolkit/vendors/abeautifulsite/SimpleImage.php on line 1110```

**Comment by moritzz** [comment]
Hi @malvese. I had this issue too —and noticed that the setup I was running Kirby at had no PHP GD library available. Did you check that?

**Comment by moritzz** [comment]
P.S. Standard OS X 10.10 installs do not have PHP GD library installed. You can however get PHP with GD library for these setups [here](http://php-osx.liip.ch). Have fun, M.

**Comment by malvese** [comment]
I just checked, GD is in fact enabled, but PNG support isn't:
````gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 9 compatible
WBMP Support => enabled
XBM Support => enabled
```
Thank you for putting me on the right track, and for the link!

**Comment by moritzz** [comment]
You're welcome. Bye bye, M.

**Comment by malvese** [comment]
And here's a [possible solution](http://stackoverflow.com/questions/26493762/yosemite-php-gd-mcrypt-installation/26505558#26505558).

**Comment by moritzz** [comment]
BTW: Looks like installing 10.11 is another easy solution; even though not 'quick' at all.
