### ISSUE TITLE
Small images are upsized on the Panel's "files" page

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#483]
The images grid displays upsized images if the originals are smaller than 300×200. Very small files like logos are then barely recognizable.

![image-crop-before](https://cloud.githubusercontent.com/assets/193492/7777775/f7e9691c-00c5-11e5-802f-7644857f8e77.png)

By changing the parameters passed to thumb() I was able display small images at their native size, then added a bit of CSS to center them.

![image-crop-after](https://cloud.githubusercontent.com/assets/193492/7777887/00ead108-00c7-11e5-9bee-3956f3739c85.png)

I was about to make a pull request, but I have two questions:

1. Is there a reason why images are cropped, beyond having a cleaner, uniform grid?
Because my fix changes ```'crop' => false``` to true, it means there would be a "transparency" grid around pictures when their ratio is not exactly 3:2. That is pretty much every picture.
Alternatively I could check the image dimensions, and crop if it is larger and higher than 320×200, but I think not cropping would also be beneficial for bigger images. E.g. for very tall images an uncropped thumbnail is more useful than a small part of a cropped one:
![image-crop-compare](https://cloud.githubusercontent.com/assets/193492/7778209/94ff3bfc-00c9-11e5-8589-840e9d24c6da.png)
What do you think?

2. Is there a minimum browser version required for the Panel, like IE9? I'm asking because the easiest way to center the images is using [transform: translate(x,y);](http://caniuse.com/#search=translate). Support for translate() in IE older than version 9 is way too ugly.

**Comment by bastianallgeier** [comment]
I fixed this for 2.2. It's already on the develop branch.
