### ISSUE TITLE
Structured data input now properly displayed in panel

### ISSUE THREAD

**Issue by plison** [getkirby/panel#487]
I'm trying to modify a blueprint to include a structured data input, as explained in http://getkirby.com/docs/cheatsheet/panel-fields/structure. Unfortunately, the panel does not seem to properly handle the structured field, as I cannot add any entry from the panel. 

Here is a screenshot:
![skjermbilde 2015-05-25 kl 01 54 51](https://cloud.githubusercontent.com/assets/11574012/7790259/9f1be090-0281-11e5-9a39-7e66e54079d5.png)

As you can see, the panel does list the structured field and displays an "add" button on the right side of the panel, but clicking the button has absolutely no effect. Also, I do not get the "no entries yet" text like the one shown in the example. The structured field is the one listed in the example.

Any idea what's causing the problem? I'm using the starter kit without any modifications.  I tried both in Firefox, Safari and Chrome, and the "add" button is inactive in all browsers.

**Comment by plison** [comment]
I just noticed that the "add" button for the structured input is actually not the only one that does not work: the "bold", "italic", "link" and "email" buttons in the panel do not seem to work either on my machine.

**Comment by malvese** [comment]
An empty structure should actually look like this (from a fresh Starterkit with only a structure field added):
![structure](https://cloud.githubusercontent.com/assets/193492/7795403/0bfb22a4-02d5-11e5-860f-b6789b41f3d5.png)

I suspect there is an error either in your blueprint, or somewhere else in your site.

**Comment by plison** [comment]
The blueprint is exactly like the one in the example (http://getkirby.com/docs/cheatsheet/panel-fields/structure), so it cannot be the source of the error. I guess there must be some configuration setting on the server I'm using that causes this behaviour? I didn't make any modification to the starter kit.

The PHP settings can be accessed here: http://folk.uio.no/plison/kirby/test.php.

**Comment by malvese** [comment]
The missing part with "No entries yet" is in a Handlebar ```{{#unless…}}``` expression. So it is rendered with Javascript. Do you have any JS error in your console?

**Comment by plison** [comment]
Yes, there is actually a Javascript error in the Javascript console, but I cannot quite make sense of it. It says there is an illegal character on line 24, column 876 of the source file ("panel"). The incriminated javascript line is "t.months=r%12;...", which seems to come from the file ./panel/app/fields/date/assets/js/moment.min.js.  But there doesn't seem to be anything wrong with that line, perhaps the column number is wrong?

**Comment by plison** [comment]
I had a closer look at it, it seems again to be a by-product of the fact that my server has activated the magic quotes.

**Comment by plison** [comment]
FYI: my host accepted to disable the magic quotes and the problem solved itself ;-)
