### ISSUE TITLE
Remove dotfiles from Site files list in sidebar

### ISSUE THREAD

**Issue by adamcbrewer** [getkirby/panel#493]
![screen shot 2015-05-27 at 14 32 41](https://cloud.githubusercontent.com/assets/423310/7837151/529bc480-047d-11e5-9899-d71c3c67f667.png)

**Comment by distantnative** [comment]
I assume, this file wasn't added through the panel, was it? Cause that shouldn't be possible.

**Comment by texnixe** [comment]
This may happen if you version control the content folder separately from the rest, so hiding dot files from the panel sounds like a good idea to me.

**Comment by adamcbrewer** [comment]
Yeah, the way I'm versioning the project it just popped into view after the upgrade. 

Though, it might be a good idea to have a list of files that should be ignored?

**Comment by distantnative** [comment]
This change removes dotfiles from panel views: https://github.com/distantnative/panel/commit/7725ee5c15fbe446752cf4b26456a5dc59ae0809

**Comment by bastianallgeier** [comment]
This is finally fixed in my decruft branch and will be in the next release.
