### ISSUE TITLE
New options for checkboxes in the Panel

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#500]
In a discussion about a possible UI for [multiple user roles](http://forum.getkirby.com/t/multiple-user-roles/1145/33?u=malvese) came the idea of an option to control the width of checkboxes. At the moment they're quite large and take 50% of the content's width on "desktop".

If we need lots of checkboxes, or if they have short descriptions, it would be nice to make them smaller, so the whole field would take screen space.

![checkboxes](https://cloud.githubusercontent.com/assets/193492/7883237/40ee7964-0615-11e5-9a0c-e0559080a192.png)

![checkboxes-33](https://cloud.githubusercontent.com/assets/193492/7882958/df28d21c-0612-11e5-8115-40bb8320d8e6.png)

![checkboxes-25](https://cloud.githubusercontent.com/assets/193492/7882957/df2394fa-0612-11e5-920e-a73dcd288949.png)

A problem is that fields already have a ```width``` option, and we need a similar one for items *inside* this one. We need a different name for this option. Tentative names: ```display:```, ```items:```, ```item-width:``` (can we have hyphens?).

```yaml
display: 1/3
display: 1/4
```
Obvious values: ```1/3```, ```1/4``` (default is ```1/2```).
Other potential value: ```full``` or ```1/1``` or ```1``` (forces 100% width even on "desktop").

**Comment by distantnative** [comment]
Ha, I know we messaged about this, but I only just realized that I stumbled upon an option while coding the multiselect field and that this is exactly for this case:

You can add `columns: 4` to get 4 checkboxes per row instead of 2. Maybe we can add additional options.

**Comment by malvese** [comment]
Oh yeah, that's even easier to grok. So mean this is already in? So we can add ```1``` and  ```3``` and basically be done? :)
Another bit that need to be in the Docs!

**Comment by distantnative** [comment]
1 should work already as well and I just added 3 and 5 - pull request coming up any second ;)

**Comment by malvese** [comment]
:+1:

**Comment by distantnative** [comment]
Has been added to the develop branch and will be part of an upcoming release.
