### ISSUE TITLE
Use <object> tag to wrap SVGs in image views

### ISSUE THREAD

**Issue by jonwhipple** [getkirby/panel#519]
Display SVG files using the <object> tag inside the file views. This will make sure that SVGs that are enhanced with any Javascript for any reason will display accurately in the Panel. See also http://forum.getkirby.com/t/notes-about-handling-svgs-in-kirby-and-your-sites/1381

**Comment by bastianallgeier** [comment]
Very good discussion and hints. I just added this to my dev branch for the next release :)
