### ISSUE TITLE
Folder permissions

### ISSUE THREAD

**Issue by zvaehn** [getkirby/panel#521]
Hi Bastian,

i am unable to update any of my pages via the panel.
If i klick on the save Button the spinner in the right upper corner keeps spinning, but no changes are applied.

The page `.txt`-files are temporarily set to `777`.
My `content`-folder has `775`.

Are there any other folder/file permissions i have to set?

Best,
Sven

**Comment by distantnative** [comment]
Do you have any plugins, custom fields at work? I remember that spinner ocurring with javascript errors from a custom field.

**Comment by zvaehn** [comment]
unfortunately no.
My blueprint looks like:
![screen shot 2015-06-25 at 15 34 13](https://cloud.githubusercontent.com/assets/5555821/8355474/c8ac66b4-1b4f-11e5-881f-c4c63f4824d4.png)

**Comment by malvese** [comment]
I *believe* I remember this happening when I updated Kirby to 2.1 without logging out then in.

**Comment by bastianallgeier** [comment]
Is this still an issue?

**Comment by zvaehn** [comment]
yes. http://d.pr/i/1d5V5

**Comment by distantnative** [comment]
Still an issue with the 2.2 beta (currently on the develop branch)?

**Comment by bastianallgeier** [comment]
I think this really is a permission problem. I will close it for now.
