### ISSUE TITLE
field:tags autocomplete broken in Safari

### ISSUE THREAD

**Issue by dgdsp** [getkirby/panel#527]
using the mouse for choosing autocomplete suggestions does not work as expected in Safari: instead of the suggestion, only the part wich has been typed before is assigned.

works fine in Chrome.

works fine, when using the keyboard (arrow down, enter).

**Comment by shoesforindustry** [comment]
Yep, I get the same, very annoying.

**Comment by bastianallgeier** [comment]
I'm super late here because it took me ages to find the issue, but I finally solved the riddle :) The fix will be included in the next release.
