### ISSUE TITLE
Can't save content on some subpages 

### ISSUE THREAD

**Issue by obear** [getkirby/panel#531]
In one of my client sites, from one day to an other some pages in the panel does not save. If I hit the save button I get an endless turning spinner in the upper right and an error in the console with the message `TypeError: response.data is undefined` that points me to `panel.js:1073:34`

I only have this problem in some subpages. Other pages are saving normaly.

Anyone an idea how to solve this? I checked the .txt files but everything seems to be normal.

I'm on Kirby version 2.1.0 but i had this error with version 2.0 as well....

**Comment by distantnative** [comment]
Have you checked if this error still remains with the 2.2 beta (currently on the develop branch)?

**Comment by bastianallgeier** [comment]
Since the new panel js works completely differently and handles errors more reliable I will close this for now.
