### ISSUE TITLE
With date.handler set to strftime, date folder numbering fails

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#536]
The issue is described in the forum http://forum.getkirby.com/t/error-in-panel-if-date-handler-strftime/1686 and could be reproduced:

If you set `c::set('date.handler', 'strftime'); ` in config.php, and numbering of pages is set to using the date field, if you subsequently set a page to visible/invisible via the panel, the result is a prepended "Ymd" string every time the setting is toggled, e.g. Ymd-Ymd-article-one.txt.

**Comment by bastianallgeier** [comment]
See: https://github.com/getkirby/panel/issues/557 :)
