### ISSUE TITLE
File field type and image drops

### ISSUE THREAD

**Issue by ian-cox** [getkirby/panel#54]
# File fields and image drops
I would love to have a file field type like this!

![file_field_and_file_drop](https://cloud.githubusercontent.com/assets/4325127/2892647/3619dafe-d53f-11e3-9593-fe4284636ee1.gif)

**File field type**: would allow you to create a field type of file and then drag any uploaded file directly into it's dropzone.

**Image drops**: would allow you to drag uploaded images directly into a text area field to be converted to kirby text.

**Where I can see this being useful**:
Easy custom thumbnails, for featured content, or maybe you have a blog template which uses a different full page background image for each post. Of course the possibilities are endless.

**Comment by byybora** [comment]
+1 looking forward this feature!

**Comment by vicegold** [comment]
Any timeframe on the file and image fields?

**Comment by simonseddon** [comment]
+1

Image field / file field first, fancy drop & drop later if necessary.

Any timeframe on this? The default 'files' part of the panel doesn't cater for separation of images for different purposes within a template, which is crucial.

**Comment by lekkerduidelijk** [comment]
Tip:
I created a slider with the structure field, including a preview image. The only downside is that the user needs to type in the file name by hand. Other than that, it works smoothly. 
My client uses this with great ease.

**Comment by simonseddon** [comment]
That's great for a slider and perhaps other applications but this sort of 'hack' is not fit for all scenarios - or clients.

**Comment by benseitz** [comment]
Any news on the image field? Now I use dynamic select (for one image) and dynamic checkboxes (for more than one), which works fine, but drag and drop seems more intuitive.

**Comment by bovisp** [comment]
I would love to use this feature on a blog article blueprint where the user can drag and drop an uploaded file into the preview image for field so that can be the header image in the article. If it's empty, the header will be styled in a different way.

**Comment by bastianallgeier** [comment]
I'm closing this as Jonas is working on a fantastic field plugin and I think it's definitely better to support that than coming up with my own thing: http://forum.getkirby.com/t/visual-file-select-panel-field-extension/397/1
