### ISSUE TITLE
Option to set default subpage template via Blueprint, in case there is more than 1

### ISSUE THREAD

**Issue by Stolzenhain** [getkirby/panel#541]
When you're used to fixed subpage templates and add another like this

    pages: 
      template: 
        - post
        - special_post

all editors are then forced to choose the template via 2 clicks. 
It would be nice to be able to set a standard option, analog to the default option of `select` fields.

**Comment by dgdsp** [comment]
+1

**Comment by bastianallgeier** [comment]
This is actually already possible by changing the order of the options. The first one will always be preselected.
