### ISSUE TITLE
Scrolling not working in IE after modal

### ISSUE THREAD

**Issue by dervondenbergen** [getkirby/panel#543]
The code, which gets executed to make a site scrollable again (https://github.com/getkirby/panel/blob/f8ecc547435d0cd7429198ac10989394a5eb61ae/assets/js/apps/main.js#L118) after a Modal closed doesn't work in IE.

The style of the `body` element doesn't get set to `overflow: initial`. That results in to being able to scroll until the page gets reloaded.

It could work if the style gets set to `overflow: visible`.

**Comment by distantnative** [comment]
The upcoming v2.2 handles the whole (non-)scrolling of modal backgrounds very differently so that this should not be an issue in 2.2 anymore.
