### ISSUE TITLE
Panel field of type headline has huge padding

### ISSUE THREAD

**Issue by kopfnuss** [getkirby/panel#544]
The rendered headline field gets a padding-top of 6em. This leaves a huge gap. Is this intended?

https://github.com/getkirby/panel/blob/master/app/fields/headline/assets/css/headline.css#L8
![image](https://cloud.githubusercontent.com/assets/1991584/9563483/07d3ef8c-4e7d-11e5-8e75-5b229e2fc404.png)

**Comment by texnixe** [comment]
You can use a custom panel stylesheet to change this if you don't like the padding. In your config.php you can set the stylesheet like this:
```php
c::set('panel.stylesheet', 'assets/css/panel.css');
```

**Comment by kopfnuss** [comment]
Thank you @texnixe. I wasn't aware that I could add a custom panel asset. Are these settings documented somewhere? 

That being said this my problem. However, I am not sure if this gap is intended after all?!

**Comment by texnixe** [comment]
The custom panel stylesheet option is only documented in the 2.0.6 changelog: http://getkirby.com/changelog/kirby-2-0-6

All other options have been moved to the cheatsheet section of the docs: http://getkirby.com/docs/cheatsheet#options

**Comment by kopfnuss** [comment]
Thanks! I was aware of the documented options in the cheatsheet, but didn't check the changelog.

**Comment by texnixe** [comment]
I created a PR to have it added to the docs: https://github.com/getkirby/getkirby.com/pull/133
