### ISSUE TITLE
Invalid route error after session destroyed

### ISSUE THREAD

**Issue by afbora** [getkirby/panel#546]
Panel version: 2.1.0

When i try to login/refresh/action  after a while(session destroyed), i am getting error like following:

> Fatal error: Uncaught exception 'Exception' with message 'Invalid route' in /public_html/panel/app/panel.php:222 Stack trace: #0 /public_html/panel/index.php(47): Panel->launch() #1 {main} thrown in /public_html/panel/app/panel.php on line 222

**Comment by JimmyRittenborg** [comment]
I'm having this issue too

I'm running kirby on nginx, i dont know if that has something to do with it.

**Comment by oroco** [comment]
I’m too, I posted this issue on the Kirby forum: http://forum.getkirby.com/t/php-fatal-error-when-login-in-the-panel-after-session-expire/1982

**Comment by JimmyRittenborg** [comment]
@h0r0man are you running on nginx ?

**Comment by h0r0man** [comment]
@JimmyRittenborg I was running on Apache using MAMP Pro, with a special url of CodeKit `sitename.local:5757`, I’ve solved just using a MAMP Pro url `sitename:8888`.

**Comment by JimmyRittenborg** [comment]
MAN! I'm using CodeKit too, with just a hardcoded injection of the url for dev sites - i'll correct it see what happens -thanks :+1:

**Comment by JimmyRittenborg** [comment]
At some point i really have to port my dev flow over to Gulp anyway :laughing:

**Comment by JimmyRittenborg** [comment]
@h0r0man can you confirm that it has indeed, been solved for you? (it seems like it didn't do it for me)

**Comment by JimmyRittenborg** [comment]
What about you @byybora do you use CodeKit ?

**Comment by byybora** [comment]
@JimmyRittenborg I'm getting this error on Apache live server.

**Comment by JimmyRittenborg** [comment]
Okay, so it has nothing to do with CodeKit interference.

Are we really the only ones who're getting this error ?

**Comment by jenstornell** [comment]
I have probably had this error on my localhost. Sometimes (but not often) when I try to login I get an error message, might be the one above.

When I refresh or try to login again it works again.

**Comment by JimmyRittenborg** [comment]
Yeah the error is very inconsistent (other than it only shows at session timeout).

I think i actually experienced it on a live server too i'm about to launch, where errors of cause is turned off, so clients would simply just get a complete plank white page :laughing:

**Comment by h0r0man** [comment]
@JimmyRittenborg Sorry but I haven’t error anymore like for two days and not I’m having it again without special CodeKit url, so it’s 100% a bug @bastianallgeier.

**Comment by bastianallgeier** [comment]
It's indeed a bug. I'm really sorry for it. I'm currently trying to figure out if it makes sense to fix that in the current version, because the new "decrufted" version, which is pretty close to a beta has a completely different architecture for this and the bug is not repeatable there. What do you think?

**Comment by jenstornell** [comment]
Add it to the next version. No panic.

**Comment by JimmyRittenborg** [comment]
@bastianallgeier it's also fine by me.

**Comment by bastianallgeier** [comment]
I will close this now. The fix will be available with the new release pretty soon.
