### ISSUE TITLE
v::url() in fieldoptions.php prevents use of "external" query API on localhost

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#548]
When trying to use the new external query API as described here http://getkirby.com/changelog/kirby-2-1-0#more-flexible-dynamic-options on localhost, this fails because the url verification v::url() in /panel/app/lib/fieldoptions.php does not seem to allow either http://localhost or http://127.0.0.1 URL patterns. This makes it difficult to test/debug functionality on local server without fiddling with the core.

**Comment by rhawbert** [comment]
:+1:

**Comment by bastianallgeier** [comment]
I just fixed this in my decruft branch for the next release.
