### ISSUE TITLE
#css error on the dashboard "your account"

### ISSUE THREAD

**Issue by AldoFerrari** [getkirby/panel#555]
I'm testing locally on WAMP the version of Kirby 2.1.1

the css for the block "Your Account" on Chrome 45+ it does not appear for an error of a "position:relative"

on chrome:
![screenshot-localhost 2015-09-16 13-40-38](https://cloud.githubusercontent.com/assets/1926233/9903772/59da6efa-5c79-11e5-8106-888552c7c804.png)

on explorer:
![screenshot-localhost 2015-09-16 13-42-30](https://cloud.githubusercontent.com/assets/1926233/9903779/61382d4a-5c79-11e5-9677-754e66ae8659.png)

**Comment by byybora** [comment]
I have too on Chrome :+1:

**Comment by h0r0man** [comment]
Seems that the issue happening on webkit browser because of the css columns, see panels [_dashboard.scss](https://github.com/getkirby/panel/blob/f8ecc547435d0cd7429198ac10989394a5eb61ae/assets/scss/components/_dashboard.scss#L17-L33)

**Comment by bastianallgeier** [comment]
Unfortunately this is a webkit bug with positioning in child elements of columns. I found a workaround for it and added it to the decruft branch for the next release.

**Comment by Targoran** [comment]
While it works on all default widgets, it somehow doesn't seem to work on custom widgets although use the same syntax. When I change the position of the widget so it's displayed in the first column, it works though.
