### ISSUE TITLE
Date field usable although readonly is set to true

### ISSUE THREAD

**Issue by DavidUnzue** [getkirby/panel#556]
In the Panel, you can set a field within a Blueprint as `readonly: true`, so it will be blocked and the user won't be able to change it.

But with the Date field, and probably with other javascript based fields, the readonly option isn't working, since the click event for showing the date widget is being registered anyway, as I presume.

<img width="817" alt="bildschirmfoto 2015-09-16 um 16 19 40" src="https://cloud.githubusercontent.com/assets/9588510/9907462/91a41924-5c8f-11e5-8bc4-4804b22a55ad.png">

**Comment by bastianallgeier** [comment]
This is already fixed in my decruft branch for the next release
