### ISSUE TITLE
date.handler 'strftime' and sorting pages by date

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/panel#557]
If you set the date.handler to 'strftime'.
```php
c::set('date.handler', 'strftime');
```
You can’t sort pages by date.
```yaml
pages:
  num:  date
```
If you want to change the status to visible nothing happens. The status will not change.

**Comment by bastianallgeier** [comment]
This is fixed in my decruft branch for the next release. With the current release, please just specify the format in the meantime: 

```yaml
pages: 
  num: date
  format: %Y%m%d
```
