### ISSUE TITLE
Radio Field can’t deselect a option

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/panel#561]
Once you selected a option in a radio field you can’t nevermore deselect the option.

**Comment by malvese** [comment]
To my knowledge and understanding, it is the normal behavior of html radio buttons.

**Comment by afbora** [comment]
Radio button is unselectable except using with javascript.

Try checkbox instead of radio.

**Comment by tobiasfabian** [comment]
Sure, I could use checkboxes for the moment. But. I want a field where I can select either one option or none.

**Comment by afbora** [comment]
So you can use `select` field. One option selectable or none.

````
fields:
	category:
		label: Category
		type: select
		options:
			design: Design
			architecture: Architecture
			photography: Photography
			3d: 3D
			web: Web
````

**Comment by tobiasfabian** [comment]
Thanks, that’s a good solution.
