### ISSUE TITLE
Language fallback in blueprint translations

### ISSUE THREAD

**Issue by groenewege** [getkirby/panel#562]
When I create a multi-language blueprint for the admin panel, it looks like this : 

    title:
      en: Project page
      fr: Page de projet
    fields:
      title:
        label:
          en: Title
          fr: Titre
        type:  text
      text:
        label:
          en: Text
          fr: Texte
        type:  textarea

This works great if my admin user chooses English or French as his language, but the translation does not default to english when another language is chosen.

If the user chooses another language, i.e. Italian, the admin panel does not fall back to english : 

- the labels display the key of the field (i.e. "title" and "text" with lowercase t) 
- the blueprint title is not used in the template select field and always displays "template" as the title
- options of a select field also display the key of the field

**Comment by bastianallgeier** [comment]
I just fixed this on the decruft branch for the next release.
