### ISSUE TITLE
Only display license code in site options to admins

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#566]
See [this thread in the forum](https://forum.getkirby.com/t/how-can-i-hide-the-licence-key-in-the-panel/2193?u=lukasbestle).

Feature request: Only display the license key to users with the admin role.

**Comment by distantnative** [comment]
Looking at https://github.com/getkirby/panel/commit/7dac25c1e971489d5387fb35ebb26229d8d95be9 - maybe we could use `panel()->user()->hasPermission('panel.site.update', panel()->site())` instead of checking the role. On the other hand, maybe really just `admin` should see it. Just a thought.

**Comment by lukasbestle** [comment]
Maybe we could also use a separate permission for that, like `panel.info.view`. It would then also hide the version information if the user didn't have the permission.

**Comment by texnixe** [comment]
Why is the license code there in the first place? Since it is not there (at least not yet) to check the validity of the license, it's more to remind people to buy a license once they go live and maybe to have easy access to the license in case of support needs (and maybe to reassure our customers that they got a (valid) license). The question is if this is more related to roles or permissions, maybe the latter makes more sense.

**Comment by lukasbestle** [comment]
Yes, that's true. I think that a permission makes more sense, because you might have an editor who needs Kirby support and therefore needs to have version and license information in the Panel.

**Comment by maxfenton** [comment]
:+1:

**Comment by afbora** [comment]
New `root` user role is good alternative instead of `admin`.

For ex: Root user is agency/developer, admin is client.

**Comment by bastianallgeier** [comment]
I added panel.info.licenses and panel.info.versions as new options to my new version on the Decruft branch.

**Comment by bastianallgeier** [comment]
I think it's a good idea to have that added to something like a root user role, but that will have to wait a bit more.

**Comment by afbora** [comment]
@bastianallgeier Great great great, thanks! :+1: The feature that in my mind for a long time :))

**Comment by luigimannoni** [comment]
I know this is an old thread but caught my eye only now.
Can we simply have a `c::set('showlicense', false)` on the config file and hide the license key? 
At the end most developers aren't the final client and that would prevent key stealing from root/admins once key verification is in place in the future.

Perhaps just keep showing when Kirby isn't registered.
