### ISSUE TITLE
Blurry modals in Chrome

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#574]
(On the develop branch, upcoming 2.2)
A combination of css translate and backface-visibility can make modals blurry, depending on your window size.
How to reproduce: in Chrome open a modal then resize your window until you get some blur.

![blur](https://cloud.githubusercontent.com/assets/193492/10559417/cfb4f44e-74f0-11e5-9d92-9bf6e63e0935.gif)

Removing -webkit-backface-visibility: hidden fixes the blur but it may be needed for a reason beyond my grasp.

**Comment by bastianallgeier** [comment]
Weirdly backface-visibility fixed this for me in the last Chrome version, but is broken again. I moved to a solution without webkit-transform as there seems to be no reliable way to avoid blur.
