### ISSUE TITLE
Search placeholder is barely visible in webkit

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#579]
Its default color is light grey, and panel.css doesn't define one, so it's almost invisible on top of the green background.
Left Firefox, right Chrome:

![placeholder](https://cloud.githubusercontent.com/assets/193492/10589170/036dda5c-76aa-11e5-9541-fe7758a4122b.png)

**Comment by texnixe** [comment]
Yeah, I agree, that's hardly accessible.

**Comment by bastianallgeier** [comment]
I agree too. I haven't fully tested all browsers yet and Firefox is actually way smarter in adjusting the color automatically.

**Comment by bastianallgeier** [comment]
I just fixed it on the develop branch.
