### ISSUE TITLE
Alert when leaving a page if changes have not been submitted

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/panel#58]
Could prevent accidental loss of just edited content.

Example on facebook: Write a comment -> don't submit -> try to navigate to another website

**Comment by distantnative** [comment]
Storing the unsaved changes in 2.1 now, this might be not necessary anymore.

**Comment by ralfgoeke** [comment]
Confirmed! It works just fine now, so I'll happily close this issue. :)
