### ISSUE TITLE
JS from custom fields not firing after 'Save' in Kirby v2.2 beta

### ISSUE THREAD

**Issue by ian-cox** [getkirby/panel#580]
The JS hooks in my [color picker field](https://github.com/ian-cox/Kirby-Color-Picker) broke after updating to v2.2.

I simplified and fixed some issues with the color picker which I've pushed to the ```develop``` branch:
```git clone -b develop git@github.com:ian-cox/Kirby-Color-Picker.git color```

The plugin JS does fire on page load after the HTML is rendered to the page however it does not fire after the save button is triggered causing the field to break.

Any thoughts on this?

Thanks!

**Comment by distantnative** [comment]
Does it help to bind whatever you want to do to the following?

```javascript
app.content.form().on('submit', function(e) {
    // whatever should be done when form is submitted
});
```

**Comment by ian-cox** [comment]
Thanks nico, that looks helpful. I'll check it out!

**Comment by distantnative** [comment]
Let us know if it works for you, so that we can try to help further or close this issue :)
