### ISSUE TITLE
Shortcut on save does not work on PC

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#586]
Command + S work to save the page on a Mac, right? I tried CTRL + S and ALT + S but none of them worked out on PC.

If there is no shortcut to save the page on PC, I think it's an issue.

**Comment by distantnative** [comment]
It checks for `meta` key and `s` or `meta` and `enter`. On Mac `e.metaKey` refers to the `cmd` key, on windows apparently to the windows key - see: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey 

Does that work for you?

**Comment by lukasbestle** [comment]
Hm, but I think it should use Ctrl-S on Windows, because that's what people are used to.

**Comment by distantnative** [comment]
It would complicate the keyboard shortcut code a bit. At the moment it only checks for one key currently pressed and uses `e.metaKey` to check for the second one:

```js
    // event delegation for all global shortcuts
    $(document).on('keydown', function(e) {

      switch(e.keyCode) {

        // meta+s
        // meta+enter
        case 83:
        case 13:
          if(!e.metaKey) return true;

          // check for an opened modal
          if(!app.hasModal()) {
            // submit the main content form
            app.content.form().trigger('submit');
          }

          return false;
          break;

        // esc
        case 27:
          app.modal.close();
          return false;
          break;
      }

    });
```

It could be changed to something like this (best thing I know right now to check for any two keys pressed at the same time:

```js
    // event delegation for all global shortcuts
    app.keys = [];
    $(document).on('keyup keydown', function(e) {

      app.keys[e.keyCode] = e.type === 'keydown';

      var metaKey = app.keys[17] || e.metaKey;

      // meta+s
      // meta+enter
      if(metaKey && (app.keys[83] || app.keys[13])) {
        // check for an opened modal
        if(!app.hasModal()) {
          // submit the main content form
          app.content.form().trigger('submit');
        }

        return false;

      } else if(app.keys[27]) {
        app.modal.close();
        return false;
      }

    });
```

**Comment by jenstornell** [comment]
The Window + S does not work either. It just opens the Window Search.

I agree that Ctrl + S would be the best solution. That is what all applications use, like Word, Sublime Text and so on.

I think the save shortcut is the most important so making it work (even on PC) would be a great benefit. I press Ctrl + S all the time when I write stuff.

It also probably need to block out the default behavior of Ctrl + S which is Save Page as HTML. Google Drive succeded with it so it's possible. How? I have no idea. preventDefault(e) maybe?

**Comment by lukasbestle** [comment]
Cmd-S works on OS X because the handler returns `false` if the combination is pressed. Otherwise you would have the same problem.

So generally Ctrl-S works as well, but currently the Panel does not handle this combination. Could you please try replacing the code in `assets/js/app.js:60` with the code proposed by @distantnative? Does it work?

BTW: Windows-S probably doesn't work because Windows grabs the event before it even gets to the browser.

**Comment by bastianallgeier** [comment]
Could you please fetch the latest version and test if CTRL+S works for you? It works for me on a Mac, but I didn't have a chance yet to test it on Windows.

**Comment by afbora** [comment]
CTRL+ S not working for me on Windows7 and Kirby 2.2.

**Comment by bastianallgeier** [comment]
Did you pull the latest panel version from the develop branch?

**Comment by bastianallgeier** [comment]
It's just up there since 2 or 3 minutes, so you might have caught the previous version.

**Comment by afbora** [comment]
Ye ye ye, it works! ;)

**Comment by bastianallgeier** [comment]
AWESOME :)

**Comment by bastianallgeier** [comment]
@jenstornell for you too? can I close this?

**Comment by afbora** [comment]
> CTRL + B = Bold
> CTRL + I = Italic
> CTRL + U = Underline

Above shortcuts not working on editor.

**Comment by jenstornell** [comment]
@bastianallgeier It works! Awesome! Close it if you want. I add a new issue if there would be any in this matter. Thanks!

**Comment by bastianallgeier** [comment]
Yay! I will create a different issue for CTRL+B, etc.

**Comment by distantnative** [comment]
`e.ctrlKey` – duh :persevere:
