### ISSUE TITLE
Add blueprint name as CSS class for custom styling

### ISSUE THREAD

**Issue by JonasDoebertin** [getkirby/panel#590]
> I just thought, if the name of the blueprint was added as a class in the markup in Kirby core, it would be easier to customize with CSS.

> It could be added to the body or mainbar element:

> `<div class="mainbar blueprint-homepage">`

> That way we could tweak the styles per blueprint.

— Malvese

[Related forum discussion](https://forum.getkirby.com/t/design-your-own-structured-fields-for-better-usability/2297/2?u=dieserjonas).

**Comment by bastianallgeier** [comment]
I've just implemented this on the develop branch for 2.2. I've added a form-blueprint-blueprintname css class to the form element. This makes most sense for me from a semantic standpoint. I hope you like it :)

**Comment by JonasDoebertin** [comment]
That was quick! 😃 Thanks a lot!

**Comment by texnixe** [comment]
Very nice 😃!

**Comment by malvese** [comment]
Yay! Thank you :smile:
