### ISSUE TITLE
Pages cannot be saved if checkboxes are not checked (v2.2 beta)

### ISSUE THREAD

**Issue by sashtown** [getkirby/panel#592]
I'm receiving validation-related error messages (“_Please fill in all fields correctly_”) when I try to save pages containing checkboxes (fields with `type: checkbox`) which are **not checked**. If I check 'em (all) I'm able save the page.

**Comment by SQbiz** [comment]
I just came across this, it was an issue on a 2.1.0 installation as well, but only when the field had `required: true`

**Comment by JonasDoebertin** [comment]
Facing the same problem here. I cannot save a page if a checkbox is uncheck, even if `required: true` isn't set.
