### ISSUE TITLE
Save button and unsaved content alert not very legible (v2.2 beta)

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#595]
The texts are barely legible in some cases, and the alert takes a lot vertical space.

![save-alert-1](https://cloud.githubusercontent.com/assets/193492/10710304/92b5959e-7a54-11e5-88da-ea2cbe5a7ed6.png)

A few quick suggestions:
- Remove the `<br>` in the alert, and reduce its top margin (.5em in the capture below instead of 1.5)
- Add a background to the button, rgba(239,239,239,0.8) here
- Start the gradient a tiny bit higher, like: -webkit-linear-gradient(bottom, #efefef, rgba(239,239,239,0.8) 85%, rgba(239,239,239,0))

![save-alert-2](https://cloud.githubusercontent.com/assets/193492/10710310/0874a536-7a55-11e5-8776-1c37187c9073.png)

**Comment by bastianallgeier** [comment]
Finally fixed this with a bit different solution:

![screen shot 2015-11-12 at 16 30 14](https://cloud.githubusercontent.com/assets/24532/11122283/cb4375a6-895a-11e5-9405-11d92cdd0781.png)

**Comment by malvese** [comment]
:+1:  Looks good!

**Comment by distantnative** [comment]
I really like the new solution. Just wondering if the linear gradient would look better if not as tall/big but shorter.
