### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/panel#60]
I'm planning to have some basic user permissions and groups for the panel. But this might be something that needs to wait until Kirby 2.1 or 2.2

**Comment by tnViking** [comment]
+9000 for this! I've been hoping this would become a feature.

**Comment by jbeyerstedt** [comment]
I have a customer right now, who wants some user groups, that should only edit some pages.
I think I have to hack a panel fork for this right now.
It would be great to have user groups that only can **edit** some of the pages.

**Comment by lukasbestle** [comment]
Do you mean "only edit" with the meaning of "no creation of new pages"?

**Comment by jbeyerstedt** [comment]
Yes, that´s what I need for this particular case. There are several groups which should only "update" their own "home page", but not any other content or structure of the whole website.
It´s the new home page of a small club, but the person who does the home page by now wants this functionality for the different groups of the club.

**Comment by lukasbestle** [comment]
Alright.

The question is if it makes more sense to define pages a group has access to in the "group settings" or to define access rights for groups in the page metadata. What do you think?

**Comment by benseitz** [comment]
I would prefer access rights for groups in the page blueprint. How about you?

**Comment by jbeyerstedt** [comment]
I first thought, that it would be nice to have it in the blueprints, but this seemed to be not so clever:
- add "valid" user groups to a blueprint:  
seems to be a bit too much overload, because you have to add more blueprints only for selecting user access
- add another field to the user role array in the config.php:  
you have to define every page which this user group should edit, but it seems to be ok for this case.  
you could also define if adding and re-arranging subpages is allowed for this user group (for the allowed pages/ folders).

**Comment by lukasbestle** [comment]
The downside of the definition in the site configuration is that it won't work once a page is moved/renamed. On the other hand, it makes it much easier to change permissions (defining permissions in the blueprints scatters the definition, defining them in the pages themselves scatters it even more).

**Comment by jbeyerstedt** [comment]
I don´t thought about renaming or moving the page (changing the url).

Defining user groups in the pages content file would fix my problem. But I think this would add more problems if adding subpages is allowed (e.g. one user which does a blog, but not anything else)

**Comment by tnViking** [comment]
In my case, I'm using it for a schools website, where I need each teacher is having their own page, and some teachers are allowed edit more than others.

**Comment by samnabi** [comment]
I'd like to add another use case for user permissions. Not sure how feasible it is to implement, but now that we have [user blueprints](https://github.com/getkirby/panel/issues/273), it would be great to be able to change the blueprint based on who's viewing the page.

i.e. an Administrator could set a "suspended" flag on a user's account, and then it would be easy to check for `$user->isSuspended()` when writing snippets and plugins. But we wouldn't want the user herself to be able to change her own suspended status :)

**Comment by distantnative** [comment]
@samnabi Might be an idea to think about not only general permissions, per blueprint permissions, but also per field permissions. We would need to think about that one a bit.

**Comment by mzur** [comment]
I thought about this a bit and here is what I came up with:

You can already define user roles and set whether the role is allowed to access the panel or not in the config. What's missing is a mechanism to configure which role is allowed to see which page and edit what content in the panel. So what about defining different blueprints for different roles?

Say we have the `admin`,  `editor` and `guest` roles. As "defaults" we then can create blueprints as usual where users can see all content but don't change anything (each field is readonly and no pages can be created/deleted). The `guest` role falls back to these blueprints. Now, as special permissions for the `editor` role, we can define separate blueprints that allow the users to edit content but don't delete or create pages. And finally we can define blueprints for the `admin` role that allow anything. Similarly there could be a default readonly user blueprint and a separate editable blueprint for the `admin` role. The blueprint directory could look like this:

```
- users/
   - admin.yml
   - admin.admin.yml
   - editor.yml
   - editor.admin.yml
   - guest.yml
   - guest.admin.yml
- default.yml
- default.editor.yml
- default.admin.yml
- error.yml
- error.admin.yml
- site.yml
- site.admin.yml
```

Although this potentially adds a lot of new files to the blueprint directory, this approach would allow for all permissions you can think of on the very level we already define them (the blueprints). What do you think?

**Comment by lukasbestle** [comment]
Thank you very much for sharing your thoughts. We have already decided on a solution and we are working on it already but we might come back to your idea if needed. :)

**Comment by mzur** [comment]
Neat! Is your solution already described anywhere? I'm curious about what you worked out :wink:

**Comment by lukasbestle** [comment]
Not yet, but once it is implemented, you will be able to see it on the develop branches of Kirby and the Panel. I will let you know.

**Comment by lukasbestle** [comment]
You can't just close this issue without a couple of emojis:

🎉🍰👯

:D

**Comment by bastianallgeier** [comment]
You are right! I was in a rush: 

👍 💯 💃 🐱
