### ISSUE TITLE
add 'tag' from auto suggest box by mouse fails (v2.2 beta)

### ISSUE THREAD

**Issue by svnt** [getkirby/panel#600]
add 'tag' from auto suggest box by mouse fails... sometimes. Very strange behaviour.
(I am using Safari browser.)

![okt 29 2015 05 25](https://cloud.githubusercontent.com/assets/5315038/10810117/d0a06b20-7dfd-11e5-8324-2a99946496b2.gif)

**Comment by bastianallgeier** [comment]
Is this in the 2.2 beta or still in 2.1.1? I actually fixed it in 2.2, so it'd be strange if that bug still exists.
