### ISSUE TITLE
wrong URL and 'Error: Invalid Panel URL' on 'Open preview' (v2.2 beta)

### ISSUE THREAD

**Issue by svnt** [getkirby/panel#601]
hello,

steps to reproduce:

- install nightly starterkit
- add one laguage to config.php:

```
c::set('language.detect', true);
c::set('languages', array(
    array(
	   	'code'    => 'de',
	    'name'    => 'Deutsch',
	    'locale'  => 'de_DE',
        'default' => true,
        'url'     => '/'
    ),
));
```

- add page "a" to root, make visible
- add page "b" to "a", make visible
- push "Open preview"

..ends up in the Error.

The Url is "/nightly/panel/pages/a/de/b" and should be "nightly/a/b".

Preview of page "a" works well.

Bug or have i missed something?

best regards,
Svnt

**Comment by texnixe** [comment]
Yes, this also happens in the langkit when switching to the development branch.
