### ISSUE TITLE
Impossible to create pages (UwAmp)

### ISSUE THREAD

**Issue by k06** [getkirby/panel#617]
Hello,

I use UwAmp 3.2 with php 5.5.15 and it seems to be impossible to create pages from the panel with Kirby v2.2.
Popup open, I can add name, url id works, but loading bar never end and nothing happens.

Regards

**Comment by k06** [comment]
Ok: Pages are created, but popup does not close and loadin bar does not end.

Regards

**Comment by distantnative** [comment]
Can confirm this in my local testing environment.

**Comment by distantnative** [comment]
Should be fixed on the develop branch.

**Comment by k06** [comment]
Thank you.
