### ISSUE TITLE
File upload: spinner doesn't show (2.2)

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#628]
<img width="611" alt="screen shot 2015-11-09 at 18 58 15" src="https://cloud.githubusercontent.com/assets/3788865/11041786/ef040184-8713-11e5-8bc2-699a55f1e6d2.png">

**Comment by bastianallgeier** [comment]
We need to move it to a data string directly in css.

**Comment by bastianallgeier** [comment]
Fixed :)
