### ISSUE TITLE
Visible subpages list numbering doesn't update automatically upon page deletion

### ISSUE THREAD

**Issue by jcs224** [getkirby/panel#63]
This is a pretty small bug, but probably worth mentioning.  After creating a page in the Panel, it looks like so:

![screen shot 2014-05-12 at 1 58 48 pm](https://cloud.githubusercontent.com/assets/6226188/2949609/9b449dda-da10-11e3-9342-9a1a1c5e3663.png)

All is well.  But after deleting a page, the numbering is off. It skips "3", which was where I arranged it to be in the subpage management menu:

![screen shot 2014-05-12 at 1 59 13 pm](https://cloud.githubusercontent.com/assets/6226188/2949614/afeb4c3e-da10-11e3-97bf-2fc89d2ef04a.png)

I'm able to fix this very easily by just moving the list items within the panel a little bit, then the sorting logic seems to kick back in:

![screen shot 2014-05-12 at 2 08 22 pm](https://cloud.githubusercontent.com/assets/6226188/2949676/5fd5730e-da11-11e3-9e13-8d39fa85eeb4.png)
![screen shot 2014-05-12 at 2 09 08 pm](https://cloud.githubusercontent.com/assets/6226188/2949680/6264adec-da11-11e3-9508-1f89d4280ff7.png)
![screen shot 2014-05-12 at 2 09 15 pm](https://cloud.githubusercontent.com/assets/6226188/2949681/64107e0a-da11-11e3-80ed-058ebfb3fd08.png)

It would be nice if it did the re-numbering immediately upon deletion.

Cheers!

**Comment by bastianallgeier** [comment]
This is finally fixed in the latest version on the develop branch. Took forever, but I'm glad it's now available :)
