### ISSUE TITLE
3 things about contextual menu

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#637]
**I have 3 minor things:**

- The hover icon is an edit pen. However when clicking it, it's not editing the page. It displays a menu. Maybe a menu icon or an arrow down would be more fitting. In the screenshot there are two edit pens. Only one of them goes to edit the page.
- The menu does not popup from the center of the list item icon. Is it good that the mouse position desides where the menu pops up?
- I have small delay when clicking the icon. Is the menu loaded on demand by ajax and not toggled by CSS? Why? Would the panel get too slow otherwise?

![context-menu](https://cloud.githubusercontent.com/assets/927011/11062274/d401838a-87ad-11e5-8fb1-a8b24a611cda.png)

**Comment by bastianallgeier** [comment]
I agree that the pencil icon might not be the best choice yet. Might need to think about alternatives. Attaching the menu to the mouse position gives it more flexibility and I have to do less calculation about the parent object. I never really worried about the visual position to be honest. It's quite common to attach context menus that way. Loading it via Ajax is the only way in my opinion to handle this. Each page might have different options and URLs for those options. Putting everything into the source of the sidebar for example would be a huge mess. Lots of HTML and also lots of processing on the backend.

**Comment by bastianallgeier** [comment]
It would also be better to separate such recommendations into different issues, so we can work on them separatedly.

**Comment by jenstornell** [comment]
I opened a new one. Sorry about grouping issues. Will do better...
