### ISSUE TITLE
Change contextual menu hover icon

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#638]
The hover icon is an edit pen. However when clicking it, it's not editing the page. It displays a menu. Maybe a menu icon or an arrow down would be more fitting. In the screenshot there are two edit pens. Only one of them goes to edit the page.

![context-menu](https://cloud.githubusercontent.com/assets/927011/11062274/d401838a-87ad-11e5-8fb1-a8b24a611cda.png)

**Comment by distantnative** [comment]
Menu icons:
http://fortawesome.github.io/Font-Awesome/icon/list-ul/
http://fortawesome.github.io/Font-Awesome/icon/list/
http://fortawesome.github.io/Font-Awesome/icon/th-list/

**Comment by jenstornell** [comment]
Just for completeness, here are some down arrows:
http://fortawesome.github.io/Font-Awesome/icon/angle-down/
http://fortawesome.github.io/Font-Awesome/icon/caret-down/
http://fortawesome.github.io/Font-Awesome/icon/sort-desc/

Another menu option:
http://fortawesome.github.io/Font-Awesome/icon/bars/

**Comment by JimmyRittenborg** [comment]
The arrows might signal some unfolding, and the hamburger menu might be a bit too main menu like - I think that both Google and Apple agrees on using kebab menus for stuff like this ![Kebab menu in iTunes](http://f.cl.ly/items/0P383011271E30013K15/Untitled-2.png)

**Comment by jenstornell** [comment]
@JimmyRittenborg I see your points. I think that would be ok for me. In that case this might be the one?
http://fortawesome.github.io/Font-Awesome/icon/ellipsis-h/

**Comment by bastianallgeier** [comment]
I like the dots a lot. They are subtle but understandable. I just changed it and added it to the dev branch.
