### ISSUE TITLE
Translatable requirements messages

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#639]

**Comment by bastianallgeier** [comment]
What exatly are you refering to? :)

**Comment by distantnative** [comment]
https://github.com/getkirby/panel/blob/develop/app/src/panel.php#L167-L185 ;)

Also maybe we should think of some way to have variables in language strings? -> https://github.com/getkirby/panel/pull/641

**Comment by bastianallgeier** [comment]
We can't really translate those. They kick in before anything else is loaded. The system does not have any idea about the user at that point. It's also just super critical stuff, which in regular cases will only be visible for the developer. More flexible strings with variables are a good idea though.

**Comment by distantnative** [comment]
:+1:

**Comment by distantnative** [comment]
Something in this direction?

```php
function l($key, $replacements = array()) {
  $string = l::get($key);
  if(is_string($replacements)) $replacements = array($replacements);
  foreach($replacements as $placeholder => $replace) {
    $string = str_ireplace('{{' . $placeholder . '}}', $replace, $string);
  }
  return $string;
}
```

**Comment by bastianallgeier** [comment]
Looks good. We should wait with this for the next release though. I prepared everything to move with 2.2 to Transifex, which seems to be a really great solution: https://www.transifex.com/getkirby/panel/ The commit is coming in a minute.

**Comment by lukasbestle** [comment]
Also see my comment [over here](https://github.com/getkirby/panel/pull/641#issuecomment-155712114).
