### ISSUE TITLE
Old filename availabe in panel.file.rename hook

### ISSUE THREAD

**Issue by iksi** [getkirby/panel#642]
It would be nice to have the old name of a file available in the `panel.file.rename` hook. I couldn’t find a method in the `$file` object that currently exposes it.

**Comment by bastianallgeier** [comment]
In 2.2 you will be able to get a copy of the old file object like this: 

```php 
kirby()->hook('panel.file.rename', function($file, $old) {
  // do something with the old file here
  // i.e. $old->filename() 
});
```
