### ISSUE TITLE
TextField counter: higher count after invalid update attempt

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#645]
When I load a  page that has a textarea field with a higher character count than the validate max setting, it looks like this:
<img width="129" alt="screen shot 2015-11-10 at 17 16 48" src="https://cloud.githubusercontent.com/assets/3788865/11067884/0bb012d0-87cf-11e5-8a20-3c5339031ec9.png">

After trying to save:
<img width="317" alt="screen shot 2015-11-10 at 17 16 52" src="https://cloud.githubusercontent.com/assets/3788865/11067889/1031b0e8-87cf-11e5-9105-a118da346dc7.png">

So 10 more characters out of nowhere. Tiny bug, but maybe we'll figure this out.

**Comment by bastianallgeier** [comment]
I think it makes sense, or am I missing something?

**Comment by distantnative** [comment]
502 before hitting Save -> 512 after. Why?

**Comment by bastianallgeier** [comment]
Ahhh, that's what I've been missing :) Let me check.

**Comment by bastianallgeier** [comment]
Fixed it. Js string length seems to count a bit differently than PHP :) A simple keyup trigger fixed it.
