### ISSUE TITLE
Fieldtype "tags", Encoding of html-Entities

### ISSUE THREAD

**Issue by hans-mayerhuber** [getkirby/panel#648]
When using special characters as tag-names (e.g. "<") the display of the tag is broken because the tag-name isn't "escaped". This happens in Line 135 of tags.js.

Possible solution would be a function converting these special characters:

~~~~js
function htmlEntities(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
~~~~

And changing line 135 to:

~~~~js
var b = $('<button class="tag-label" type="button">' + htmlEntities(tag) + '</button>');
~~~~

**Comment by bastianallgeier** [comment]
I just fixed it on the develop branch. Fortunately jQuery has a better way to handle this with the .text() method.
