### ISSUE TITLE
custom panel language on config broke panel

### ISSUE THREAD

**Issue by plantalabs** [getkirby/panel#655]
when custom panel language is put on site config it broke panel, because language is missing.

i guess it is for the languages folders in panel folder has  odd names. 
 
like es_419 of pt_br instead of es_la or pt_br when i rename it the panel work again. also this problem  is it broken plugin that use panel->language function.

sorry my english. thanks for kirby

**Comment by bastianallgeier** [comment]
I just fixed this by aliasing old language codes. You can now keep the old ones and they will link to the new codes.
