### ISSUE TITLE
fieldname »content« not allowed

### ISSUE THREAD

**Issue by jensfranke** [getkirby/panel#660]
If I use »content« as fieldname in the blueprint it will breaks during the save-process and after reload the panel is broken for this entry.

```
Catchable fatal error: Object of class Content could not be converted to string in …panel/models/page/changes.php on line 70
```

**Comment by distantnative** [comment]
Yea, I think `content` shouldn't be usable as fieldname – as all other `$page` methods cause that would be conflicting. But there should probably a better error catch/warning.

**Comment by jensfranke** [comment]
Most of the time ```content``` is to unspecific and so a better error handling would be fine.

**Comment by bastianallgeier** [comment]
I just added a new version to the develop branch, which handles this far better :)
