### ISSUE TITLE
Panel 2.2 - Upload overlay appears when a link is dragged.

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#664]
When you drag any link in the interface, for example the Preview link, the upload overlay appears. Not a big issue since there is no reason to drag links (apart from files in the sidebar), but when you do it by accident it looks weird :)

**Comment by JimmyRittenborg** [comment]
It also happens if want to quickly select a text snippet in a textarea and move it around by dragging, which I actually does sometimes when I'm reordering images in gallery kirbytag
```markdown
(gallery: cats.jpg, cats-with-shoes.jpg, cats-with-hats.jpg)
```

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
