### ISSUE TITLE
Kirby 2.2: `GLOB_BRACE` not supported everywhere

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#665]
See [this topic in the forum](https://forum.getkirby.com/t/panel-error-caused-by-glob-brace-in-kirby2-2/2550?u=lukasbestle).

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch. Also requires the develop branch version of the toolkit.

**Comment by p-h-i-l** [comment]
thank you :+1:
