### ISSUE TITLE
In URL fields, use the icon on the right as link

### ISSUE THREAD

**Issue by anselmh** [getkirby/panel#669]
In URL fields in the panel there is a link symbol on the right that’s acting as an indicator. I’d love to have that acting as a dynamic link to the URL given as well (you could use JS if URL changed on the fly). It should open in a new tab.

![screen shot 2015-11-20 at 08 50 05](https://cloud.githubusercontent.com/assets/399345/11294452/de9a7898-8f63-11e5-81ad-a374d88130da.png)

**Comment by bastianallgeier** [comment]
That's one of those ideas you feel stupid about not having it before :)

**Comment by bastianallgeier** [comment]
I just uploaded a feature branch for this which already contains a working version. https://github.com/getkirby/panel/tree/feature/Url-Field-Improvement 

This will be added to 2.3

**Comment by anselmh** [comment]
<3
