### ISSUE TITLE
Invalid yaml format

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#670]
First I spotted that Sublime Text did not color code the `alphanum`.

![image](https://cloud.githubusercontent.com/assets/927011/11300073/40e4ab68-8f8c-11e5-9706-c8e032f0502f.png)

Then I tried it in http://www.yamllint.com/ and got an error.

![image](https://cloud.githubusercontent.com/assets/927011/11300066/366f0444-8f8c-11e5-89bf-ca3a9395b553.png)

***(<unknown>): could not find expected ':' while scanning a simple key at line 47 column 7***

It seems like the yaml is not valid. To fix it maybe do something like this? Add a key to it?

    type: alphanum

As a sidenote, the blueprint work but is invalid by validators.

**Comment by bastianallgeier** [comment]
it should probably be: 

```
validate: 
  min: 4
  max: 140
  - alphanum
```

**Comment by jenstornell** [comment]
I tried it and it seems to work. Then it's just a docs issue:

http://getkirby.com/docs/panel/blueprints/form-fields#validation

**Comment by lukasbestle** [comment]
I fixed it in the docs.

**Comment by bastianallgeier** [comment]
:+1:
