### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby/panel#671]
I really really like the ⌘+s for saving in the panel, I was constantly hitting it when jumping between Sublime Text.

But what about ⌘+b, ⌘+i and maybe ⌘+z (if ever existed), they have now been moved to [ctrl]+b, [ctrl]+b - was that on purpose?

**Comment by bastianallgeier** [comment]
I've unintentionally overwritten the old shortcuts. They are now both available at the same time.
