### ISSUE TITLE
Smiley face appears after editing structure field, but page hasn't been saved

### ISSUE THREAD

**Issue by samnabi** [getkirby/panel#675]
The smiley face in the corner is a good UX detail, but it may give a false sense of security when the data hasn't yet been saved. This is what happens when I save a structure field:

![screen shot 2015-11-21 at 15 52 49](https://cloud.githubusercontent.com/assets/1731536/11320501/fc97a186-9067-11e5-96f9-13bc013a2ce9.png)

The smiley seems to be a confirmation, but actually nothing has been saved yet.

**Comment by puckey** [comment]
Was just about to post the same issue - plus one from me here..

**Comment by bastianallgeier** [comment]
You are completely right with this! I will remove it in the next release.

**Comment by bastianallgeier** [comment]
Just uploaded a fix for this to the develop branch.
