### ISSUE TITLE
Field initialization runs when canceling a modal

### ISSUE THREAD

**Issue by JonasDoebertin** [getkirby/panel#680]
Have a look at this issue: https://github.com/JonasDoebertin/kirby-visual-markdown/issues/61

It seems the panel reruns the field initialization callback when canceling a modal (= the panel page isn't reloaded). This leads to double initializations of some fields. I'll try to find a workaround for Visual Markdown, but I think this should be fixed here, as well.

**Comment by bastianallgeier** [comment]
This is actually needed. I unbind all content events before the modal gets loaded in order to avoid conflicts. The correct way of initializing your plugin would include a check if it already has been initialized. I do that with my stuff by adding a data attribute after initialization.

**Comment by bastianallgeier** [comment]
Ups, I just saw that you already did that :) Awesome!!

**Comment by JonasDoebertin** [comment]
@bastianallgeier Yeah, that's how I solved it as well. Thanks for the explanation though!
