### ISSUE TITLE
Renaming of folder sorting logik

### ISSUE THREAD

**Issue by larshaendler** [getkirby/panel#681]
Since version 2.2 the panel renames page folders automatically for automatic sorting with [1,2, ...]-foldername/ upon saving. In prior versions folder names were not touched by the panel. 

My page folders were named with date and page name (19930201-PlayList_Feb_01_1993, 19931104-PlayList_Nov_04_1993). So new pages containing play lists could easily be inserted between existing pages. 

Since 2.2: As soon as one of those pages is updated in the panel every subfolder containing a page gets renamed to (1-PlayList_Feb_01_1993, 33-PlayList_Nov_04_1993). I could easily restore all folders from backups but it is annoying nonetheless.

Is there config variable to stop the panel from rewriting folder names alltogether? Otherwise the panel cannot be used for user defined ordering.

**Comment by bastianallgeier** [comment]
What you should do is to switch to date-based sorting: http://getkirby.com/docs/panel/blueprints/subpages-settings#numbering-of-subpages and add a date field to your files, which can be used to generate the correct date for the numbers. This will make sure that the panel will never rename the dates to something unusable and it will also speed up sorting.

**Comment by texnixe** [comment]
That's true. And if you want to use the date in the url you could use a route to achieve that, similar to Wordpress-like URLs: http://getkirby.com/docs/advanced/routing#simulating-wordpress-urls
