### ISSUE TITLE
Blog Pagination 2.2.2

### ISSUE THREAD

**Issue by k06** [getkirby/panel#689]
Hello, 

I've some trouble with blog pagination and Kirby 2.2.2.
I use exactly this [blog code pagination](http://getkirby.com/docs/solutions/blog/pagination).
It works perfectly with 2.1 version but navigation does not work anymore with Kirby 2.2.2.
I can go to older Post, but when try to return to newer post using pagination it does not work and have this error:
`Fatal error: Call to a member function isErrorPage() on a non-object in A:\JOB\Prog\UwAmp\www\metvKirby\kirby\kirby.php on line 366`

going to blog page 2 gives url: **site/collections/page;2** instead of **site/collections/page:2** but shows page correctly
and when try to return to newers posts it gives url: **site/collections/page:2** with fatal error

Thank you for your help,

**Comment by afbora** [comment]
Have you an error page? I got that error when i delete `/content/error/` page by mistake.

**Comment by k06** [comment]
Hi, 
That' true I did not had yet error page :( 
I just add one, but problem is the same without error message, it just redirects to error page.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
