### ISSUE TITLE
Option to change template

### ISSUE THREAD

**Issue by DanielRivers** [getkirby/panel#69]
I have a usecase where I want to change the template being used.

Effectively the site I am putting together features events, after the event I want to switch the event to use a different 'post event' template.  Would be REALLY useful to be able to change the template from the panel instead of me having to manually edit the file name.

Thanks

**Comment by distantnative** [comment]
As this is not possible atm, at least for your case a workaround could be to actually check in the event template first if the event is still in the future or already in the past. And depending on that displaying the different things you wanna do in the one event template (no need to change the template anymore).

Might not be ideal, but at least for the moment.

**Comment by distantnative** [comment]
The ability to change a page's template/blueprint has been added to the development branch and will be part of the next release.
