### ISSUE TITLE
"Your last updates" in panel

### ISSUE THREAD

**Issue by A-Monkey** [getkirby/panel#691]
Are not updating, ever, for me it just shows:

" Your last modified pages will be displayed here to make it easy to find them again later. "

**Comment by CalebGrove** [comment]
I can *partially* confirm this. On a brand-new website, which started with Kirby 2.2.2, "Your last updates" doesn't work. However, on an older website, which has been updated to 2.2.2, it works as expected.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch. Sorry for the bug!
