### ISSUE TITLE
Disable changing of URL per blueprint (and also showing/hiding pages)

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#693]
As per this forum post https://forum.getkirby.com/t/disable-change-url-in-blueprint/2715/1

**Comment by jbeyerstedt** [comment]
I just had a case, where I wished, that there is an option for keeping certain pages hidden. This option would be nice.

**Comment by bastianallgeier** [comment]
:+1:

**Comment by gerardkd** [comment]
:+1;

**Comment by Moorst** [comment]
Would definitely be useful to have this as an option as hiding the links in CSS is (as far as I can see) impossible:

- There's no way of targeting specific templates 
- There's no way of isolating the "Change URL" list item.

**Comment by bastianallgeier** [comment]
I just committed the following changes: https://github.com/getkirby/panel/commit/0072302dc4ca291995a210e107af205186e7ee0a

This will make it possible to control each and every feature for pages from blueprints: 

Example: 

```
options:
  preview: false
  url: false
  template: false
  delete: true
```

**Comment by texnixe** [comment]
Yes!
