### ISSUE TITLE
More field validations feature request

### ISSUE THREAD

**Issue by afbora** [getkirby/panel#694]
`required` rule is already exists. Would be more likes that:

 1. matches[form_item]
 2. regex_match[/regex/]
 3. is_unique
 4. min_length[3]
 5. max_length[12]
 6. exact_length[8]
 7. greater_than[8]
 8. less_than[8]
 9. alpha
 10. alpha_numeric
 11. alpha_numeric_spaces
 12. alpha_dash
 13. numeric
 14. integer
 15. decimal

etc..

### For examle:

````php
custom:
	label: Custom Field
	type:  text
	rule: regex_match[/^custom-([a-z]+)/]
````

**Comment by PaulMorel** [comment]
Already possible with the `validate` rule.

http://getkirby.com/docs/panel/blueprints/form-fields#validation
http://getkirby.com/docs/cheatsheet/#validators

**Comment by afbora** [comment]
@PaulMorel In fact i was knowing validations and remembered when you said :) i forgot that. Thanks..
