### ISSUE TITLE
User profile fields reading/saving performance

### ISSUE THREAD

**Issue by afbora** [getkirby/panel#698]
Pages reading/saving time is good. Click and read/write in a second. But users that having custom fields reading/saving time is so slow.

### For examples i tried: 

> Click a page to edit: < 1 second
> Click button to save page: < 1 second

**Users that no custom fields**

> Click a user to edit: < 1 second
> Click button to save user: < 1 second

**Users that having custom fields**

> Click a user to edit: > 4 seconds
> Click button to save user: > 5 seconds

**Comment by bastianallgeier** [comment]
Hm, I can't really reproduce those numbers here. I've got a bunch of custom fields in my test environment and it doesn't affect performance at all. Can you give me some more informations about the fields you've setup? Maybe the issue is in the fields.

**Comment by afbora** [comment]
When i remove 3 select fields that country (1), province(81) and district(1000) with query, returned to normal :)

Sorry at first from Kirby because of i said slow about it and from @bastianallgeier :smile: 

Kirby, you are my favorite! :heart:

**Comment by bastianallgeier** [comment]
Ah, yeah, rendering 1000 options in a select field might take a bit :)
