### ISSUE TITLE
Ignore `help` blueprint option for title fields

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#700]
See [this topic in the forum](https://forum.getkirby.com/t/panel-show-the-translation-of-the-title-help-from-a-blueprint/2824?u=lukasbestle).

**Comment by texnixe** [comment]
When I think about this, wouldn't that be even more irritating for the user, if the option failed silently? Maybe a more explicit error message, which tells the user that he/she cannot use the help option with the title field, would make more sense? Then again, I doubt that many people would try to use help text for a title field ...

**Comment by lukasbestle** [comment]
Hm, yes, that's true. But the nondescript error that's currently there definitely has to go away.

**Comment by distantnative** [comment]
This is a bug. Cause the `help` option does work if not translated. So I wouldn't ignore or remove it, simply fix it. I won't use it, but some developers might want to give some additional information for a title (SEO tips... i don't know).
