### ISSUE TITLE
Root page template [feature request]

### ISSUE THREAD

**Issue by afbora** [getkirby/panel#711]
I have 20 blueprints/page templates. When i try to add new page from root, listing all blueprints.

Following template` parameter is only solution but i think this should be more useful and dynamic.

*site/blueprints/site.php*

    pages:
		template:
			- about
			- contact
			- services
			- default

**Expected solution on creating new page template:**

*site/blueprints/newpage.php*

    pages:
        root: true

Now listing pages only selected `template:` and dynamicly having `root: true` parameter.

**Comment by distantnative** [comment]
For that, when adding a new page the panel would not just need to look into its own blueprint to see what templates are allowed/available (as it does now), but it would have to go through all blueprints to see which one has set `root: true`. I'd imagine that as a huge slowdown.

**Comment by afbora** [comment]
I dont agree with you about huge slowdown. Panel will check available pages only click add page. I think panel will be made more dynamic with this feature.

**Comment by distantnative** [comment]
Ture, it's a matter of perspective. But I'd say adding a page is a quite common action. And the panel would need to open and read not just 1 file anymore, but 20 – and that's just for your example. Moreover, imho it introduces another layer of complexity that I don't see the benefits living up to.

**Comment by afbora** [comment]
Another great perspective :smile: 

Absolutely right! Little slowdown is correct but huge not in my opinion :sunglasses: My purpose was that appending more dynamic system.

We can rethink about this issue or close anytime.
