### ISSUE TITLE
Permanent panel logout on https connection on Uberspace

### ISSUE THREAD

**Issue by Designscheu** [getkirby/panel#713]
Running Kirby on uberspace encrypted with lets encrypt as well as the uberspace wildcard certificate is causing a permanent logout. Sometimes directly redirected to the login again sometimes after a few clicks in the panel. Uberspace support is denying probability that this is caused by their infrastructure or should be solved by them. Everything is working fine over http.
Here is the respective thread in the kirby forum:
https://forum.getkirby.com/t/permanent-panel-logout-on-https-connection-on-uberspace/2917

**Comment by lukasbestle** [comment]
Turns out this was an issue at Uberspace which is now fixed. \o/
