### ISSUE TITLE
Form class never gets passed the $parent param for structure fields

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#715]
See [this topic in the forum](https://forum.getkirby.com/t/how-to-know-if-the-field-is-used-in-a-structure-field/2935?u=lukasbestle).

It looks like the `$form->parentField` attribute never gets set because the Form class never actually gets passed the `$parent` param.

**Comment by distantnative** [comment]
This got fixed on the develop branch and will be included in the next release.
