### ISSUE TITLE
Blueprint option to hide the "Add page" button only

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#719]
See [this topic in the forum](https://forum.getkirby.com/t/panel-existing-subpages-are-not-displayed/2945?u=lukasbestle).

Suggestion: A new blueprint option like `pages: false` that displays all existing pages and only hides the "Add Page" button.

**Comment by distantnative** [comment]
Just wondering, maybe a hack/fix would be to set `max: 1` once the wanted pages have been created. Should hide the add button

**Comment by bastianallgeier** [comment]
So far I always went for Nico's hack. I feel like there are already a lot of options available for blueprints and I'm a bit sceptical with adding new ones. But maybe it makes sense.

**Comment by lukasbestle** [comment]
Definitely true.

**Comment by texnixe** [comment]
I have a feeling that the scenario described in the forum topic is rather an edge case. If it can be handled with the hack, that should be sufficient.
