### ISSUE TITLE
Change of slug in panel not persistent when numbering set to alphabetical

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#725]
See [this forum thread](https://forum.getkirby.com/t/bug-custom-url-appendix-is-undone-by-save-function-in-panel/2834/7).

This only seems to happen if the alphabetical numbering setting is put after the template setting, i.e. with the following setting:

```
pages:
  template: project
  num: zero
```

the bug appears. While everything works alright, if the numbering is set before like this:

```
pages:
  num: zero
  template: project
```

**Comment by lukasbestle** [comment]
Also see [this topic](https://forum.getkirby.com/t/unwanted-url-change-via-panel/3107?u=lukasbestle).

**Comment by lukasbestle** [comment]
It seems like reordering the two options does not fully fix this issue. See [this post](https://forum.getkirby.com/t/unwanted-url-change-via-panel/3107/3?u=lukasbestle).

**Comment by distantnative** [comment]
Looks like this might not be a bug but a feature? https://github.com/getkirby/panel/blob/master/app/src/panel/models/page.php#L393-L397

Still need to figure out, why.

**Comment by texnixe** [comment]
Hm, right, so it is assumed that you want to sort by title, not by slug? That probably makes sense. However, that does not explain why the behavior differs when changing the order of the settings.

**Comment by distantnative** [comment]
Yea, that the behaviour differs based on the order of blueprint settings is weird.
And it still is a bug, even if we agree that it should be based on the title. Cause then we should completely hide changing the slug and so on, if it gets updated automatically anyways.

**Comment by distantnative** [comment]
I'm also not sure if enforcing updating the slug from the title is a good idea since `num: zero` is only described as "Alphabetical numbering" in the docs. I would assume alphabetical numbering of the slug. And that I could still edit the slug.

**Comment by bastianallgeier** [comment]
I added this with the idea that you probably want the uid to be updated when the title changes so the alpahbetical ordering is still correct. But that's too intrusive. I changed it back already.
