### ISSUE TITLE
Missing label in blueprint for structure causes error in panel

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/panel#733]
I forgot to add the label in the blueprint for a structure field and got the following error in the panel:

```Fatal error: Method StructureField::__toString() must not throw an exception in /.../kirby/toolkit/lib/brick.php on line 0```

Thought this might be of interest. :)

OSX / Mamp / PHP 7.0.0

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
