### ISSUE TITLE
Dangerous order in Create account form makes passwords visible

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#735]
Today I create a new Kirby installation for my next project (already bought licenses).

The first time the panel is set up we need to setup our admin account.

**Now it's in this order:**

1. **Username**
1. Email
1. **Password**

I my case I filled in the username, tabbed to the next field and filled in the password. Big oops there. The password is now fully visible in the email field. Might not always be a big deal but if I have someone behind my back I just gave away my password.

**A better field order would be:**

1. **Username**
1. **Password**
1. Email

If we use the suggested field order it would also be more in line with what we do when we are logging in (Username then password).

**Screenshot of the dangerous field order**

![image](https://cloud.githubusercontent.com/assets/927011/12507583/ee29e02c-c0f6-11e5-8638-0a85118a23ff.png)

**Comment by bastianallgeier** [comment]
I never really thought about it, but I think you are right. I just changed it on the develop branch.
