### ISSUE TITLE
error message when try to change filename

### ISSUE THREAD

**Issue by strukturart** [getkirby/panel#737]
Warning: simplexml_load_string(): Entity: line 18: parser warning : xmlns: URI &ns_sfw; is not absolute in /home/www/web404/html/dev1/kirby/toolkit/lib/media.php on line 437

Warning: simplexml_load_string(): <sfw xmlns="&ns_sfw;"> in /home/www/web404/html/dev1/kirby/toolkit/lib/media.php on line 437

Warning: simplexml_load_string(): ^ in /home/www/web404/html/dev1/kirby/toolkit/lib/media.php on line 437

**Comment by bastianallgeier** [comment]
Would it be possible to get the file, which creates the issue, so I can make some tests? bastian@getkirby.com

**Comment by bastianallgeier** [comment]
I'm closing this because I can't debug it without the file.
