### ISSUE TITLE
Escape field separator "----"

### ISSUE THREAD

**Issue by mzur** [getkirby/panel#738]
When you insert the field separator `----`, say, in a text area in the panel it may break the content of the field. Take a look at this example:

before:
```
Title: Home
----
Text: Hello
```

after:
```
Title: Home
----
Text:
----
Hello
```

Inserting a field separator like this should be disallowed by the panel.

**Comment by bastianallgeier** [comment]
That's weird. I actually have escaping in place for this. Which version of Kirby and the panel do you use?

**Comment by mzur** [comment]
Kirby and the panel both have version 2.2.3.

This happens only if the `----` is added at the _top_ of the text area. If there is text first, it is properly escaped.

**Comment by bastianallgeier** [comment]
Ahh, that helped a lot to reproduce it. I just fixed it on the develop branch.
