### ISSUE TITLE
"Open link in new tab" button for non-coders

### ISSUE THREAD

**Issue by lukehatfield** [getkirby/panel#739]
I had a client today ask for a "popup: true" checkbox in the kirbytext link builder button. That way they don't have to go into the code and remember how to make some pages open in a new tab.

Re: https://forum.getkirby.com/t/open-link-in-new-tab-button-for-non-coders/3151/3

Thanks!!!

**Comment by distantnative** [comment]
What would be inserted for the different styles of markdown/kirbytext to open the link in a new tab?

```
<url>

(link: url text: text)

[text](url)
```

**Comment by distantnative** [comment]
Just for context, Bastian's comment on this issue from the forum
> I'm very critical with this feature as a default. target=_blank is something you should use very carefully and rather convince clients not to use it in the first place. I know from my own clients that this wish comes up over and over again.

> In most cases I prefer to solve this with javascript for all external links if clients really want that.

> But if you really need the button, copy the textarea field from the panel source and create your own custom textarea field. You can even keep the textarea name for it. Since 2.2.3 fields now have their own ways of adding modals, so you can modify the buttons as well as the modal and add the additional form field.

**Comment by lukehatfield** [comment]
Thanks distantnative. Now I'm thinking the js route Bastian suggested may be the best approach for clients or situations that demand this.
