### ISSUE TITLE
Load page models in Panel

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#740]
See [this post in the forum](https://forum.getkirby.com/t/page-models-in-panel-field-select/3155?u=lukasbestle).

This is difficult as the Panel would need to ignore the models when loading the form (for example by using `content()`). The question is how to integrate models so that they actually make sense in the Panel.

**Comment by bastianallgeier** [comment]
I think this is too risky. It would lead to so many possible issues.

**Comment by tillprochaska** [comment]
I can totally understand that there might be sighteffects loading custom page models by default, but it would be really helpful if there was an easy way to create a new instance of a page’s page model on demand in the case you need to access its methods.

**Comment by lukasbestle** [comment]
See https://github.com/getkirby/kirby/issues/478.
