### ISSUE TITLE
Missing Page Show Hook

### ISSUE THREAD

**Issue by moritzz** [getkirby/panel#741]
### Introduction

Even though Panel provides a hook when hiding a page, there is none when showing a page. Assuming that many editors might use hidden pages for drafting new pages and collaboration with copy-editors and later switch them visible to publish, having no easy way for Panel instances to act on page show seams a major miss.

### Feature Request

Introduce a `panel.page.show` hook for Panel instances to act after a page's visibly is switched on. E.g. updating a published data automatically.

**Comment by texnixe** [comment]
Should be covered by the `panel.page.sort` hook.

**Comment by moritzz** [comment]
Oh! Wow! Thanks a lot for the hint, @texnixe. Is there a detailed documentation in the cheat sheet on what actions triggers which hook?

**Comment by texnixe** [comment]
No, there is only the table of hooks, and most of them seem to be kind of self-explanatory but the sorting hook definitely isn't. I think we can add another column to the list with a short explanation.

**Comment by moritzz** [comment]
Oh, a 'table'? What's its URL? And thanks again! Hooks really made iA.net's day.

**Comment by texnixe** [comment]
I was referring to this [list of hooks](https://getkirby.com/docs/panel/developers/hooks), which you probably know. We could add a new column "description".
