### ISSUE TITLE
Blueprints and templates

### ISSUE THREAD

**Issue by marcwieland95** [getkirby/panel#750]
Hi,
I'm using Kirby for the first time and found some limitations I absolutely don't like:

1. I'm a little confused by the term "Template" in the Panel, while creating a new page. This term references to the blueprint and has absolutely nothing to do with the template folder.
I like the blueprints a lot and it's very easy to create custom fields - well done.

2. The templates feels very static. The page name has to match the template name, which makes everything unflexible. I think it would be nice, if there's a possible in addition to the existing static detection to select a template in the backend.
As a workaround I can create a custom field with a dropdown and list my templates. Later I can read the value out and use it properly. But the downside is that I need some addition logic behind and also have to create this template-field in every blueprint (don't repeat yourself).

3. This point is still discussed here (#264). The ability to change the template afterwards.

4. Is there a possibility to read the out the chosen blueprint on the front-end (kind like `$page->template()`)?
My advice would be: Match the blueprint with the template.

Maybe I'm wrong in some points or doesn't understand the philosophy behind a feature correctly. If this is true, help me ;-)

**Comment by lukasbestle** [comment]
> I'm a little confused by the term "Template" in the Panel, while creating a new page.

A blueprint is just another representation of a template. The blueprint defines which fields are required for the template, which defines how they are displayed.

> I think it would be nice, if there's a possible in addition to the existing static detection to select a template in the backend

Well, that's exactly what you wrote above. This is what you do when creating a new page. Not the page name matters, but the name of the text file.

> The ability to change the template afterwards.

Well, that's difficult. There has been a [long discussion about this in the forum](https://forum.getkirby.com/t/panel-change-the-template/1226?u=lukasbestle).

> Is there a possibility to read the out the chosen blueprint on the front-end (kind like $page->template())?

Exactly like that actually. If a template with that name does not exist, this value will default to the `default` template though. You can use `$page->intendedTemplate()` to get the actual chosen blueprint.

**Comment by distantnative** [comment]
The way Kirby works is:

page's content file name (e.g. about.txt, not the page's title) --- tries to match a template --> about.php (if not there, fall back to default.php template)

Same goes for the panel. When you try to edit a page in the panel, it will try to resolve:

page's content file name (e.g. about.txt) -----> yml (if not there, fall back to default.yml blueprint)

So if you creat a new page, panel will ask you which blueprint this new page should be based on. Which is asking "what set of fields should I display". The blueprint you choose will then define the page content's file name which then tells Kirby what template should be chosen.

Inside the template `$page->template()` will get you what template actually was choosen, while `$page->intendedTemplate()` will tell you what blueprint was chosen / what's the page content file name (e.g. `about` but since there is not `about.php` template, the `default.php` was chosen instead).

**Comment by texnixe** [comment]
> But the downside is that I need some addition logic behind and also have to create this template-field in every blueprint (don't repeat yourself).

You could use [Blueprint snippets](https://forum.getkirby.com/t/tutorial-global-field-definitions-aka-blueprint-snippets/2820) to only define the field once and then add it to each blueprint.

**Comment by marcwieland95** [comment]
Thanks a lot. Now it's clear.
I didn't know that the blueprints has also an impact on how the page (filename) is created.

@lukasbestle I see now why it's tricky to change the template on the fly :smile:

@texnixe Blueprint snippets worked fine. Exactly what I need.

One more question: There's a [hidden field](https://getkirby.com/docs/cheatsheet/panel-fields/hidden) in the blueprint available. How do you use this? For me, it's not clearly explained in the doc.

To come back to the template field example above. I've got a contact page, which has a contact blueprint. Is it possible to store a fixed value to the hidden field?

Something like this:
```
fields:
  template: 
    value: contact
    type: hidden
```

**Comment by lukasbestle** [comment]
The `hidden` field is a field that keeps its current value. So you can't change it via the Panel and also can't set a value in the blueprint.

The idea is to edit the content text file manually and add the content there. It will stay that value forever.
