### ISSUE TITLE
Select with "pages" query does not work in site settings

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/panel#768]
Even though the documentation lists "pages" as an option to "list of options with all pages of the site", it's not possible to use this in the site settings.

https://getkirby.com/docs/cheatsheet/panel-fields/select

It will result in an empty select field.

**Comment by texnixe** [comment]
Hm, I cannot reproduce this. This works for in Kirby 2.2.3:

```text
select:
    label: Select a page
    type: select
    options: pages
```

**Comment by medienbaecker** [comment]
Does a query work in your installation too?

      seite:
        label:   Zu verlinkende Seite
        type:    select
        options: query
        query:
          fetch: pages
          value: '{{uri}}'
          text: {{title}} ({{uri}})

**Comment by texnixe** [comment]
No, that does not work.

**Comment by medienbaecker** [comment]
Alright. Exactly this works on other pages though and I use this as a link selector.

One workaround I just found out is adding "page: /" to the query. While "pages" should be global, the site settings seem to need a specific page for the query.

**Comment by distantnative** [comment]
This got fixed on the develop branch and will be included in the next release.
