### ISSUE TITLE
Special Characters on URL

### ISSUE THREAD

**Issue by afbora** [getkirby/panel#773]
In turkish language, some chars should be like that:

`ö` => `o`
`ı` => `i`

I solved this issue with following on config.php

``` php
str::$ascii = a::merge(str::$ascii, array(
  '/Ç/' => 'C',
  '/ç/' => 'c',
  '/Ğ/' => 'G',
  '/ğ/' => 'g',
  '/İ/' => 'I',
  '/ı/' => 'i',
  '/Ö/' => 'O',
  '/ö/' => 'o',
  '/Ş/' => 'S',
  '/ş/' => 's',
  '/Ü/' => 'U',
  '/ü/' => 'u'
));
```

It was working perfect but doest working properly anymore on v2.2.3.

Second problem is that replacing only once char. For ex:

**Current:**

`üzümlük` => `uzmlk`
`özgürlük` => `ozgurlk`

**Should be:**

`üzümlük` => `uzumluk`
`özgürlük` => `ozgurluk`

So each speacial char replaced only first one.

**Comment by distantnative** [comment]
I would assume that this is related to #724

**Comment by afbora** [comment]
on 2.4 milestone?

**Comment by jenstornell** [comment]
I don't know if it helps but I have a plugin for everything...

https://github.com/jenstornell/kirby-slug-modifier

**Comment by afbora** [comment]
2.4.1 milestone pls

**Comment by bastianallgeier** [comment]
You can now use your trick to rematch special chars to slug translations in the config again and the repeating issue has been solved as well. I think we need to start providing language based character maps in a future release, so everyone can contribute them for their own language and get the best results.
