### ISSUE TITLE
Chrome: Page icons not displayed

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#784]
In Chrome I cannot see the page icons in the history

<img width="777" alt="screen shot 2016-02-26 at 13 37 43" src="https://cloud.githubusercontent.com/assets/3788865/13352560/5bdd8468-dc8e-11e5-93bb-dd1844d7517b.png">

**Comment by bastianallgeier** [comment]
chrome has this horrible bug with css columns :( I already fixed it but it's coming back in various forms. Super frustrating.
