### ISSUE TITLE
Make it possible to edit file metadata

### ISSUE THREAD

**Issue by ponychicken** [getkirby/panel#785]
In [the docs](https://getkirby.com/docs/content/media) it is described how to add captions or descriptions or other metadata to files (image.png.txt). 

It would be great if these could be edited and created using the web interface

**Comment by texnixe** [comment]
Yes, this is already possible.

**Comment by ponychicken** [comment]
Could you let me know where? I coulnd't find it

**Comment by texnixe** [comment]
https://getkirby.com/docs/panel/blueprints/file-settings

**Comment by lukasbestle** [comment]
Once you defined your file fields, you can edit the fields in the file detail view (click on the filename in the sidebar).
