### ISSUE TITLE
Images in panel ‘flash’ for a bit in Safari

### ISSUE THREAD

**Issue by iksi** [getkirby/panel#788]
In Safari 9.0.3. images in the files edit page flash shortly when loading: the become visible, then go invisible again to become visible. The same happens when sorting images: after dropping an image in it’s new position all of the thumbnails become in visible to become visible again after a bit. In the screenshot I’m using a custom panel stylesheet to set 1px red border around the image. You can see that just after sorting it has neither a height or a width and you can only see it’s red border. After a couple of seconds the image reappears.

![screen shot 2016-02-29 at 15 02 48](https://cloud.githubusercontent.com/assets/1090876/13396557/886b2576-def5-11e5-86df-6208d1a49d34.png)

Contents of custom panel stylesheet:

```CSS
.file-preview img  {
    border: 1px solid red;
}
```

**Comment by iksi** [comment]
Forgot to mention that it’s on localhost and the used versions are:
Toolkit version: 2.2.3, Kirby version: 2.2.3, Panel version: 2.2.3

It seems that after changing the order of the images Safari reloads all of the images:

![01](https://cloud.githubusercontent.com/assets/1090876/13424169/37a619fc-df9f-11e5-94a6-f1076b943a6b.jpg)

![02](https://cloud.githubusercontent.com/assets/1090876/13424168/377b8cfa-df9f-11e5-94d8-e4be3cb7c208.jpg)

**Comment by texnixe** [comment]
Yes, I can confirm this effect, seems to be present only in Safari, does not happen in Chrome or Firefox.

**Comment by JimmyRittenborg** [comment]
@texnixe isn't it just because the images doesn't gets resized anymore, at least i'm having this issue too in Chrome.

**Comment by bastianallgeier** [comment]
We fixed this on the develop branch for the next release.
