### ISSUE TITLE
Panel files slower compared to v2.1.1.

### ISSUE THREAD

**Issue by iksi** [getkirby/panel#789]
(This is somewhat related to https://github.com/getkirby/panel/issues/611) I’m comparing panel versions 2.1.1 to 2.2.3 (both clean install plainkits) with a page that contains a lot of sortable files (212). I know I should probably split this up in smaller batches across pages but I can’t help notice the difference in performance between the panel version 2.1.1 and 2.2.3 (testing them using their equivalent versions of the core and toolkit). Loading the page with files (thumbnails are already generated) takes about 305 milliseconds on panel 2.1.1 and 14.01 seconds on panel 2.2.3 (both on localhost, php 5.6.18). The same goes for sorting an image: 2.1.1 is way faster than 2.2.3.

Version 2.1.1:

![panelv211](https://cloud.githubusercontent.com/assets/1090876/13425454/19efd292-dfa7-11e5-9d26-31a0073788ba.jpg)

Version 2.2.3:

![panelv223](https://cloud.githubusercontent.com/assets/1090876/13425455/1a2fcb0e-dfa7-11e5-8365-4bf0c8afafca.jpg)

Related to my other issue (https://github.com/getkirby/panel/issues/788) Safari also seems to load the images twice.

I’ve uploaded my test setup with both kirby installations to https://www.iksi.cc/files/test.zip

**Comment by distantnative** [comment]
Can confirm this issue (also seems to me as if the files are loaded twice and all files are only shown once all files have been loaded). And yes, it also looks to me as this is essentially tied to #788.

Trying to investigate and see if I can spot the cause.

**Comment by JimmyRittenborg** [comment]
It seems it's because the images doesn't gets resized like before where they were resized and cropped.

**Comment by distantnative** [comment]
They still get resized/cropped but through a route. Just opened a PR (https://github.com/getkirby/panel/pull/800) which - I believe - fixes the issue.

**Comment by JimmyRittenborg** [comment]
@distantnative oh i see, thanks :+1:

**Comment by iksi** [comment]
:+1:

**Comment by bastianallgeier** [comment]
We fixed this in the meantime on the develop branch.
