### ISSUE TITLE
Custom icons not showing in "Your latest updates" section

### ISSUE THREAD

**Issue by longbored** [getkirby/panel#793]
If a custom (Font Awesome) icon is given to a page (via the blueprint), it doesn't show that icon in the "Your latest updates" area in the panel's home. It just shows the default page icon.

**Comment by distantnative** [comment]
This has been already fixed on the `develop` branch and will be included in the next release (see https://github.com/getkirby/panel/issues/729 and https://github.com/getkirby/panel/commit/cff939343611c30183bfe70e281019d25bb5a3cc).
