### ISSUE TITLE
error of "The page is not writable" in panel

### ISSUE THREAD

**Issue by johnchourajr** [getkirby/panel#795]
My /content and /site folder on the VPS is set to 755, and I'm still having this issue.

Here is what I see.
![screen shot 2016-03-06 at 11 28 20 pm](https://cloud.githubusercontent.com/assets/6431920/13578105/ca25fce8-e44a-11e5-9889-35a2f44c1a9e.png)

Not sure how to resolve this, I've tried doing a fresh install of the /kirby folder from 2.2.3, but it's showing that there are no diffs from what I had before and what the fresh install did. 

I should also note, that I have full access to the panel on my local machine.

**Comment by lukasbestle** [comment]
A quick checklist:

- Have you applied the permission recursively to all directories and folders in the `content` directory?
- Does your webserver (Apache probably) run as the user that owns the files? If no, verify that the group of all files in the `content` directory is `www-data`/your webserver's group and set the permissions to `775`.

**Comment by johnchourajr** [comment]
@lukasbestle Went through your checklist, still no luck. I'm editing the permissions through Transmit, here is a screenshot for reference. Any other ideas?

<img width="262" alt="screen shot 2016-03-07 at 2 28 53 pm" src="https://cloud.githubusercontent.com/assets/6431920/13585499/f26703ac-e470-11e5-953f-f68b38141f7d.png">

**Comment by texnixe** [comment]
As @lukasbestle suggested, have you also checked ownership? If you ssh into your server and type `ls -la` do you see an entry similar to this for the content directory?

```
drwxrwxr-x 11 www-data www-data   4096 Feb 26 11:40 content
```

This might be different depending on your webserver group.

**Comment by johnchourajr** [comment]
@texnixe 

I think you're onto something, I'm seeing this `drwxrwxr-x 11 root     root     4096 Mar  7 00:04 content`

How can I change root to www-data?

**Comment by johnchourajr** [comment]
Just ran `sudo chown -R www-data:www-data /var/www` and I fixed it. All good!
