### ISSUE TITLE
Saves the wrong language

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#806]
This time I add it here directly because I'm sure it's a bug.

I use multi language. The issue appear when I switch from the default language to another language, make some changes and save it.

### "Redirects" to another language, then save

It appears like it saved it correctly but when looking at the language it has switched it to another language, which means it overwrite the wrong language.

***It's really disturbing because all the work on the another language is lost.***

**I don't have much clues but here are some:**

- If I always click on the browser address and hit enter (reload page) before making adjustments and then edit and save the problem does not seems to appear.
- It does not seems to appear every time and not to every page. Random kind of feeling.
- The page is a visible one which means a number in the content folder.
- I use the development branch.

**Comment by distantnative** [comment]
Could you provide your language config settings and a bit more detailed (maybe step-by-step) description? Would help a lot to reproduce this.

**Comment by jenstornell** [comment]
**In config.php**

```php
<?php
c::set('languages', array(
	array(
		'code'    => 'sv',
		'name'    => 'Swedish',
		'locale'  => 'sv_SE',
		'url'     => '/',
		'default' => true,
	),
	array(
		'code'    => 'en',
		'name'    => 'English',
		'locale'  => 'en_US',
		'url'     => '/en',
	),
	array(
		'code'    => 'de',
		'name'    => 'Deutsch',
		'locale'  => 'de_DE',
		'url'     => '/de',
	),
));
```

**Step by step**

1. Add a few pages.
1. Make the pages visible, which means they will have sorting numbers.
1. Edit one of the pages and write something on the default language.
1. Change language to another.
1. Change the content and write something in this language.
1. Do the same for the last language as well.
1. Switch languages and check that they have the correct content.
1. Be aware if the language switches automatically after save.

Because this problem feels random maybe you need to do it a few times.

**Maybe**

I removed the prefixed number and made the page not visible. So far I did not have the problem anymore but because I have not tested so many times yet I cannot say it depends on that.

I can update if I'm sure it's the visible pages in combination with multi language that creates this bug.

**Comment by distantnative** [comment]
Could you check it with the most recent version from the develop branch. I have spotted something that got added a few minutes ago and I think, this could solve the origin of this issue.

**Comment by jenstornell** [comment]
Oh. I just reconstructed my whole structure of my site so that would now be difficult. Now it does not rely on visible, but instead of a modified version of the structure field ([snippetfield](https://github.com/jenstornell/kirby-snippetfield)).

But you say you have probably found it so I close this one and open it again if the problem comes back.

**Comment by jenstornell** [comment]
I had not restructured my whole site. Some parts was using the old structure. I've been working on that part for a while and no problems appeared. It seems like it's solved. Thanks!
