### ISSUE TITLE
User field: inconsistent default value

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#810]
I think we are using the default value for the user field very inconsistently:
If I interpret it correctly, this line (https://github.com/getkirby/panel/blob/master/app/fields/user/user.php#L19) will actually make the field always default to the current user if none is already saved. There seems to be no way to deactivate that. However, I think there is already a better default mechanism implemented, which we are just not using: https://github.com/getkirby/panel/blob/master/app/src/panel/models/page/blueprint/field.php#L116-L120. So the User field would just have to pre-define its default array:

``` php
$this->default = array('type' => 'user');
```

Which should work as well (when removing the line from `UserField::value()`) and would leave the possibility to actually change the default mechanism through the blueprint:

```
contactperson:
  label: Contact Person
  type:  user
  default: false
```

**Comment by lukasbestle** [comment]
I just tested this with Kirby 2.3.1 and couldn't reproduce it.
Setting `default` to a username pre-selects that user, setting `default` to `false` disables the preselection.

Please reopen if this issue still exists.

**Comment by Sija** [comment]
> If I interpret it correctly, this line (https://github.com/getkirby/panel/blob/master/app/fields/user/user.php#L19) will actually make the field always default to the current user if none is already saved.

@lukasbestle Above mentioned line is still there and there's no way to see in the panel if selected user was just preselected from default or is it an actual value of the field.

**Comment by lukasbestle** [comment]
> Above mentioned line is still there

Yes, but using a `default` value of `false` works, so the field does not default to the current user. There is a way to disable it.

> there's no way to see in the panel if selected user was just preselected from default or is it an actual value of the field.

What do you mean exactly? That's just the way the defaults work. It's the same with select fields.

**Comment by LeBenLeBen** [comment]
I’m using Kirby 2.5.4 with the same panel version and I have a problem with this. I have a field setup like this:

```
  author:
    label: User
    type: user
    width: 1/3
    translate: false
    default: false
```

While creating a new page using this field, the value is empty:

![capture d ecran 2017-08-16 a 11 43 40](https://user-images.githubusercontent.com/793344/29357585-5b9dfabe-8278-11e7-947b-46419901e041.png)

Once I fill-in some fields (not this one) and I save the page, a value appear in the panel, which is my current user:

![capture d ecran 2017-08-16 a 11 44 08](https://user-images.githubusercontent.com/793344/29357579-57578eac-8278-11e7-8cc8-9803543556a5.png)

But this value is not in the page content file:

```
----

Authoruser: 

----
```

If I save again the page, the value is now added to the content file:

```
----

Authoruser: benoit-burgener

----
```

The panel should not pre-fill a user field with the current user in any case if `default` is set to `false`.

**Comment by texnixe** [comment]
Yes, I can reproduce this. You can't even select the empty option and save that

**Comment by lukasbestle** [comment]
You can now set the `default` option to `false` to default to the empty option or you can set it to any existing username to default to that user.

**Comment by LeBenLeBen** [comment]
@lukasbestle I made a quick test, it works perfectly, thank you!
