### ISSUE TITLE
Allow spaces in the beginning of a textarea

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#815]
It's sometimes needed to keep the spaces in the beginning of a textarea for some custom form fields. Read more about the issue here:

https://forum.getkirby.com/t/allow-spaces-in-the-beginning-of-a-textarea-in-the-panel/3594

Now the spaces in the beginning of a textarea is stripped out.

### Possible solution

In this case I don't like the idea of having an option for it in the blueprint because it should be handled by the field itself. Instead I would like it to be a data attribute (or similar) with information about it.

```html
<textarea data-allow-whitespace="true"></textarea>
```

If the panel sees this, it will allow spaces on that field.

**Comment by texnixe** [comment]
Could you pls. check if your issue is a duplicate of https://github.com/getkirby/panel/issues/322 or related?

**Comment by jenstornell** [comment]
Yes, it's the same issue, at least in the beginning of the post. Do you think I should move my possible solution to that issue instead and closing this one?

**Comment by texnixe** [comment]
Would make sense to keep it all in one place.

**Comment by jenstornell** [comment]
Closing it because if duplicate issue. The content is copied to that issue.
