### ISSUE TITLE
Configuration option to set a custom favicon path

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#819]
See [this topic](https://forum.getkirby.com/t/setting-a-favicon-for-the-panel/3761?u=lukasbestle).

**Comment by mungle** [comment]
+1 (better an area where to write custom code -as ex. to add different favicons formats...-)

**Comment by bastianallgeier** [comment]
There's now a new panel.favicon option available on the develop branch, which can be used to set a custom one for the panel. 

It can be used like this in your config: 

```php
c::set('panel.favicon', 'assets/images/favicon.png');
```
