### ISSUE TITLE
Show the URL with correct Umlauts instead of Punycode

### ISSUE THREAD

**Issue by tweh** [getkirby/panel#821]
See https://forum.getkirby.com/t/kirby-panel-and-umlaut-urls/

I think the panel should show the same URL as the user sees in the browser to prevent confusion for _non-nerdy_ clients …

![6d902ad23a6c107e13939e1a91f438b5d16c8b14](https://cloud.githubusercontent.com/assets/3011538/14421481/363e7ee4-ffd2-11e5-8b1f-b1bd97ff0967.png)

**Comment by jenstornell** [comment]
+1 The linked url should still go to the real / ugly url, I think.

**Comment by lukasbestle** [comment]
This is now implemented, see #888. Could you please test if that works? Please note that you need to have the `intl` PHP extension installed, otherwise there will be no difference. A screenshot would be great!

**Comment by lukasbestle** [comment]
I found a way to test this locally. This is now implemented on the develop branch for Kirby 2.3.2. Please note that it requires the `intl` extension to work as stated above. However it's backwards-compatible with the old way.

**Comment by tweh** [comment]
Hi,

Im sorry, I’m quite busy and had no time to test it jet. Hope I find some time soon …

Best,
Tobi

**Comment by lukasbestle** [comment]
No problem. Since I was able to test it, it's probably fine. :)
Feel free to test it anyway in case I missed anything.
