### ISSUE TITLE
Field assets are not registered correctly with the new registry

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#825]
https://forum.getkirby.com/t/register-plugin-with-set/3827

**Comment by puckey** [comment]
+1

**Comment by lukasbestle** [comment]
Seems like this doesn't only apply to the registry but also to "normal" fields: #831.

**Comment by distantnative** [comment]
I think this is a duplicate of #831 - and since that one is the more general one, I'm closing this issue.
