### ISSUE TITLE
Field Plugin – assets are not loaded

### ISSUE THREAD

**Issue by gerritvanaaken** [getkirby/panel#831]
With the new panel 2.3.0, my panel plugins (e.g. https://github.com/storypioneers/kirby-selector) cannot put their js and css files to the panel assets files:

http://localhost/panel/plugins/css?v=2.3.0
http://localhost/panel/plugins/js?v=2.3.0

These files are empty. Changing the panel to latest stable fixes it.

**Comment by bastianallgeier** [comment]
Just fixed this on the develop branch.
