### ISSUE TITLE
site()->index()->toArray() gives error

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#832]
Kirby 2.3 beta

I'm not sure if it's just the panel but in a field I do this:

```
print_r( site()->index()->toArray() );
```

The array I get is fine, but above it I also get a notice:

> Notice: Undefined index: tinyurl.enabled in C:\wamp\www\panelia\kirby\core\page.php on line 197

I don't use tinyurl.

**Comment by lukasbestle** [comment]
This shouldn't be related to `site()->index()->toArray()` specifically.

Does it also happen:

a) in Kirby 2.2.3
b) when getting just one page?
c) if you leave out the `->toArray()` at the end?

**Comment by lukasbestle** [comment]
This was sort of related to the Panel in that the error is triggered when the tinyurl component is not loaded. Because the Panel does not load components, you see the error.

This is now fixed for Kirby 2.3.1.
