### ISSUE TITLE
develop: The template is missing

### ISSUE THREAD

**Issue by mrflix** [getkirby/panel#842]
Hi! I encountered this bug today that whenever I want to create a subpage in the panel it throws this error:

![screen shot 2016-04-29 at 11 09 22](https://cloud.githubusercontent.com/assets/60777/14912196/dd8c76a2-0dfa-11e6-9c25-c526f2c16f07.png)

What did I do wrong? When I roll back to a development version from some weeks ago it doesn't break. The blueprint is there, I even created a `site/template` for the page although I don't need a template because I use the child pages as a structured data source.

**Comment by texnixe** [comment]
Which Kirby version is that? The current 2.3 beta or stable Kirby 2.2.3? What has changed from your development version from a few weeks ago to now?

**Comment by mrflix** [comment]
I checked out kirby, toolkit and panel development branches. `kirby.php` says `static public $version = '2.3.0';`.
My content changed entirely – its a new project. I just copied over a version of panel from another project. That panel is also from the development branch but from some weeks ago. I think max 2 weeks old.

**Comment by texnixe** [comment]
Could you pls. check out the latest panel version and test if that works?

**Comment by distantnative** [comment]
Yes, the most current version has this bug. Quick temporary fix is to delete the sort-line from panel/app/forms/pages/add.php (on my phone, otherwise I'd be mire specific)

**Comment by mrflix** [comment]
Cool, that was quick. Thanks guys!

**Comment by distantnative** [comment]
The one added in this commit: https://github.com/getkirby/panel/commit/b2850d9672bc3fd57244312b607b1550ab6b855d#diff-0255f5c8a953b34669876a390de96972R12

**Comment by distantnative** [comment]
Got fixed on the develop branch.
