### ISSUE TITLE
Kirby 2.3 Beta 2 - Page translation results in default.{lang}.txt

### ISSUE THREAD

**Issue by p-h-i-l** [getkirby/panel#843]
On a multi-language text site i have a template for `News` which can have `newsarticle` child pages. 

_What i want to do: _
Create new Article and translate it to english.
_Expected behaviour: _
Article is created. Switching the language results in a copy of the same template with the old translation (Kirby 2.2).
_What actually happens_
New language file for the translation is called **default.en.txt** ...and i can't translate the page without going into the content folder and changing the name to the appropriate template.

news.yaml

    pages: 
      template: newsarticle

newsarticle.yaml

    ...

**Comment by bastianallgeier** [comment]
Is this the latest version from the develop branch on github? I know that we had this bug in beta 1. But I was pretty sure we already fixed it.

**Comment by p-h-i-l** [comment]
Jup, unfortunately... 
i updated all submodules this morning, and again just now to make sure that i am intact on the latest version.

**Comment by bastianallgeier** [comment]
Yikes, thanks for checking! I will try to fix this asap.

**Comment by bastianallgeier** [comment]
Ok, I just fixed it on the develop branch.

**Comment by p-h-i-l** [comment]
Just updated the installation, everything seems to be in order now! 

Thanks for the fast response!
Regards from Switzerland and a have a great evening!

**Comment by bastianallgeier** [comment]
Yay! I'm really glad to hear it. 
Greetings from Germany :)
