### ISSUE TITLE
Structure field on multi language bug

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#848]
I have a multi language site. With the new version I have a bug.

- When I load/reload a page in a language it's working.
- If I switch language and then edit a structure field, sometimes there is a bug.

In the example below DE bugs. When trying it again, EN bugs.

![bug1](https://cloud.githubusercontent.com/assets/927011/15068246/35488b3a-1376-11e6-89cf-04ca5c853895.gif)

@bastianallgeier If you need the site to test it, it's the same site I sent you the last time. The page is called "fragor-och-svar".

**The error message in english:**

>Article can not be found

**Comment by bastianallgeier** [comment]
I just downloaded your version again. Replaced the kirby and panel folder with the latest version of 2.3.0 and wasn't able to reproduce it. I tried various ways of switching languages, editing and saving, but I didn't run into the same issue. 

Could you please check again?

**Comment by jenstornell** [comment]
Now I've updated both the core and the panel to development branch and I still get this error.

It feels kind of random which language get the error. It's sometimes DE, sometimes EN and sometimes SV.

Be aware that I don't save before I switch language. I just "Edit" and "Abort" and then switch language. My guess is that is loses the info about what language I'm editing inside the structure field.

**Comment by bastianallgeier** [comment]
Does it happen in your local version or also on a public server. I tried again, creating quite some chaos with the content, but I still don't get the same issue here. Super difficult to debug. A server version would make it a bit easier I guess.

**Comment by jenstornell** [comment]
I've put it on the web now (localhost before). You have got a mail with login. Hopefully you can see what I see.

![image](https://cloud.githubusercontent.com/assets/927011/15069767/2d0242cc-1380-11e6-8fd7-2dde20a1be6b.png)
