### ISSUE TITLE
validate field not respected in 'add a new page' dialog

### ISSUE THREAD

**Issue by puckey** [getkirby/panel#860]
when I add a validate option like 'max: 20' to the title field, it is not respected in the 'add a new page' dialog

**Comment by malvese** [comment]
Just [wrote about this in the forum](https://forum.getkirby.com/t/validate-a-title-when-we-create-a-page/4306), so +1.
In my case, the title is a year so I would have liked to validate it as a `num` and with `min` value.

**Comment by lukasbestle** [comment]
Duplicate of #845. Discussion continues there.
