### ISSUE TITLE
Uploading an image removes all previously generated thumbnails

### ISSUE THREAD

**Issue by samvantoever** [getkirby/panel#863]
I'm trying to pre-generate multiple thumbnails when a file is being uploaded using a hook:

```
kirby()->hook("panel.file.upload", function($file) {
	$sizes = c::get("imgSizes");

	foreach ($sizes as $key => $val) {
		$file->resize($val, $val);
	}
});
```

I've been looking at the thumbnail folder to see if it works when I upload an image, but I noticed something strange. Whenever I upload a file all previously generated thumbnails are being removed. Am I missing something here, or is this a bug?

**Comment by texnixe** [comment]
Yes, this is weird, I just tested this and can reproduce it. While all thumbs generated otherwise, all thumbnails generated via the hook are removed as soon as a new image is uploaded/resized.

**Comment by texnixe** [comment]
This is not a panel issue though.

**Comment by texnixe** [comment]
See here: https://github.com/getkirby/kirby/issues/329
