### ISSUE TITLE
Register set default.yml blueprint crashes panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#881]
>Panel Error:
Error without a useful message :(
It happened here:
File: /panel\app\src\panel\models\page\blueprint.php
Line: 85

All other blueprints works.

Registered from a plugin instead of the blueprints folder.

**Comment by lukasbestle** [comment]
You opened the same issue in May already. :D
See #851.

**Comment by jenstornell** [comment]
Oh, sorry, I'm getting old...
