### ISSUE TITLE
Can't register a blueprint for site.yml

### ISSUE THREAD

**Issue by samnabi** [getkirby/panel#889]
In a plugin, if I register a blueprint to override the default `site.yml` it won't work.

Perhaps this is intentional? Maybe it's not a good idea for plugins to override the Site blueprint. If so, there should be a note in the docs.

**Comment by texnixe** [comment]
Not 100% sure, but as far as I know, you cannot override any blueprints from a plugin. From my point of view, plugin blueprints should not override any existing blueprints.

**Comment by lukasbestle** [comment]
You can't override blueprints as @texnixe wrote, but you should be able to set it at least if no one exists in the blueprints directory.

**Comment by samnabi** [comment]
Sorry, I don't know why I said override. The problem persists if you move the `site.yml` to a plugin's blueprint folder.

Steps to replicate:

1. Download Kirby Starterkit
2. Create new folders: `site/plugins/test` and `site/plugins/test/blueprints`
3. Create plugin file `site/plugins/test/test.php`:
    ```php
    <?php
    
    $kirby->set('blueprint', 'site',      __DIR__.DS.'blueprints'.DS.'site.yml');
    ```
4. Move `site/blueprints/site.yml` to `plugins/test/blueprints/site.yml`
5. Navigate to `http://domain.com/panel/options`. It's using the default blueprint, not the `site.yml`

**Comment by lukasbestle** [comment]
Thank you for the information, we will look into this.

**Comment by lukasbestle** [comment]
This was caused by the same issue as #851 and magically solves itself in Kirby 2.3.2.
