### ISSUE TITLE
Thumbs get deleted if thumbs are generated in hooks

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#890]
See getkirby/kirby#329:

```php
kirby()->hook('panel.file.upload', function($file) { 
  $file->resize(300);
});
```

**Comment by lukasbestle** [comment]
Moved from #329:

> After digging through the source code I've found the cause of this issue.
> 
> I don't know for what reason, but all the thumbnails are removed on purpose when uploading a file. See the following file on line 66: https://github.com/getkirby/panel/blob/master/app/src/panel/models/page/uploader.php
> 
> This removeThumbs() function is also called a few times within:
> 
> https://github.com/getkirby/panel/blob/master/app/src/panel/models/file.php
> https://github.com/getkirby/panel/blob/master/app/src/panel/models/page.php

**Comment by bastianallgeier** [comment]
Fixed!
