### ISSUE TITLE
Error when uploading an SVG that contains a style element

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/panel#895]
When uploading an SVG that contains a `style` element, a »Forbidden mime type« error is displayed in the top right. (Kirby / Panel version: 2.3.1)

![error](https://cloud.githubusercontent.com/assets/15672385/16954707/201134d8-4dd2-11e6-87ee-204ffb913f80.png)

You can test it with these two SVGs: [kirbyicon.zip](https://github.com/getkirby/panel/files/371175/kirbyicon.zip)

**kirbyicon_attribute.svg** uses an attribute to style the path: 

```
<path fill="#FF0200" d="…" />
```

**kirbyicon_style_element.svg** uses a style element: 

```
<style>path{fill:#FF0200;}</style>
<path d="…" />
```

When you try to upload **kirbyicon_style_element.svg** via the panel, you should get an error.

**Comment by macx** [comment]
The same for me, please fix this!

**Comment by bastianallgeier** [comment]
This is finally fixed on the develop branch.
