### ISSUE TITLE
Sort subpages in sidebar by custom field

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#896]

**Comment by malvese** [comment]
Also sort by template? It can make the list more legible if you allow multiple subpages types.

**Comment by bastianallgeier** [comment]
That's both already possible! 

```
pages:
  sort: myfield asc
```

…and…

```
pages:
  sort: template asc
```

**Comment by malvese** [comment]
Nice!
But I couldn't find it in the Docs. If it is indeed not documented, should I open an issue in the website's repo?

**Comment by bastianallgeier** [comment]
Sorry for not documenting it so far. An issue would really help.
