### ISSUE TITLE
Validate max on text fields with only numbers does not check for string length but value of number

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#899]
https://forum.getkirby.com/t/question-about-validate-max/4840

**Comment by lukasbestle** [comment]
I agree that this is a bug. However it's rather hard to fix as validators don't know anything about the field type. The only way would be to conditionally choose the validator in the field definition.

Since this is a breaking change, we will fix this in Kirby 2.4.

**Comment by texnixe** [comment]
Maybe we should separate the validators, to have one for strings and one for numbers.

**Comment by lukasbestle** [comment]
Makes sense. Then it's not even a breaking change as users who don't need the new behavior will just keep the old one.
I will look into this and if it works, I will add a `minLength` and `maxLength` validator.

**Comment by lukasbestle** [comment]
This is now fixed and will be included in Kirby 2.3.2.
