### ISSUE TITLE
Problem with checkboxes

### ISSUE THREAD

**Issue by iksi** [getkirby/panel#908]
Situation: You have a `categories` field with some predefined options and the following in your content file:

`Categories: Nein, Sachbücher, Kunst`

From the above `Nein` is not defined in your options. Upon saving in the panel the new content is:

`Categories: Sachbücher, Kunst`

In my opinion `Nein` gets removed correctly. The problem arises when the content is as follows:

`Categories: Nein`

Now upon saving the field gives an error and does not remove the unavailable option from the content. Nor do you as a user have the possibility to remove this options, you’re stuck.

This can happen for instance with dynamic options and an option is removed but still present in the content.

**Comment by iksi** [comment]
For my current use case I have temporarily solved it by replacing the `value` function in `fields/checkboxes.php` with the following:

````PHP
public function value() {

    $value = InputListField::value();

    if(!is_array($value)) {
      $value = str::split($value, ',');
    }

    return array_keys(array_intersect_key(array_flip($value), $this->options()));

  }
````

I didn’t make a pull request just yet as I can’t oversee whether this has bad implications elsewhere.

**Comment by bastianallgeier** [comment]
your solution is great and I don't see any connected issues! I just added it on the develop branch.
