### ISSUE TITLE
Wrong checkbox state for different languages

### ISSUE THREAD

**Issue by flokosiol** [getkirby/panel#910]
There is a problem with checkboxes for translated pages showing the wrong value/state. Please see this [forum topic](https://forum.getkirby.com/t/checkbox-value-for-different-languages/5059?u=flokosiol).

## What I've done …

+ Downloaded a fresh [Kirby langkit](https://github.com/getkirby/langkit)
```
Toolkit version: 2.3.2
Kirby version: 2.3.2
Panel version: 2.3.2
```
+ Added a checkbox field to `site/blueprints/default.yml`
```
test:
  label: Test
  type: checkbox
  text: This is just a test
```

+ Created a page (default language is EN), checked the checkbox and saved it
+ Switched language to (so far not existing) german translation, **unchecked the checkbox** (as inherited from the default language) and **then** saved the german version for the first time.

## Strange result

+ The value in the german text file is `0` (as expected)
+ The checkbox in the panel for the german page is checked (as not expected)

![kirby-langkit-checkbox](https://cloud.githubusercontent.com/assets/11918336/18200493/5db3131e-7105-11e6-93d3-779f9a63cdb6.png)

If I switch back to the default language (EN), uncheck the checkbox and switch back to german, the checkbox is also unchecked.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
