### ISSUE TITLE
Field assets are not loaded

### ISSUE THREAD

**Issue by bartvdboomen** [getkirby/panel#914]
The assets defined in Fields are not being loaded. Also the default fields (e.g. DateField) which have assets, don't work as they should.

The date field works because of the loading of form.min.js. However, it should load date.js as an asset as it is defined in the class:

```
static public $assets = array(
    'js' => array(
      'date.js'
    )
  );

```

**Comment by lukasbestle** [comment]
I have used field assets quite recently and they worked fine. Could you please tell me your Kirby and Panel version, PHP version and the error/wrong behavior you are getting?

**Comment by bartvdboomen** [comment]
Hello,

I'm using version 2.3.2
PHP Version: 5.6.16

The plugin I'm trying to use right now is the WYSIWYG editor from the plugins site:
http://getkirby-plugins.com/wysiwyg-editor

I don't get any errors. The loading of the PHP files works fine. I added the wysiwyg field to my blueprint, but no assets are loaded when I edit the page.

...
  richtext:
    label: Text
    type:  wysiwyg
...

**Comment by lukasbestle** [comment]
Thanks, I will look into this.

**Comment by bartvdboomen** [comment]
Hello, I created an issue in the AssetsController, which caused the javascript from not being loaded. The assets are loaded fine now.
