### ISSUE TITLE
Inherit default blueprints

### ISSUE THREAD

**Issue by robjames** [getkirby/panel#92]
*Feature request*

I think it would be great if blueprints inherited from the default blueprint. Then you would only need to include keys that you wanted different.

You could even have a key `inherit` to choose which blueprint to inherit from rather than just default.

**Comment by theWeird** [comment]
just found this issue.

A few moments ago I created a pull request with a modification to import "field snippets" into blueprint field lists. https://github.com/getkirby/panel/pull/433

would this fix your issue?

**Comment by RHansmann** [comment]
The pull request #433 solves this issue in a very flexible way. Forget about my solution described above.

**Comment by distantnative** [comment]
Will be part of the upcoming 2.2 (currently as beta on the `develop` branch). Read more: https://github.com/getkirby/panel/pull/433#issuecomment-150559661
