### ISSUE TITLE
Image field init bug, !?

### ISSUE THREAD

**Issue by H-i-red** [getkirby/panel#922]
If I have not selected any image, and navigate or save the page in the panel, I get multiple get requests.. If I have an Image selected then I do not.

I saw this in image field js file : 
```
 // avoid multiple init
      if (field.data('imagefield')) return true;
      field.data('imagefield', true);
```

But I guess thats not working.. 

![skarmavbild 2016-09-26 kl 16 56 16](https://cloud.githubusercontent.com/assets/19476159/18839131/32fa07c8-840a-11e6-8bf8-8eced6e66b1e.png)

**Comment by H-i-red** [comment]
```
if($image == '') {
      return new Brick('option', '', array(
        'value'    => '',
        'selected' => $selected
      ));
    } else {
      return new Brick('option', $image->filename(), array(
        'value'      => $filename,
        'selected'   => $selected,
        'data-url'   => $image->url('edit'),
        'data-thumb' => $image->crop(75)->url()
      ));
    }

```

**Comment by bastianallgeier** [comment]
I tried to reproduce this, but wasn't able to. The additional GET requests in your example IMHO come from navigating.
