### ISSUE TITLE
Datepicker is broken (beta)

### ISSUE THREAD

**Issue by foobartel** [getkirby/panel#925]
Seems like the datepicker is broken in the latest beta, it only displays one option, not the usual picker. Supposedly this type error in the panel JS is the culprit. 

```
Uncaught TypeError: Cannot read property '0' of undefined
panel.min.js?v=2.4.0 beta 1:2 
P @ panel.min.js?v=2.4.0 beta 1:2
draw @ panel.min.js?v=2.4.0 beta 1:2
show @ panel.min.js?v=2.4.0 beta 1:2
N.a._onInputFocus @ panel.min.js?v=2.4.0 beta 1:2
```

![screen shot 2016-09-30 at 5 09 41 pm](https://cloud.githubusercontent.com/assets/1708876/18988271/73438080-8738-11e6-88a4-e72c273a0367.png)

**Comment by bastianallgeier** [comment]
Fixed!
