### ISSUE TITLE
Additional 'amp;'s added on page save (2.4.0 beta)

### ISSUE THREAD

**Issue by foobartel** [getkirby/panel#926]
One of my page fields contains `&amp;` and upon saving one of the pages, another `amp;` gets added, each new one without the '&' though. 

![screen shot 2016-09-30 at 5 55 07 pm](https://cloud.githubusercontent.com/assets/1708876/18988565/e581ab6c-8739-11e6-8079-acc06116d3dc.png)
![screen shot 2016-09-30 at 6 12 26 pm](https://cloud.githubusercontent.com/assets/1708876/18988566/e5d74e50-8739-11e6-9cce-7108265b61bd.png)

**Comment by ralfgoeke** [comment]
Probably related: In text fields, for example the title field, umlauts get replaced with the HTML Entity on save.

`ö  -> &oouml;`

**Comment by bastianallgeier** [comment]
Fixed 💃
