### ISSUE TITLE
Icons Size

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/panel#927]
Hi there.
Just a tiny tiny design "bug" (not really a bug)

As you can see from the screen attached the icons at the current size don't look perfectly crisp.
I think that's because the font awesome icons are designed on a 14px grid, and you have the font size correctly set at 14px somewhere in the css, but later is overwritten and set a 16px and as a result the icons look a bit blurry.

![screen shot 2016-09-30 at 4 40 56 pm](https://cloud.githubusercontent.com/assets/1738077/18995622/3e97b276-872d-11e6-90d3-66ff161879ce.jpg)

The icons on the left are set at 14px and the one on the right are the current one.
The image is from a "normal" screen, on a retina the "problem" is less pronounced.

Keep up the good work guys.

**Comment by bastianallgeier** [comment]
Fixed!
