### ISSUE TITLE
Kirby url option is not considered by the Panel

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#928]
See [this topic](https://forum.getkirby.com/t/hosting-on-docker-with-nginx-reverse-proxy/5308/14?u=lukasbestle).

I am pretty sure that we have fixed this issue already in one of the recent Kirby releases. @bastianallgeier?

**Comment by 0xsven** [comment]
Is there a quick and dirty fix for this? I would like my clients to work on the content...

**Comment by lukasbestle** [comment]
@0xsven You can use a custom `site.php` file and override the `index` URL. That should then also apply to the Panel.

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
