### ISSUE TITLE
Error when trying to save site settings (2.4.0 beta)

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#930]
See [this thread](https://forum.getkirby.com/t/2-4-0-beta-1-with-xampp-7-0-8-on-windows/5447) in the forum

Error message: `Undefined variable: data`

can be tracked to 

=> panel/app/src/panel/models/site.php, line 104

```
$event = $this->event('update:action', ['data' => $data]);
```

**Comment by bastianallgeier** [comment]
Just fixed this.
