### ISSUE TITLE
'required: true' not working on Site Options (site.yml) — Panel v2.3.2

### ISSUE THREAD

**Issue by evvvritt** [getkirby/panel#934]
Hi, I'm trying to add a required number field to the Site Options (site.yml) blueprint, but the field is not showing or behaving as required. Also, it isn't honoring `min`, `max` or `default`.

```
# site/blueprints/site.yml

logoMaxW:
    label: Width
    type: number
    required:true
    min:0
    max:250
    step:1
    default:195
    help: >
      'max-width' in px, but logo won't exceed 3x nav height firstly
```

```
# trial version
Toolkit version: 2.3.2
Kirby version: 2.3.2
Panel version: 2.3.2
```

Any help much appreciated !

**Comment by bastianallgeier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ['required: true' not working on Site Options (site.yml) — Panel v2.3.2](https://trello.com/c/7kRgHfyx/11-required-true-not-working-on-site-options-site-yml-panel-v2-3-2)

**Comment by bastianallgeier** [comment]
I just double-checked and this is working.
