### ISSUE TITLE
Kirby 2.4.0 beta 2: Undefined index: somefield

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#935]
The error occurs after adding an entry in a structure field in the default language and then trying to switch to another language.

Whoops\Exception\ErrorException 
…/branches/multilang/page.php206

![bildschirmfoto 2016-10-18 um 14 35 01](https://cloud.githubusercontent.com/assets/5312492/19477789/25de5b38-9540-11e6-96cf-cd256a4a07d1.png)

**Comment by dweidner** [comment]
I am facing the same problem with a normal text field. I have a multi-language site (default language german, additional language english), switched in the panel from german to english and saw the same exception just for a different field.

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
