### ISSUE TITLE
Kirby 2.3.2 Cache problem: Structure field entries not recognized in second language

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#936]
See https://forum.getkirby.com/t/strange-structure-behaviour-in-2-3-2/5542

Don't know if this issue was tackled in 2.4, maybe not successfully https://github.com/getkirby/panel/issues/935?

**Comment by lukasbestle** [comment]
https://forum.getkirby.com/t/2-5-5-struct-field-entries-not-shown-in-second-lang-unless-save-there-too/8398?u=lukasbestle
