### ISSUE TITLE
Compatibility with Permissions in Kirby 2.4.0 beta 2

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#939]
I just got an issue report to my plugin. I don't have time to debug this at the moment. I have so many other things to do.

But if it's important that all plugins will work I suggest that you take it for a spin in the new version. Else I will look into it when I update the plugin next time at some point in the future.

https://github.com/jenstornell/kirby-revisions/issues/33#issuecomment-255363582

> Hey there! 
> I just wanted to let you know that something seems to by incompatible with the new Kirby 2.4.0 beta 2. It seems to be an issue related to the new permissions system.
> 
> I can see the revision-list in the panel, but when i try to interact with (/click on) any revision, i get a
> 
> Kirby \ Panel \ Exceptions \ PermissionsException
> You are not allowed to do this
> Tested it on two different existing websites but not on starterkit

**Comment by bastianallgeier** [comment]
I fixed this in the latest version on the develop branch.
