### ISSUE TITLE
Checkbox state not reflected properly in multilang setup

### ISSUE THREAD

**Issue by kamasheto** [getkirby/panel#941]
### Steps to reproduce
- Add a checkbox to a blueprint
```
  test_checkbox:
    label: Test checkbox
    text: Check me
    type: checkbox
```
- Setup multilang (config.php)
```

c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'English',
    'default' => true,
    'locale'  => 'en_US',
    'url'     => '/',
  ),
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'locale'  => 'de_DE',
    'url'     => '/de',
  ),
));
```
- In default language save the checkbox as checked
- In another language save the checkbox as unchecked

### Actual output
- Content files are updated properly (.en.text => `Test-checkbox: 1`, .de.txt => `Test-checkbox: 0`)
- Panel form shows **both fields checked**

### Expected output
- Checkbox to be unchecked when content file is 0

### Diagnosis
- When value of field is non existent, default language value is picked. In this case, 0 is being incorrectly identified as non existent causing the default language setting to be parsed.

**Comment by bastianallgeier** [comment]
I fixed this on the develop branch for the next update.
