### ISSUE TITLE
Renaming Image, while it's selected in image panelfield

### ISSUE THREAD

**Issue by TimGr** [getkirby/panel#944]
Hey, I stumpled over this little issue today... 

Steps to reproduce it:
1. Upload image "xyz.jpg"
2. Select it in image panelfield and save. Everything looks good and the image is displayed.
3. Rename the selected image and save
4. Frontend-Page is completly broken

The field still stores the old image name in the content file but can't find it. I know this is maybe not a normal usecase...

In my template I use this:
```php
<?php if($page->heroimage() != ''): ?>
  // echo image 
<?php endif; ?>
```

What do you think?

**Comment by texnixe** [comment]
I think you should always check if the image exists, checking if the field contains anything does not help in this case, you will run into the same issue if you select an image and then later delete it.

**Comment by TimGr** [comment]
Okay, that would be a good workaround for my template but the field still store the image-name, if I don't save the page again.
