### ISSUE TITLE
Visible/invisible toggle not working

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/panel#946]
This is new in 2.4.0
The toggle works fine in the `visible to invisible` direction.

If instead I try to make a page visible I get the bug.

I see the modal but after I click the change button nothing happens.
Here's a quick video of the bug: http://quick.as/ZQPhpPoY

**Comment by texnixe** [comment]
See this topic in the forum: https://forum.getkirby.com/t/bug-invisible-visible-toggle-in-panel-2-4-0/5674

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
