### ISSUE TITLE
permissions: panel.page.read does not hide pages from the pages list

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/panel#950]
Setting `panel.page.read` to false (for all or only for some pages) does not hide the corresponding pages from the pages list/ sidebar.
So clicking on the page leads to a debug page with an permissions exception.

(This feature was functioning alright in the early beta, but the release version of 2.4 has broken the behavior somehow. Last test from me was with commit b9de386.)

For additional information see these threads in the forum:
https://forum.getkirby.com/t/disable-enable-multiple-pages-via-panel-page-read/5671
https://forum.getkirby.com/t/permissions-panel-page-read-does-not-hide-the-pages-from-the-page-list/5683/2

**Comment by krisak** [comment]
I can confirm this. Maybe it is connected to this issue? 
[https://github.com/getkirby/panel/issues/947](url)

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
