### ISSUE TITLE
panel.page.sort not firing as expected

### ISSUE THREAD

**Issue by ShawnCollier** [getkirby/panel#952]
Noticed this after I upgraded to 2.4.0.

https://forum.getkirby.com/t/is-panel-page-sort-broken-in-2-4-0/5689/4

I was trying to use the hook to run code that would update two fields (a time and a date field). In 2.3.2, when I changed from invisible -> visible, the hook would fire as expected and my code would run. But in 2.4.0, it doesn't do anything.

Other hooks, such as **panel.page.update**, work as expected. So it seems to be just relegated to this particular hook.

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch
