### ISSUE TITLE
Error: Invalid Panel URL when deleting images

### ISSUE THREAD

**Issue by p-mylecharane** [getkirby/panel#957]
Using latest steady build. Get this error when deleting images. Any ideas? Has only happened since upgrading to 2.4.0

<img width="846" alt="screen shot 2016-11-14 at 11 04 29 pm" src="https://cloud.githubusercontent.com/assets/18585409/20264306/f73e93d0-aabe-11e6-9d79-a9d3c26fa218.png">

**Comment by bastianallgeier** [comment]
I cannot reproduce this. Could you explain a bit more about the steps you take to get there and what plugins you have installed? Do you use some sort of permission setup?

**Comment by p-mylecharane** [comment]
Hey @bastianallgeier — I worked it out. Was based on an ampersand being in the project url. It was from adding content via the server (not the pane) therefore the urls weren't being sanitized :-/

**Comment by lukasbestle** [comment]
That's still an issue, Kirby should properly encode in the URL.

**Comment by bastianallgeier** [comment]
I only now really understood what the problem is. I just fixed it on the develop branch.
