### ISSUE TITLE
Session is lost when using both http and https

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#958]
```text
https://example.com/panel
http://example.com
```

In the above is the panel on https and the domain on http. When using the panel (https) and then going to the frontend (http) and back to the panel, the panel is logged out.

I guess the same problem appears when they are switched:

```text
http://example.com/panel
https://example.com
```

I guess this is part of a bigger problem that we don't have persistent cookies.

(I'm aware that it's not optimal to have both http and https, but I was having this issue when developing)

**Comment by lukasbestle** [comment]
Kirby uses so-called secure cookies when possible. This means that a cookie set on a HTTPS connection won't be transmitted. The other way around should work though (non-secure cookies are of course also transmitted over HTTPS).

We can't fix this without making HTTPS cookies more insecure.
