### ISSUE TITLE
Delete site image redirect error

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#959]
1. Go to panel options.
1. Add an image.
1. Delete the image by clicking on it and then delete it.

![image](https://cloud.githubusercontent.com/assets/927011/20554767/4e492ce4-b15e-11e6-9e86-62656d7efd2f.png)

Kirby 2.4.0 on a localhost environment.

The image is deleted but the redirect does not work. It's only on the option page. Normal pages works fine.

**Comment by bastianallgeier** [comment]
This has been fixed on the develop branch.
