### ISSUE TITLE
Dashboard edit button error when pages:false in site.yml

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#964]
Fatal error:  Call to a member function nextPageUrl() on null in /panel/app/controllers/subpages.php on line 37

Somehow it does not make sense to set pages to false in the site blueprint because site cannot have no pages anyway. But people seem to do it nonetheless (see https://forum.getkirby.com/t/page-option-hide-true-does-not-hide-the-page/5841/3) when they should be using the max page option. Which results in all pages showing even if they are hidden.

**Comment by bastianallgeier** [comment]
This has been fixed with the pages widget fix.
