### ISSUE TITLE
Title is set as required in a structure field

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#966]
Kirby 2.4.0

## This works fine:

```text
  addresses:
    label: Addresses
    type: structure
    entry: >
      {{street}}<br />
      {{zip}} {{city}}
    fields:
      title2:
        label: Title2
        type: text
      zip:
        label: ZIP
        type: text
      city:
        label: City
        type: text
```

![image](https://cloud.githubusercontent.com/assets/927011/20960971/4375512a-bc63-11e6-883d-4d97503445df.png)

## Does not work as expected

Below sets title as require, but I did not set it.

```text
  addresses:
    label: Addresses
    type: structure
    entry: >
      {{street}}<br />
      {{zip}} {{city}}
    fields:
      title:
        label: Title
        type: text
      zip:
        label: ZIP
        type: text
      city:
        label: City
        type: text
```

![image](https://cloud.githubusercontent.com/assets/927011/20961004/623658a2-bc63-11e6-8cc2-499b69e953b6.png)

See the asterix above.

**Comment by lukasbestle** [comment]
A field of with field name `title` is converted to a `title` field, regardless of the custom type. And `title` fields are always required. I agree that this is a bug when used in structure fields though.

**Comment by jenstornell** [comment]
We have had a similar issue so part of the problem is solved, but it seems like it's missed out of the `required` attribute:

https://github.com/getkirby/panel/issues/814

**Comment by lukasbestle** [comment]
Yep, that seems to be related.

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch. Thanks for your patience!
