### ISSUE TITLE
Select field default empty does not work in this case

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#968]
Kirby 2.4.0

**This works:**

```text
```text
 target:
    label: Target
    type: select
    default:
    options:
      _blank: _blank
      _self: _self
      _parent: _parent
      _top: _top
```

Key value pair works.

**Does not work**

```text
 target:
    label: Target
    type: select
    default:
    options:
      - _blank
      - _self
      - _parent
      - _top
```

A list with just values results in that it takes the first item as default, not an empty value.

**Comment by lukasbestle** [comment]
This is probably because an empty `default` is `null` to PHP. And then `$options[null] === $options[0]`, because ... PHP. ;)

I don't consider this bug critical though, an empty value for `default` is not supported and a fix on Kirby's end would increase complexity.
