### ISSUE TITLE
Different icon for invisible pages

### ISSUE THREAD

**Issue by meszarosrob** [getkirby/panel#97]
Maybe a different icon for invisible pages would be good. Easier to distinguish between the two.

https://www.dropbox.com/s/q4x87g8q9y0qult/Screenshot%202014-08-09%2022.09.00.png

**Comment by distantnative** [comment]
This has been added to the develop branch and will be part of an upcoming release.

It works the way @kompuser has suggested it:

```
title: Just A Contact Page
icon: map-marker
```
