### ISSUE TITLE
All thumbs are being deleted when adding/removing/renaming an image

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/panel#971]
When adding or a removing an image to a page with existing images and thumbs, all the thumbs will have to be created again. When adding/removing an image manually via FTP this does not happen.

See [this thread](https://forum.getkirby.com/t/panel-performance-with-thumbnails/5985) in the forum.

I'm not sure if and how this is connected to this issue: https://github.com/getkirby/panel/issues/296 "Clean up thumbs when files are being deleted".

EDIT:
I just noticed this happens when renaming files, too.

**Comment by texnixe** [comment]
+1 for only deleting thumbs of images that are removed, replaced or renamed.

**Comment by m-artin** [comment]
+2

**Comment by bastianallgeier** [comment]
This is finally fixed on the develop branch. Sorry that it took so long. Killing all thumbs was the "easier" way to do it and I didn't anticipate that it would have such huge negative effects.

**Comment by texnixe** [comment]
At least when uploading a new image, all thumbs still get deleted, I therefore reopened [this issue](https://github.com/getkirby/kirby/issues/460) but am not sure if I should instead reopen this here?
