### ISSUE TITLE
414 Error when using long texts in structured field textarea

### ISSUE THREAD

**Issue by Andi-Lo** [getkirby/panel#974]
I first thought that this is related to the kirby-visual-markdown plugin but it seems that it is a problem with kirby.

In short: If you have a very long text in a structured field textarea with e.g. ~7000 characters then you will exceed the "Request URI" and get an error.

More details in issue reference:
https://github.com/JonasDoebertin/kirby-visual-markdown/issues/101

Thoughts?

**Comment by texnixe** [comment]
Could you please provide more information, like your blueprint, the steps to reproduce it. I just tried to reproduce this in a current 2.4.1 Starterkit, but couldn't, not even with much more than 7000 characters.

**Comment by Andi-Lo** [comment]
Yes you're actually right when using the starterkit it also makes no trouble.

**Comment by texnixe** [comment]
Could you please open an issue in the builder repo. I'm closing this here.
