### ISSUE TITLE
Url validation fails in structure field

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#976]
**Kirby 2.4.1**

This url results in an error:

![image](https://cloud.githubusercontent.com/assets/927011/21268674/0000d244-c3b0-11e6-8e30-af53c7fab7d9.png)

It's a domain that is IDN converted domain from like `http://åäö.com`.

It's the double `--` that is not accepted. With a single dash it works.

**Comment by lukasbestle** [comment]
This is actually a Toolkit issue with the [url validator](https://github.com/getkirby/toolkit/blob/master/lib/v.php#L132-L136). As you can see we need to use a regex and there is currently no absolutely perfect regex to match every valid URL (if you know one or even a really solid way to validate URLs please let us know).

Why don't you just use `http://åäö.com` in the URL field? It's not only human-readable but works just fine as browsers will deal with Punycode automatically.
