### ISSUE TITLE
Blueprint setting for hiding subpages does not work

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#978]
https://getkirby.com/docs/panel/blueprints/subpages-settings#hide-subpages

**Comment by mzur** [comment]
This probably should be fixed [somewhere around here](https://github.com/getkirby/panel/blob/23d7b532caeec151f965429dea50e1f263c57f08/app/src/panel/models/page/options.php#L138).

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
