### ISSUE TITLE
Update false - I can still save with shortcut

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#988]
```text
options:
  update: false
```

Nice that this feature now exists. The save button is gone, great!

But I can still save by on Windows pressing CTRL+S. That should not be possible

![update](https://cloud.githubusercontent.com/assets/927011/21889742/bd2b36e6-d8ca-11e6-8d5c-6955d18fa6e6.gif)

**Comment by lukasbestle** [comment]
Oh, seems like we missed adding a check in the backend. Thanks for reporting.

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
